### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by johnxiongs** [aaugustin/websockets#1009]
```
import asyncio

import websockets


async def hello():
    async with websockets.connect('wss://fstream.binance.com/stream?streams=ethusdt@depth5@100ms') as websocket:
        while True:
            msg = await websocket.recv()
            print(msg)


asyncio.run(hello())

```

```
Traceback (most recent call last):
  File "/home/johnxiong/PycharmProjects/mywork/tests.py", line 13, in <module>
    asyncio.run(hello())
  File "/home/johnxiong/anaconda3/envs/mywork/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/johnxiong/anaconda3/envs/mywork/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/johnxiong/PycharmProjects/mywork/tests.py", line 7, in hello
    async with websockets.connect('wss://fstream.binance.com/stream?streams=ethusdt@depth5@100ms') as websocket:
  File "/home/johnxiong/anaconda3/envs/mywork/lib/python3.8/site-packages/websockets/py35/client.py", line 2, in __aenter__
    return await self
  File "/home/johnxiong/anaconda3/envs/mywork/lib/python3.8/site-packages/websockets/py35/client.py", line 12, in __await_impl__
    transport, protocol = await self._creating_connection
  File "/home/johnxiong/anaconda3/envs/mywork/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/home/johnxiong/anaconda3/envs/mywork/lib/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
    await waiter
  File "/home/johnxiong/anaconda3/envs/mywork/lib/python3.8/asyncio/selector_events.py", line 848, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer

```

**Comment by aaugustin** [comment]
https://websockets.readthedocs.io/en/stable/contributing.html#bitcoin-users
