### ISSUE TITLE
"TimeoutError: [Errno 60] Operation timed out" from client

### ISSUE THREAD

**Issue by v-yunbin** [aaugustin/websockets#1019]
I start server with websockets in local network，and start a client in local network，all is normal.
when i start a client in outside network(the outside network had been maped to localnetwork, it means that the outside network can handshake successsfully with websockets in local network)，client always throw errors about overtime：
The server offten get three follows errors:
**error1:**
```
Error in connection handler
Traceback (most recent call last):
  File "/home/zyb/miniconda3/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 750, in transfer_data
    message = await self.read_message()
  File "/home/zyb/miniconda3/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 819, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/zyb/miniconda3/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 895, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/zyb/miniconda3/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 971, in read_frame
    frame = await Frame.read(
  File "/home/zyb/miniconda3/lib/python3.8/site-packages/websockets/legacy/framing.py", line 85, in read
    data = await reader(length)
  File "/home/zyb/miniconda3/lib/python3.8/asyncio/streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "/home/zyb/miniconda3/lib/python3.8/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zyb/miniconda3/lib/python3.8/site-packages/websockets/legacy/server.py", line 293, in handler
    await self.ws_handler(self, path)
  File "asr_server4_short_connect.py", line 64, in recognize
    message = await websocket.recv()
  File "/home/zyb/miniconda3/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 421, in recv
    await self.ensure_open()
  File "/home/zyb/miniconda3/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 735, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
Error in connection handler
Traceback (most recent call last):
  File "/home/zyb/miniconda3/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 750, in transfer_data
    message = await self.read_message()
  File "/home/zyb/miniconda3/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 819, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/zyb/miniconda3/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 895, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/zyb/miniconda3/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 971, in read_frame
    frame = await Frame.read(
  File "/home/zyb/miniconda3/lib/python3.8/site-packages/websockets/legacy/framing.py", line 85, in read
    data = await reader(length)
  File "/home/zyb/miniconda3/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 49138 bytes read on a total of 410180 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zyb/miniconda3/lib/python3.8/site-packages/websockets/legacy/server.py", line 293, in handler
    await self.ws_handler(self, path)
  File "asr_server4_short_connect.py", line 64, in recognize
    message = await websocket.recv()
  File "/home/zyb/miniconda3/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 421, in recv
    await self.ensure_open()
  File "/home/zyb/miniconda3/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 726, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```
**error2:**
```
Error in connection handler
Traceback (most recent call last):
  File "/home/zyb/miniconda3/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 750, in transfer_data
    message = await self.read_message()
  File "/home/zyb/miniconda3/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 819, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/zyb/miniconda3/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 895, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/zyb/miniconda3/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 971, in read_frame
    frame = await Frame.read(
  File "/home/zyb/miniconda3/lib/python3.8/site-packages/websockets/legacy/framing.py", line 55, in read
    data = await reader(2)
  File "/home/zyb/miniconda3/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zyb/miniconda3/lib/python3.8/site-packages/websockets/legacy/server.py", line 293, in handler
    await self.ws_handler(self, path)
  File "asr_server4_short_connect.py", line 64, in recognize
    message = await websocket.recv()
  File "/home/zyb/miniconda3/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 421, in recv
    await self.ensure_open()
  File "/home/zyb/miniconda3/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 726, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```
**error3:**
```
Error in connection handler
Traceback (most recent call last):
  File "/home/zyb/miniconda3/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 750, in transfer_data
    message = await self.read_message()
  File "/home/zyb/miniconda3/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 819, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/zyb/miniconda3/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 895, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/zyb/miniconda3/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 971, in read_frame
    frame = await Frame.read(
  File "/home/zyb/miniconda3/lib/python3.8/site-packages/websockets/legacy/framing.py", line 55, in read
    data = await reader(2)
  File "/home/zyb/miniconda3/lib/python3.8/asyncio/streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "/home/zyb/miniconda3/lib/python3.8/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
  File "/home/zyb/miniconda3/lib/python3.8/asyncio/selector_events.py", line 846, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zyb/miniconda3/lib/python3.8/site-packages/websockets/legacy/server.py", line 293, in handler
    await self.ws_handler(self, path)
  File "asr_server4_short_connect_except.py", line 64, in recognize
    message = await websocket.recv()
  File "/home/zyb/miniconda3/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 421, in recv
    await self.ensure_open()
  File "/home/zyb/miniconda3/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 726, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

The client often get one follows error:
```
Traceback (most recent call last):
  File "/Users/zhangyunbin/miniconda3/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 750, in transfer_data
    message = await self.read_message()
  File "/Users/zhangyunbin/miniconda3/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 819, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/zhangyunbin/miniconda3/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 895, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/zhangyunbin/miniconda3/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 971, in read_frame
    frame = await Frame.read(
  File "/Users/zhangyunbin/miniconda3/lib/python3.8/site-packages/websockets/legacy/framing.py", line 55, in read
    data = await reader(2)
  File "/Users/zhangyunbin/miniconda3/lib/python3.8/asyncio/streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "/Users/zhangyunbin/miniconda3/lib/python3.8/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
  File "/Users/zhangyunbin/miniconda3/lib/python3.8/asyncio/selector_events.py", line 846, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 60] Operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/zhangyunbin/Downloads/vtt.py", line 28, in <module>
    asyncio.get_event_loop().run_until_complete(request_api('wss://asr-edc.gwm.cn'))
  File "/Users/zhangyunbin/miniconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/zhangyunbin/Downloads/vtt.py", line 21, in request_api
    res = await websocket.recv()
  File "/Users/zhangyunbin/miniconda3/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 421, in recv
    await self.ensure_open()
  File "/Users/zhangyunbin/miniconda3/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 726, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

**Comment by v-yunbin** [comment]
Is this project maintained?

**Comment by aaugustin** [comment]
1. Your question is answered here: https://websockets.readthedocs.io/en/stable/faq.html#what-does-connectionclosederror-code-1006-mean
2. Escalating from "asking a question" to "is this project maintained" within less than 24h is completely inappropriate when there's no business relationship between us and when you can easily check the commit history to see that the project is maintained. You're welcome to contact me at aymeric.augustin AT fractalideas.com if you'd like to pay for a support contract with a guaranteed response time.

**Comment by v-yunbin** [comment]
So scared！！！

**Comment by lgrahl** [comment]
You got an appropriate and in no way offending answer. Please, try not to embarrass yourself with toxic behaviour.

**Comment by v-yunbin** [comment]
toxic behaviour not for me.

**Comment by v-yunbin** [comment]
I've never heard that an open source project needs to pay

**Comment by aaugustin** [comment]
I feel like the discussion isn't helping improve websockets, especially since @v-yunbin removed their comments, so I'm going to lock it.
