### ISSUE TITLE
closing handshake failed Traceback (most recent call last):   File "/home/cimi/.local/lib/python3.10/site-packages/websockets/legacy/server.py", line 239, in handler     await self.close()   File "/home/cimi/.local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 779, in close     await asyncio.shield(self.close_connection_task)   File "/home/cimi/.local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1309, in close_connection     self.transport.write_eof()   File "/usr/lib/python3.10/asyncio/selector_events.py", line 972, in write_eof     self._sock.shutdown(socket.SHUT_WR) OSError: [Errno 107] Transport endpoint is not connected

### ISSUE THREAD

**Issue by aaabbbcccabc** [aaugustin/websockets#1104]
closing handshake failed
Traceback (most recent call last):
  File "/home/cimi/.local/lib/python3.10/site-packages/websockets/legacy/server.py", line 239, in handler
    await self.close()
  File "/home/cimi/.local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 779, in close
    await asyncio.shield(self.close_connection_task)
  File "/home/cimi/.local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1309, in close_connection
    self.transport.write_eof()
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 972, in write_eof
    self._sock.shutdown(socket.SHUT_WR)
OSError: [Errno 107] Transport endpoint is not connected

**Comment by lgrahl** [comment]
This isn't a place to dump your exceptions...
