### ISSUE TITLE
won't raise a ConnectionClosedError when the connection is closed by force

### ISSUE THREAD

**Issue by zzxjl1** [aaugustin/websockets#1108]
async for message in websocket:
    await process(message)

It won't raise a ConnectionClosedError when the connection is closed by force.

**Comment by aaugustin** [comment]
I'm not sure what you mean when you write "closed by force".

A WebSocket can be closed:

- with a closing handshake and a close code of 1000 (OK) or 1001 (going away) => no exception because these are normal close codes — I think this is what you're seeing here
- with a closing handshake and another close codes => ConnectionClosed exception because these are likely errors / problems
- without a closing handshake (e.g. network connection dropped) => ConnectionClosed exceptions

**Comment by zzxjl1** [comment]
without a closing handshake (e.g. network connection dropped) => ConnectionClosed exceptions

**Comment by zzxjl1** [comment]
kill -9 won't raise any exception

**Comment by aaugustin** [comment]
If you `kill -9` the Python process, it's terminated instantly, so the Python interpreter doesn't get a chance to raise an exception.

**Comment by aaugustin** [comment]
I connected a client and a server as follows and tried killing them with `kill -9`:

```
$ python example/quickstart/server.py
```

```
$ python example/quickstart/client.py
```

Killing the client produces this message on the server (which is reading at the time of the crash):

```
Traceback (most recent call last):
  File "/Users/myk/dev/websockets/src/websockets/legacy/protocol.py", line 944, in transfer_data
    message = await self.read_message()
  File "/Users/myk/dev/websockets/src/websockets/legacy/protocol.py", line 1013, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/myk/dev/websockets/src/websockets/legacy/protocol.py", line 1088, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/myk/dev/websockets/src/websockets/legacy/protocol.py", line 1143, in read_frame
    frame = await Frame.read(
  File "/Users/myk/dev/websockets/src/websockets/legacy/framing.py", line 70, in read
    data = await reader(2)
  File "/Users/myk/.pyenv/versions/3.10.0/lib/python3.10/asyncio/streams.py", line 708, in readexactly
    await self._wait_for_data('readexactly')
  File "/Users/myk/.pyenv/versions/3.10.0/lib/python3.10/asyncio/streams.py", line 502, in _wait_for_data
    await self._waiter
  File "/Users/myk/.pyenv/versions/3.10.0/lib/python3.10/asyncio/selector_events.py", line 856, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 54] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/myk/dev/websockets/src/websockets/legacy/server.py", line 232, in handler
    await self.ws_handler(self)
  File "/Users/myk/dev/websockets/example/quickstart/server.py", line 7, in hello
    name = await websocket.recv()
  File "/Users/myk/dev/websockets/src/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/Users/myk/dev/websockets/src/websockets/legacy/protocol.py", line 920, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
```

Killing the server produces this message on the client (after pressing enter, so it's attempting to write):

```
Traceback (most recent call last):
  File "/Users/myk/dev/websockets/src/websockets/legacy/protocol.py", line 1170, in drain
    await self._drain()
  File "/Users/myk/dev/websockets/src/websockets/legacy/protocol.py", line 318, in _drain
    raise exc
  File "/Users/myk/dev/websockets/src/websockets/legacy/protocol.py", line 944, in transfer_data
    message = await self.read_message()
  File "/Users/myk/dev/websockets/src/websockets/legacy/protocol.py", line 1013, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/myk/dev/websockets/src/websockets/legacy/protocol.py", line 1088, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/myk/dev/websockets/src/websockets/legacy/protocol.py", line 1143, in read_frame
    frame = await Frame.read(
  File "/Users/myk/dev/websockets/src/websockets/legacy/framing.py", line 70, in read
    data = await reader(2)
  File "/Users/myk/.pyenv/versions/3.10.0/lib/python3.10/asyncio/streams.py", line 697, in readexactly
    raise self._exception
  File "/Users/myk/.pyenv/versions/3.10.0/lib/python3.10/asyncio/selector_events.py", line 918, in write
    n = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/myk/dev/websockets/example/quickstart/client.py", line 18, in <module>
    asyncio.run(hello())
  File "/Users/myk/.pyenv/versions/3.10.0/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/myk/.pyenv/versions/3.10.0/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Users/myk/dev/websockets/example/quickstart/client.py", line 14, in hello
    greeting = await websocket.recv()
  File "/Users/myk/dev/websockets/src/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/Users/myk/dev/websockets/src/websockets/legacy/protocol.py", line 920, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
```

In both cases, the exception is reported.

You will need to provide more information for me to understand the problem that you are facing.
