### ISSUE TITLE
OSError: [Errno 107] Transport endpoint is not connected

### ISSUE THREAD

**Issue by th3hamm0r** [aaugustin/websockets#1117]
We've upgraded a websocket-server-project with many active WS-connections from 7.0 to 10.1, and we now sometimes find this error in our logs. There seem to be two possible stack paths:

One where our code `await`s for `recv()`:

    2022-01-10 16:00:06 ERROR:websockets.server: connection handler failed (server.py
    :233)
    Traceback (most recent call last):
      File "/***/.venv/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
        await self.ws_handler(self)
      File "/***/.venv/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
        return await cast(
      File "/***/websocket.py", line 447, in _handler
        await connection_handler.run()
      File "/***/websocket.py", line 98, in run
        first_client_message = await self.websocket.recv()
      File "/***/.venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
        await self.ensure_open()
      File "/***/.venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 928, in ensure_open
        await asyncio.shield(self.close_connection_task)
      File "/***/.venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 1309, in close_connection
        self.transport.write_eof()
      File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 964, in write_eof
        self._sock.shutdown(socket.SHUT_WR)
    OSError: [Errno 107] Transport endpoint is not connected

In the above case it happens very early, as we're waiting for the first message from the client.

And another one which isn't touching our code:

    2022-01-10 15:47:35 ERROR:websockets.server: closing handshake failed (server.py:243)
    Traceback (most recent call last):
      File "/***/.venv/lib/python3.8/site-packages/websockets/legacy/server.py", line 239, in handler
        await self.close()
      File "/***/.venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 779, in close
        await asyncio.shield(self.close_connection_task)
      File "/***/.venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 1309, in close_connection
        self.transport.write_eof()
      File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 964, in write_eof
        self._sock.shutdown(socket.SHUT_WR)
    OSError: [Errno 107] Transport endpoint is not connected

I've only found #1104 which looks similar to the seconds stack trace, except we're using python 3.8 instead of python 3.10.

**Comment by aaugustin** [comment]
I believe #1086 should fix this.

**Comment by th3hamm0r** [comment]
Yes, that seems to fix it.
I will try to upgrade python and look if it still occurs.

**Comment by aaugustin** [comment]
Weird. Do you have logs of the issue at the DEBUG level?

**Comment by th3hamm0r** [comment]
Not right now, but I will enable it tomorrow and post the results then. Thanks!

**Comment by th3hamm0r** [comment]
I've turned on debug logging and for now only the second stack trace occured. There is so much logging, I hope I've extracted enough, but of course, if it helps, I can extract more information:

    ...
    2022-01-13 10:51:25 DEBUG:websockets.server: < CLOSE 1005 (no status code [internal]) [0 bytes] (protocol.py:1151)
    2022-01-13 10:51:25 DEBUG:websockets.server: = connection is CLOSING (protocol.py:1206)
    2022-01-13 10:51:25 DEBUG:websockets.server: > CLOSE 1005 (no status code [internal]) [0 bytes] (protocol.py:1157)
    2022-01-13 10:51:25 DEBUG:websockets.server: x half-closing TCP connection (protocol.py:1308)
    2022-01-13 10:51:25 DEBUG:websockets.server: = connection is CLOSED (protocol.py:1481)
    2022-01-13 10:51:25 INFO:websockets.server: connection closed (server.py:259)
    2022-01-13 10:51:25 DEBUG:websockets.server: < PONG eb 20 04 a1 [binary, 4 bytes] (protocol.py:1151)
    2022-01-13 10:51:25 DEBUG:websockets.server: % received keepalive pong (protocol.py:1254)
    2022-01-13 10:51:25 DEBUG:websockets.server: % sending keepalive ping (protocol.py:1244)
    2022-01-13 10:51:25 DEBUG:websockets.server: > PING '\x17\x10[T' [text, 4 bytes] (protocol.py:1157)
    2022-01-13 10:51:25 DEBUG:websockets.server: % sending keepalive ping (protocol.py:1244)
    2022-01-13 10:51:25 DEBUG:websockets.server: > PING e5 cc 73 53 [binary, 4 bytes] (protocol.py:1157)
    2022-01-13 10:51:25 DEBUG:websockets.server: < TEXT '***' [226 bytes] (protocol.py:1151)
    2022-01-13 10:51:25 DEBUG:websockets.server: < CLOSE 1005 (no status code [internal]) [0 bytes] (protocol.py:1151)
    2022-01-13 10:51:25 DEBUG:websockets.server: = connection is CLOSING (protocol.py:1206)
    2022-01-13 10:51:25 DEBUG:websockets.server: > CLOSE 1005 (no status code [internal]) [0 bytes] (protocol.py:1157)
    2022-01-13 10:51:25 DEBUG:websockets.server: x half-closing TCP connection (protocol.py:1308)
    2022-01-13 10:51:25 DEBUG:websockets.server: x closing TCP connection (protocol.py:1336)
    2022-01-13 10:51:25 DEBUG:websockets.server: = connection is CLOSED (protocol.py:1481)
    2022-01-13 10:51:25 DEBUG:websockets.server: % sending keepalive ping (protocol.py:1244)
    2022-01-13 10:51:25 DEBUG:websockets.server: > PING 98 c6 aa 05 [binary, 4 bytes] (protocol.py:1157)
    2022-01-13 10:51:25 ERROR:websockets.server: closing handshake failed (server.py:243)
    Traceback (most recent call last):
      File "/***/.venv/lib/python3.8/site-packages/websockets/legacy/server.py", line 239, in handler
        await self.close()
      File "/***/.venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 779, in close
        await asyncio.shield(self.close_connection_task)
      File "/***/.venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 1309, in close_connection
        self.transport.write_eof()
      File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 964, in write_eof
        self._sock.shutdown(socket.SHUT_WR)
    OSError: [Errno 107] Transport endpoint is not connected
    2022-01-13 10:51:25 INFO:websockets.server: connection closed (server.py:259)
    2022-01-13 10:51:25 DEBUG:websockets.server: < CLOSE 1005 (no status code [internal]) [0 bytes] (protocol.py:1151)
    2022-01-13 10:51:25 DEBUG:websockets.server: = connection is CLOSING (protocol.py:1206)
    2022-01-13 10:51:25 DEBUG:websockets.server: > CLOSE 1005 (no status code [internal]) [0 bytes] (protocol.py:1157)
    2022-01-13 10:51:25 DEBUG:websockets.server: = connection is CONNECTING (protocol.py:252)
    2022-01-13 10:51:25 DEBUG:websockets.server: x closing TCP connection (protocol.py:1336)
    2022-01-13 10:51:25 DEBUG:websockets.server: = connection is CLOSED (protocol.py:1481)
    2022-01-13 10:51:25 DEBUG:websockets.server: < GET /*** HTTP/1.1 (server.py:281)
    2022-01-13 10:51:25 DEBUG:websockets.server: < Upgrade: websocket (server.py:283)
    2022-01-13 10:51:25 DEBUG:websockets.server: < Connection: upgrade (server.py:283)
    ...

Another case:

    ...
    2022-01-13 10:51:27 DEBUG:websockets.server: > TEXT '***' [142 bytes] (protocol.py:1157)
    2022-01-13 10:51:27 DEBUG:websockets.server: > TEXT '***' [60 bytes] (protocol.py:1157)
    2022-01-13 10:51:27 DEBUG:websockets.server: < CLOSE 1005 (no status code [internal]) [0 bytes] (protocol.py:1151)
    2022-01-13 10:51:27 DEBUG:websockets.server: = connection is CLOSING (protocol.py:1206)
    2022-01-13 10:51:27 DEBUG:websockets.server: > CLOSE 1005 (no status code [internal]) [0 bytes] (protocol.py:1157)
    2022-01-13 10:51:27 DEBUG:websockets.server: x half-closing TCP connection (protocol.py:1308)
    2022-01-13 10:51:27 DEBUG:websockets.server: x closing TCP connection (protocol.py:1336)
    2022-01-13 10:51:27 DEBUG:websockets.server: = connection is CLOSED (protocol.py:1481)
    2022-01-13 10:51:27 ERROR:websockets.server: closing handshake failed (server.py:243)
    Traceback (most recent call last):
      File "/***/.venv/lib/python3.8/site-packages/websockets/legacy/server.py", line 239, in handler
        await self.close()
      File "/h***/.venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 779, in close
        await asyncio.shield(self.close_connection_task)
      File "/***/.venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 1309, in close_connection
        self.transport.write_eof()
      File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 964, in write_eof
        self._sock.shutdown(socket.SHUT_WR)
    OSError: [Errno 107] Transport endpoint is not connected
    2022-01-13 10:51:27 INFO:websockets.server: connection closed (server.py:259)
    2022-01-13 10:51:27 DEBUG:websockets.server: = connection is CONNECTING (protocol.py:252)
    2022-01-13 10:51:27 DEBUG:websockets.server: < TEXT '***' [306 bytes] (protocol.py:1151)
    ...

**Comment by Klavionik** [comment]
Same issue here, but in my case, it seems to happen only if the client disconnects with 1001, not 1005. Not every time, but pretty often. Python 3.10, Uvicorn 0.15.0, websockets 10.1.

The debug log looks like this:
```
INFO:     connection open
DEBUG:    = connection is OPEN
DEBUG:    < CLOSE 1001 (going away) [2 bytes]
DEBUG:    = connection is CLOSING
DEBUG:    > CLOSE 1001 (going away) [2 bytes]
DEBUG:    x half-closing TCP connection
DEBUG:    x closing TCP connection
DEBUG:    = connection is CLOSED
ERROR:    closing handshake failed
Traceback (most recent call last):
  File "/home/jediroman/Desktop/BlackSheep/venv/lib/python3.10/site-packages/websockets/legacy/server.py", line 239, in handler
    await self.close()
  File "/home/jediroman/Desktop/BlackSheep/venv/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 779, in close
    await asyncio.shield(self.close_connection_task)
  File "/home/jediroman/Desktop/BlackSheep/venv/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1309, in close_connection
    self.transport.write_eof()
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 972, in write_eof
    self._sock.shutdown(socket.SHUT_WR)
OSError: [Errno 107] Transport endpoint is not connected
INFO:     connection closed
```
