### ISSUE TITLE
'websockets' has no attribute 'client'

### ISSUE THREAD

**Issue by aPatinthehat** [aaugustin/websockets#1120]
I am trying to perform some webscraping using [this ](https://github.com/jhnwr/requests-html-render-yt/blob/master/requests-render.py) script, and the follow "AttributeError: module 'websockets' has no attribute 'client'" error occurs when using render(). 

websocket-version: 1.2.3

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kali/.local/lib/python3.9/site-packages/requests_html.py", line 586, in render
    self.browser = self.session.browser  # Automatically create a event loop and browser
  File "/home/kali/.local/lib/python3.9/site-packages/requests_html.py", line 730, in browser
    self._browser = self.loop.run_until_complete(super().browser)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/kali/.local/lib/python3.9/site-packages/requests_html.py", line 714, in browser
    self._browser = await pyppeteer.launch(ignoreHTTPSErrors=not(self.verify), headless=True, args=self.__browser_args)
  File "/usr/lib/python3/dist-packages/pyppeteer/launcher.py", line 306, in launch
    return await Launcher(options, **kwargs).launch()
  File "/usr/lib/python3/dist-packages/pyppeteer/launcher.py", line 169, in launch
    self.connection = Connection(self.browserWSEndpoint, self._loop, connectionDelay, )
  File "/usr/lib/python3/dist-packages/pyppeteer/connection.py", line 43, in __init__
    self._ws = websockets.client.connect(
  File "/usr/lib/python3/dist-packages/websockets/imports.py", line 96, in __getattr__
    raise AttributeError(f"module {package!r} has no attribute {name!r}")
AttributeError: module 'websockets' has no attribute 'client'
```

**Comment by aaugustin** [comment]
Did you `import websockets.client`?

**Comment by aaugustin** [comment]
Based on the current implementation of https://github.com/pyppeteer/pyppeteer/blob/1595c9f617b9db56edf9ec9e12ede85f95e4910e/pyppeteer/connection.py it looks like the bug is fixed over there. 

However, it still contains `import websockets`, supporting my theory that an incorrect import caused the problem. It should be `import websockets.client`.

In Python, `import a` doesn't guarantee that submodule `a.b` is available. It depends if importing `a` has a side-effect of importing `a.b`.
