### ISSUE TITLE
Client throws exception that does not inherit from `WebSocketException`

### ISSUE THREAD

**Issue by janheindejong** [aaugustin/websockets#1139]
Ok - maybe I'm completely missing something in the docs, but I ran across something rather funny. 

In some cases, the websocket client throws an exception that does not inherit from `WebSocketException`. I traced it to [this piece of code](https://github.com/aaugustin/websockets/blob/c60df611023ac47345d9201b0a4785c4d8dbdbd9/src/websockets/legacy/client.py#L670-L673).

In researching this I noticed that by default, the `websockets.connect` function returns an instance of `websockets.legacy.client.WebSocketProtocol`. Is the legacy client indeed the default behavior? 

Traceback: 

``` 
future: <Task finished name='Task-3' coro=<StreamPublisher.run() done, defined at /opt/pysetup/.venv/lib/python3.9/site-packages/allseas_twitch/publisher/_stream.py:54> exception=TimeoutError()>
Traceback (most recent call last):

  File "/opt/pysetup/.venv/lib/python3.9/site-packages/websockets/legacy/client.py", line 658, in __await_impl__
    await protocol.handshake(
          │        └ <function WebSocketClientProtocol.handshake at 0x7f7769dba5e0>
          └ <websockets.legacy.client.WebSocketClientProtocol object at 0x7f7769fdd040>
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/websockets/legacy/client.py", line 328, in handshake
    raise InvalidStatusCode(status_code, response_headers)
          │                 │            └ Headers([('Content-Type', 'text/html'), ('Server', 'Microsoft-IIS/10.0'), ('X-Powered-By', 'ASP.NET'), ('Date', 'Sun, 06 Mar ...
          │                 └ 503
          └ <class 'websockets.exceptions.InvalidStatusCode'>

websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 503


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/opt/pysetup/.venv/lib/python3.9/site-packages/websockets/legacy/client.py", line 672, in __await_impl__
    await protocol.wait_closed()
          │        └ <function WebSocketCommonProtocol.wait_closed at 0x7f778992e310>
          └ <websockets.legacy.client.WebSocketClientProtocol object at 0x7f7769fdd040>

asyncio.exceptions.CancelledError


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           │   └ <method 'result' of '_asyncio.Task' objects>
           └ <Task cancelled name='Task-90' coro=<Connect.__await_impl__() done, defined at /opt/pysetup/.venv/lib/python3.9/site-packages...

asyncio.exceptions.CancelledError
```

**Comment by aaugustin** [comment]
Something, most likely in the `allseas_twitch`, calls `websockets.connect`, then cancels it due to reaching a timeout. In this case, `websockets.connect` may do some cleanup and must re-raise `CancelledError`, else it would prevent the cancellation. This behavior is mandated by asyncio, at a lower layer than websockets.

There are other cases where you may get exception that don't inherit `WebSocketException`. If your Python process ran out of memory, you could get `MemoryError`. (Both `CancelledError` and `MemoryError` inherit `BaseException`, not `Exception`, which makes this analogy especially relevant.)

And yes, the non-legacy implementation only exists in my head at this point; the legacy implementation is stable and supported.

**Comment by aaugustin** [comment]
Reopening to double check if this is the effect of default timeout of `connect`

**Comment by aaugustin** [comment]
I believe this traceback shows a timeout happening after hitting a HTTP 503 error, possibly because the server keeps the connection alive instead of closing it after the handshake fails, so you hit the "open timeout" before the "close timeout".

I suspect the trackback is truncated; you should have a `TimeoutError` after that, which would be more readable.

Typical traceback:

```
Traceback (most recent call last):
  File "/Users/myk/dev/websockets/src/websockets/legacy/client.py", line 658, in __await_impl__
    await protocol.handshake(
  File "/Users/myk/dev/websockets/src/websockets/legacy/client.py", line 322, in handshake
    status_code, response_headers = await self.read_http_response()
  File "/Users/myk/dev/websockets/src/websockets/legacy/client.py", line 135, in read_http_response
    status_code, reason, headers = await read_response(self.reader)
  File "/Users/myk/dev/websockets/src/websockets/legacy/http.py", line 120, in read_response
    status_line = await read_line(stream)
  File "/Users/myk/dev/websockets/src/websockets/legacy/http.py", line 194, in read_line
    line = await stream.readline()
  File "/Users/myk/.pyenv/versions/3.10.0/lib/python3.10/asyncio/streams.py", line 525, in readline
    line = await self.readuntil(sep)
  File "/Users/myk/.pyenv/versions/3.10.0/lib/python3.10/asyncio/streams.py", line 617, in readuntil
    await self._wait_for_data('readuntil')
  File "/Users/myk/.pyenv/versions/3.10.0/lib/python3.10/asyncio/streams.py", line 502, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/myk/.pyenv/versions/3.10.0/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/myk/dev/websockets/example/hello.py", line 11, in <module>
    asyncio.run(hello())
  File "/Users/myk/.pyenv/versions/3.10.0/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/myk/.pyenv/versions/3.10.0/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Users/myk/dev/websockets/example/hello.py", line 7, in hello
    async with websockets.connect("ws://localhost:8765", open_timeout=0.5) as websocket:
  File "/Users/myk/dev/websockets/src/websockets/legacy/client.py", line 633, in __aenter__
    return await self
  File "/Users/myk/dev/websockets/src/websockets/legacy/client.py", line 650, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/Users/myk/.pyenv/versions/3.10.0/lib/python3.10/asyncio/tasks.py", line 460, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
```
