### ISSUE TITLE
testsuite failures with Python 3.5.2

### ISSUE THREAD

**Issue by doko42** [aaugustin/websockets#123]
Both 3.0 and 3.1 fail four tests when run with Python 3.5.2:
# 
## FAIL: test_local_address (websockets.test_protocol.ClientTests)

Traceback (most recent call last):
  File "/home/packages/tmp/python-websockets-3.1/.pybuild/pythonX.Y_3.5/build/websockets/test_protocol.py", line 261, in test_local_addre
ss
    get_extra_info.assert_called_once_with('sockname', None)
  File "/usr/lib/python3.5/unittest/mock.py", line 802, in assert_called_once_with
    raise AssertionError(msg)
AssertionError: Expected 'get_extra_info' to be called once. Called 2 times.
# 
## FAIL: test_remote_address (websockets.test_protocol.ClientTests)

Traceback (most recent call last):
  File "/home/packages/tmp/python-websockets-3.1/.pybuild/pythonX.Y_3.5/build/websockets/test_protocol.py", line 271, in test_remote_address
    get_extra_info.assert_called_once_with('peername', None)
  File "/usr/lib/python3.5/unittest/mock.py", line 802, in assert_called_once_with
    raise AssertionError(msg)
AssertionError: Expected 'get_extra_info' to be called once. Called 2 times.
# 
## FAIL: test_local_address (websockets.test_protocol.ServerTests)

Traceback (most recent call last):
  File "/home/packages/tmp/python-websockets-3.1/.pybuild/pythonX.Y_3.5/build/websockets/test_protocol.py", line 261, in test_local_address
    get_extra_info.assert_called_once_with('sockname', None)
  File "/usr/lib/python3.5/unittest/mock.py", line 802, in assert_called_once_with
    raise AssertionError(msg)
AssertionError: Expected 'get_extra_info' to be called once. Called 2 times.
# 
## FAIL: test_remote_address (websockets.test_protocol.ServerTests)

Traceback (most recent call last):
  File "/home/packages/tmp/python-websockets-3.1/.pybuild/pythonX.Y_3.5/build/websockets/test_protocol.py", line 271, in test_remote_address
    get_extra_info.assert_called_once_with('peername', None)
  File "/usr/lib/python3.5/unittest/mock.py", line 802, in assert_called_once_with
    raise AssertionError(msg)
AssertionError: Expected 'get_extra_info' to be called once. Called 2 times.

---

Ran 231 tests in 0.899s

FAILED (failures=4, skipped=27)

**Comment by aaugustin** [comment]
Thanks for the report. I'll look into fixing this.

It doesn't look like this will prevent the library from operating properly on Python 3.5.2. I think it's just a problem with a test assertion that fails due to implementation changes in Python.

**Comment by aaugustin** [comment]
I fixed this in 6b1db40e93fbedd8a7c4134bb0c82d29e651fcbf.
