### ISSUE TITLE
WebSocketCommonProtocol.close_connection exception

### ISSUE THREAD

**Issue by alamathe1** [aaugustin/websockets#1235]
Websocket throwing following error during an intentional keyboard interrupt on client. The use case is to keep the client connection to server open, continuously for receiving message from the server until the user exits out using a keyboard interrupt i.e. CMD+C:

```
closing TCP connection
2022-09-26 15:43:08,538:[websockets.client]:[DEBUG]:: x closing TCP connection
Exception ignored in: <coroutine object WebSocketCommonProtocol.close_connection at 0x108f152c0>
Traceback (most recent call last):
  File "<>/.venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 1326, in close_connection
    await self.close_transport()
  File "<>/.venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 1342, in close_transport
    self.transport.close()
  File "<>/build/python3.8/lib/python3.8/asyncio/selector_events.py", line 692, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "<>/build/python3.8/lib/python3.8/asyncio/base_events.py", line 719, in call_soon
    self._check_closed()
  File "<>build/python3.8/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2022-09-26 15:43:08,542:[asyncio]:[ERROR]:: Task was destroyed but it is pending!
task: <Task pending name='Task-6' coro=<WebSocketCommonProtocol.close_connection() done, defined at <>/.venv/lib/python3.8/site-packages/websockets/legacy/protocol.py:1271> wait_for=<Task cancelled name='Task-4' coro=<WebSocketCommonProtocol.transfer_data() done, defined at <>/.venv/lib/python3.8/site-packages/websockets/legacy/protocol.py:935>>>

Process finished with exit code 0
```

Client code:
```
def main():

    event_loop = asyncio.events.new_event_loop()
    asyncio.events.set_event_loop(event_loop)

    event_loop.add_signal_handler(signal.SIGINT, my_handler)
    try:
        event_loop.run_until_complete(_connect_send_receive_until_complete(encoded_msg, receive, callback))
        event_loop.run_forever()
    except (asyncio.CancelledError, websockets.exceptions.ConnectionClosed) as error:
        print('Tasks has been canceled')
    finally:
        event_loop.close()

async def _connect_send_receive_until_complete(
        data: bytes, receive: bool, callback: typing.Optional[progress_callback] = None
) -> typing.Optional[typing.Tuple[str, object]]:
    connection = await connect(data, callback)
    while True:
        await receiveMessage(connection)

def my_handler():
    print('Stopping')
    for task in asyncio.Task.all_tasks():
        task.cancel()
```

Even though the web socket functions are wrapped in a try/except, the error is being propagated outside.

Server logs:
```
exception code = 1006 (connection closed abnormally [internal]), no reason
```

**Comment by aaugustin** [comment]
There are two problems here.

(1)

```
    for task in asyncio.Task.all_tasks():
        task.cancel()
```

is messing with internal state of websockets. 

(2)

You are closing the event loop before websockets is done.

----

Your program stucture is so weird that I'm not sure how to improve it without rewriting it entirely.

In short:

- run `_connect_send_receive_until_complete` in a task, say `main_task`
- when you get a signal, close the connection with `connection.close()`
- wait until the task is complete with `await main_task`
- only then you can close the event loop

**Comment by alamathe1** [comment]
@aaugustin Updated code below per your recommendation:

```

class WebSocketClient:
    _keepOpen: bool
    _websocket: websockets.WebSocketServerProtocol
    _event_loop: asyncio.AbstractEventLoop

    def __init__(self, keepOpen: bool):
        self._keepOpen = keepOpen

    def my_handler(self):
        self._websocket.close()

    async def run(self, data: bytes, receive: bool, callback: typing.Optional[progress_callback] = None
    ):

        # all the event loop magic goes here

        self._event_loop = asyncio.events.new_event_loop()
        asyncio.events.set_event_loop(self._event_loop)

        try:
            for sig in (signal.SIGINT, signal.SIGTERM):
                self._event_loop.add_signal_handler(sig, self.my_handler)
            send_receive_task = asyncio.create_task(self._connect_send_receive_until_complete(data, receive, callback))
            done, pending = await asyncio.wait(
                [send_receive_task],
                return_when=asyncio.FIRST_COMPLETED,
            )
            for task in pending:
                task.cancel()

        finally:
            self._event_loop.close()


    async def _connect_send_receive_until_complete(self,
            data: bytes, receive: bool, callback: typing.Optional[progress_callback] = None
    ) -> None:
            await self.connect()
            if self._websocket.open:
                await self.sendMessage(data, callback)
                if receive:
                    await self.receiveMessage()

    async def connect(self):
        uri: str = _get_uri()
        max_size: int = typing.cast(int, None)
        self._websocket = await websockets.connect(
            uri, max_size=max_size, ping_timeout=300, compression=None, ping_interval=None
        )

    async def sendMessage(self, data):
        await self._websocket.send(data)

    async def receiveMessage(self):
        while True:
            try:
                message = await self._websocket.recv()
            except Exception as e:
                break

def main():
      web_socket_client = WebSocketClient(True)
      web_socket_client.run(encoded_msg, receive, callback)
```

Following are logs received on client:

Received message from server: 
```
b'\xe0\x01\x00\xea\xee\x93\x81\x83\xde\x8f\x87\xbd\x84type\x87message\xde\xa1\x8a\x87Success\x8b\x8e\x95Deployment successful'

Process finished with exit code 137 (interrupted by signal 9: SIGKILL)
```

I am wondering why it does not enter my_handler() ?
