### ISSUE TITLE
Unable to build from sources in Win (Python 3.11)

### ISSUE THREAD

**Issue by dreo** [aaugustin/websockets#1250]
Hi,

there seems to be no wheels for the newly release Python 3.11 yet, and it seems it's not possible to build one in Win 10 - `pip install websockets` ends up with the following error:

```
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\ondre\AppData\Local\Temp\pip-install-9zcbd40o\websockets_0a8798084b5c45538f93d9f69fa08228\setup.py", line 33, in <module>
          setuptools.setup(
        File "x:\janoshik\venv\Lib\site-packages\setuptools\__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "X:\tools\python311\Lib\distutils\core.py", line 148, in setup
          dist.run_commands()
        File "X:\tools\python311\Lib\distutils\dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "X:\tools\python311\Lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "x:\janoshik\venv\Lib\site-packages\wheel\bdist_wheel.py", line 337, in run
          impl_tag, abi_tag, plat_tag = self.get_tag()
                                        ^^^^^^^^^^^^^^
        File "x:\janoshik\venv\Lib\site-packages\wheel\bdist_wheel.py", line 287, in get_tag
          assert tag in supported_tags, "would build wheel with unsupported tag {}".format(tag)
      AssertionError: would build wheel with unsupported tag ('cp311', 'cp311', 'win_amd64')
```

I'm not sure how to fix this, any clue?

**Comment by aaugustin** [comment]
`pip install websockets --no-binary=websockets`

**Comment by aaugustin** [comment]
There will be Python 3.11 wheels for the next release of websockets. I don't have an ETA for this; releases are infrequent.

**Comment by dreo** [comment]
Thanks, didn't know about `--no-binary`, good to know!
