### ISSUE TITLE
Exception behavior on close code 1005

### ISSUE THREAD

**Issue by LambdaP** [aaugustin/websockets#1260]
Hi. This might be a bit of a naïve question, in which case I apologize. I’m unfamiliar with most of the technologies at play here.

In short, running a dummy script in my browser that opens a websocket, sends a message, and then closes the connection using `close()`, I notice that my browser (actually, three different browsers) sends a close code 1005. This, in turn, is interpreted by my toy `websockets` server as an error, and a `ConnectionClosedError` exception is raised, which pollutes the execution log. That's unfortunate, because it greatly reduces the utility of the idiom

```python3
async def handler(websocket):
    async for message in websocket:
        print(message)
```

I’m not sure who’s at fault here. It’s pretty clear that the proximate cause of the problem is that receiving a 1005 close code is considered an error by the library. I don’t know why my browser is sending a 1005 close code rather than a 1000 close code, but a cursory Internet search seems to show that some people think 1005 is an acceptable code when sending an empty close request. I have no opinion on the matter.

What’s going on here, and is there something to be done?

Here’s the front-end code generating the behavior.

```html
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Websocket example</title>
	</head>
	<body>
		<script>
			const ws = new WebSocket('ws://localhost:8987');
			ws.onopen = function () {
				ws.send('hello');
				setTimeout(function () {
					ws.send('bye');
					ws.close();
				}, 1000);
				console.log('connection closed');
			}
		</script>
	</body>
</html>
```

and here’s the server

```python3
#!/usr/bin/env python3

import asyncio
import websockets
import logging

logger = logging.getLogger("websockets")
logger.setLevel(logging.DEBUG)
logger.addHandler(logging.StreamHandler())


async def handler(websocket):
    async for message in websocket:
        print(message)


async def main():
    async with websockets.serve(handler, "", 8987):
        await asyncio.Future()


if __name__ == "__main__":
    asyncio.run(main())
```

and here’s the output of the server when there’s a connection (from Firefox, but the behavior is similar when using Safari or Chrome)

```
= connection is CONNECTING
< GET / HTTP/1.1
< Host: localhost:8987
< User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:106.0) Gecko/20100101 Firefox/106.0
< Accept: */*
< Accept-Language: en-US,en;q=0.5
< Accept-Encoding: gzip, deflate, br
< Sec-WebSocket-Version: 13
< Origin: http://localhost:8000
< Sec-WebSocket-Extensions: permessage-deflate
< Sec-WebSocket-Key: iJP3akNzm+oCIXZHkGxeRQ==
< DNT: 1
< Connection: keep-alive, Upgrade
< Cookie: CSRF-Token-S7K6Q=WVZ7HRAUaLgMh99k79nEry6gMsHJQxEx; sessionid-S7K6Q=NhrssWixJ6fLJ4u2wJCrx3EkNbxC5xhU; org.cups.sid=6958f9eca80c2c0e1a51541fcfdfcbe2
< Sec-Fetch-Dest: websocket
< Sec-Fetch-Mode: websocket
< Sec-Fetch-Site: same-site
< Pragma: no-cache
< Cache-Control: no-cache
< Upgrade: websocket
> HTTP/1.1 101 Switching Protocols
> Upgrade: websocket
> Connection: Upgrade
> Sec-WebSocket-Accept: TURb1I47l6rKV+cEMR3dDAE3mR8=
> Sec-WebSocket-Extensions: permessage-deflate; server_max_window_bits=12
> Date: Mon, 07 Nov 2022 11:20:54 GMT
> Server: Python/3.9 websockets/10.4
connection open
= connection is OPEN
< TEXT 'hello' [5 bytes]
hello
< TEXT 'bye' [3 bytes]
< CLOSE 1005 (no status code [internal]) [0 bytes]
= connection is CLOSING
> CLOSE 1005 (no status code [internal]) [0 bytes]
x half-closing TCP connection
bye
= connection is CLOSED
connection handler failed
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/Users/p/work/precog/dom_playground/websockets/ws_server/ws_server.py", line 13, in handler
    async for message in websocket:
  File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 497, in __aiter__
    yield await self.recv()
  File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 944, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: received 1005 (no status code [internal]); then sent 1005 (no status code [internal])
connection closed
```

note that if I replace `ws.close()` with `ws.close(1000)` in the script things are fine:

```
= connection is CONNECTING
< GET / HTTP/1.1
< Host: localhost:8987
< User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:106.0) Gecko/20100101 Firefox/106.0
< Accept: */*
< Accept-Language: en-US,en;q=0.5
< Accept-Encoding: gzip, deflate, br
< Sec-WebSocket-Version: 13
< Origin: http://localhost:8000
< Sec-WebSocket-Extensions: permessage-deflate
< Sec-WebSocket-Key: Hr2migHv0NF+3m6bIP6leg==
< DNT: 1
< Connection: keep-alive, Upgrade
< Cookie: CSRF-Token-S7K6Q=WVZ7HRAUaLgMh99k79nEry6gMsHJQxEx; sessionid-S7K6Q=NhrssWixJ6fLJ4u2wJCrx3EkNbxC5xhU; org.cups.sid=6958f9eca80c2c0e1a51541fcfdfcbe2
< Sec-Fetch-Dest: websocket
< Sec-Fetch-Mode: websocket
< Sec-Fetch-Site: same-site
< Pragma: no-cache
< Cache-Control: no-cache
< Upgrade: websocket
> HTTP/1.1 101 Switching Protocols
> Upgrade: websocket
> Connection: Upgrade
> Sec-WebSocket-Accept: KsKC6t3ivFlLOoikjNWNxRq1nA0=
> Sec-WebSocket-Extensions: permessage-deflate; server_max_window_bits=12
> Date: Mon, 07 Nov 2022 11:22:20 GMT
> Server: Python/3.9 websockets/10.4
connection open
= connection is OPEN
< TEXT 'hello' [5 bytes]
hello
< TEXT 'bye' [3 bytes]
< CLOSE 1000 (OK) [2 bytes]
= connection is CLOSING
> CLOSE 1000 (OK) [2 bytes]
x half-closing TCP connection
bye
= connection is CLOSED
connection closed
```

this seems to support the idea that browsers send a 1005 close code when sending an empty close request, but again I do not know whether that’s a strict interpretation of the protocol or not.

Thanks.

**Comment by aaugustin** [comment]
For context, it is legal to send a WebSocket close frame without any content — there's only a WebSocket header telling that it's a close frame with a payload of 0 bytes. This is what is happening here.

The spec says this should be translated to a status code of 1005. This is an artificial status code: it wasn't present in the close frame.

It's hard to tell if the connection was closed normally or erroneously if there's no information about how it was closed in the close frame...

I agree to classify it as "OK" rather than "Error", given that it's the result of calling `WebSocket.close()` in a browser, and someone doing that is closing the connection normally.

I guess I didn't notice earlier because most WebSocket connections are closed by navigating away from the page and browsers send a 1001 code automatically in that case.

**Comment by aaugustin** [comment]
Thank you for reporting this!

**Comment by LambdaP** [comment]
Pleasure :-)
