### ISSUE TITLE
Getting errors like that

### ISSUE THREAD

**Issue by damc** [aaugustin/websockets#1296]
Here's a snippet from my logs:

```
2023-02-15T14:47:47.944940+00:00 app[web.1]: DEBUG:websockets.server:% sending keepalive ping
2023-02-15T14:47:48.043463+00:00 app[web.1]: DEBUG:websockets.server:% received keepalive pong
2023-02-15T14:48:08.061871+00:00 app[web.1]: DEBUG:websockets.server:% sending keepalive ping
2023-02-15T14:48:08.159636+00:00 app[web.1]: DEBUG:websockets.server:% received keepalive pong
2023-02-15T14:48:28.173193+00:00 app[web.1]: DEBUG:websockets.server:% sending keepalive ping
2023-02-15T14:48:28.271360+00:00 app[web.1]: DEBUG:websockets.server:% received keepalive pong
2023-02-15T14:48:31.213807+00:00 app[web.1]: DEBUG:websockets.server:= connection is CONNECTING
2023-02-15T14:48:31.215303+00:00 app[web.1]: DEBUG:websockets.server:! invalid handshake
2023-02-15T14:48:31.215304+00:00 app[web.1]: Traceback (most recent call last):
2023-02-15T14:48:31.215304+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/websockets/legacy/http.py", line 74, in read_request
2023-02-15T14:48:31.215305+00:00 app[web.1]: request_line = await read_line(stream)
2023-02-15T14:48:31.215305+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^
2023-02-15T14:48:31.215305+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/websockets/legacy/http.py", line 200, in read_line
2023-02-15T14:48:31.215305+00:00 app[web.1]: raise EOFError("line without CRLF")
2023-02-15T14:48:31.215306+00:00 app[web.1]: EOFError: line without CRLF
2023-02-15T14:48:31.215307+00:00 app[web.1]: 
2023-02-15T14:48:31.215308+00:00 app[web.1]: The above exception was the direct cause of the following exception:
2023-02-15T14:48:31.215308+00:00 app[web.1]: 
2023-02-15T14:48:31.215308+00:00 app[web.1]: Traceback (most recent call last):
2023-02-15T14:48:31.215309+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/websockets/legacy/server.py", line 279, in read_http_request
2023-02-15T14:48:31.215309+00:00 app[web.1]: path, headers = await read_request(self.reader)
2023-02-15T14:48:31.215309+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-02-15T14:48:31.215309+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/websockets/legacy/http.py", line 76, in read_request
2023-02-15T14:48:31.215310+00:00 app[web.1]: raise EOFError("connection closed while reading HTTP request line") from exc
2023-02-15T14:48:31.215310+00:00 app[web.1]: EOFError: connection closed while reading HTTP request line
2023-02-15T14:48:31.215310+00:00 app[web.1]: 
2023-02-15T14:48:31.215310+00:00 app[web.1]: The above exception was the direct cause of the following exception:
2023-02-15T14:48:31.215311+00:00 app[web.1]: 
2023-02-15T14:48:31.215311+00:00 app[web.1]: Traceback (most recent call last):
2023-02-15T14:48:31.215311+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/websockets/legacy/server.py", line 165, in handler
2023-02-15T14:48:31.215311+00:00 app[web.1]: await self.handshake(
2023-02-15T14:48:31.215311+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/websockets/legacy/server.py", line 587, in handshake
2023-02-15T14:48:31.215312+00:00 app[web.1]: path, request_headers = await self.read_http_request()
2023-02-15T14:48:31.215312+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-02-15T14:48:31.215312+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/websockets/legacy/server.py", line 283, in read_http_request
2023-02-15T14:48:31.215312+00:00 app[web.1]: raise InvalidMessage("did not receive a valid HTTP request") from exc
2023-02-15T14:48:31.215313+00:00 app[web.1]: websockets.exceptions.InvalidMessage: did not receive a valid HTTP request
2023-02-15T14:48:31.215431+00:00 app[web.1]: DEBUG:websockets.server:> HTTP/1.1 400 Bad Request
2023-02-15T14:48:31.215462+00:00 app[web.1]: DEBUG:websockets.server:> Date: Wed, 15 Feb 2023 14:48:31 GMT
2023-02-15T14:48:31.215487+00:00 app[web.1]: DEBUG:websockets.server:> Server: Python/3.11 websockets/10.4
2023-02-15T14:48:31.215510+00:00 app[web.1]: DEBUG:websockets.server:> Content-Length: 77
2023-02-15T14:48:31.215534+00:00 app[web.1]: DEBUG:websockets.server:> Content-Type: text/plain
2023-02-15T14:48:31.215556+00:00 app[web.1]: DEBUG:websockets.server:> Connection: close
2023-02-15T14:48:31.215676+00:00 app[web.1]: DEBUG:websockets.server:> [body] (77 bytes)
2023-02-15T14:48:31.215725+00:00 app[web.1]: INFO:websockets.server:connection failed (400 Bad Request)
2023-02-15T14:48:31.215755+00:00 app[web.1]: DEBUG:websockets.server:x closing TCP connection
2023-02-15T14:48:31.215826+00:00 app[web.1]: DEBUG:websockets.server:= connection is CLOSED
2023-02-15T14:48:31.215977+00:00 app[web.1]: INFO:websockets.server:connection closed
2023-02-15T14:48:48.287158+00:00 app[web.1]: DEBUG:websockets.server:% sending keepalive ping
2023-02-15T14:48:48.387962+00:00 app[web.1]: DEBUG:websockets.server:% received keepalive pong
2023-02-15T14:49:08.405404+00:00 app[web.1]: DEBUG:websockets.server:% sending keepalive ping
2023-02-15T14:49:08.505126+00:00 app[web.1]: DEBUG:websockets.server:% received keepalive pong
2023-02-15T14:49:28.525400+00:00 app[web.1]: DEBUG:websockets.server:% sending keepalive ping
2023-02-15T14:49:28.626193+00:00 app[web.1]: DEBUG:websockets.server:% received keepalive pong
2023-02-15T14:49:48.644057+00:00 app[web.1]: DEBUG:websockets.server:% sending keepalive ping
2023-02-15T14:49:48.742810+00:00 app[web.1]: DEBUG:websockets.server:% received keepalive pong
2023-02-15T14:50:08.757560+00:00 app[web.1]: DEBUG:websockets.server:% sending keepalive ping
2023-02-15T14:50:08.855904+00:00 app[web.1]: DEBUG:websockets.server:% received keepalive pong
2023-02-15T14:50:28.873391+00:00 app[web.1]: DEBUG:websockets.server:% sending keepalive ping
2023-02-15T14:50:28.972192+00:00 app[web.1]: DEBUG:websockets.server:% received keepalive pong
2023-02-15T14:50:31.494792+00:00 app[web.1]: DEBUG:websockets.server:= connection is CONNECTING
2023-02-15T14:50:31.496062+00:00 app[web.1]: DEBUG:websockets.server:! invalid handshake
2023-02-15T14:50:31.496062+00:00 app[web.1]: Traceback (most recent call last):
2023-02-15T14:50:31.496063+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/websockets/legacy/http.py", line 74, in read_request
2023-02-15T14:50:31.496063+00:00 app[web.1]: request_line = await read_line(stream)
2023-02-15T14:50:31.496064+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^
2023-02-15T14:50:31.496069+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/websockets/legacy/http.py", line 200, in read_line
2023-02-15T14:50:31.496069+00:00 app[web.1]: raise EOFError("line without CRLF")
2023-02-15T14:50:31.496070+00:00 app[web.1]: EOFError: line without CRLF
2023-02-15T14:50:31.496071+00:00 app[web.1]: 
2023-02-15T14:50:31.496071+00:00 app[web.1]: The above exception was the direct cause of the following exception:
2023-02-15T14:50:31.496072+00:00 app[web.1]: 
2023-02-15T14:50:31.496072+00:00 app[web.1]: Traceback (most recent call last):
2023-02-15T14:50:31.496072+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/websockets/legacy/server.py", line 279, in read_http_request
2023-02-15T14:50:31.496073+00:00 app[web.1]: path, headers = await read_request(self.reader)
2023-02-15T14:50:31.496073+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-02-15T14:50:31.496073+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/websockets/legacy/http.py", line 76, in read_request
2023-02-15T14:50:31.496074+00:00 app[web.1]: raise EOFError("connection closed while reading HTTP request line") from exc
2023-02-15T14:50:31.496075+00:00 app[web.1]: EOFError: connection closed while reading HTTP request line
2023-02-15T14:50:31.496075+00:00 app[web.1]: 
2023-02-15T14:50:31.496075+00:00 app[web.1]: The above exception was the direct cause of the following exception:
2023-02-15T14:50:31.496075+00:00 app[web.1]: 
2023-02-15T14:50:31.496075+00:00 app[web.1]: Traceback (most recent call last):
2023-02-15T14:50:31.496076+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/websockets/legacy/server.py", line 165, in handler
2023-02-15T14:50:31.496076+00:00 app[web.1]: await self.handshake(
2023-02-15T14:50:31.496076+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/websockets/legacy/server.py", line 587, in handshake
2023-02-15T14:50:31.496076+00:00 app[web.1]: path, request_headers = await self.read_http_request()
2023-02-15T14:50:31.496076+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-02-15T14:50:31.496076+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/websockets/legacy/server.py", line 283, in read_http_request
2023-02-15T14:50:31.496077+00:00 app[web.1]: raise InvalidMessage("did not receive a valid HTTP request") from exc
2023-02-15T14:50:31.496077+00:00 app[web.1]: websockets.exceptions.InvalidMessage: did not receive a valid HTTP request
2023-02-15T14:50:31.496213+00:00 app[web.1]: DEBUG:websockets.server:> HTTP/1.1 400 Bad Request
2023-02-15T14:50:31.496265+00:00 app[web.1]: DEBUG:websockets.server:> Date: Wed, 15 Feb 2023 14:50:31 GMT
2023-02-15T14:50:31.496298+00:00 app[web.1]: DEBUG:websockets.server:> Server: Python/3.11 websockets/10.4
2023-02-15T14:50:31.496332+00:00 app[web.1]: DEBUG:websockets.server:> Content-Length: 77
2023-02-15T14:50:31.496369+00:00 app[web.1]: DEBUG:websockets.server:> Content-Type: text/plain
2023-02-15T14:50:31.496401+00:00 app[web.1]: DEBUG:websockets.server:> Connection: close
2023-02-15T14:50:31.496440+00:00 app[web.1]: DEBUG:websockets.server:> [body] (77 bytes)
2023-02-15T14:50:31.496501+00:00 app[web.1]: INFO:websockets.server:connection failed (400 Bad Request)
2023-02-15T14:50:31.496536+00:00 app[web.1]: DEBUG:websockets.server:x closing TCP connection
2023-02-15T14:50:31.496633+00:00 app[web.1]: DEBUG:websockets.server:= connection is CLOSED
2023-02-15T14:50:31.496832+00:00 app[web.1]: INFO:websockets.server:connection closed
2023-02-15T14:50:48.990234+00:00 app[web.1]: DEBUG:websockets.server:% sending keepalive ping
2023-02-15T14:50:49.094737+00:00 app[web.1]: DEBUG:websockets.server:% received keepalive pong
2023-02-15T14:51:09.103166+00:00 app[web.1]: DEBUG:websockets.server:% sending keepalive ping
2023-02-15T14:51:09.205527+00:00 app[web.1]: DEBUG:websockets.server:% received keepalive pong
2023-02-15T14:51:29.225763+00:00 app[web.1]: DEBUG:websockets.server:% sending keepalive ping
```

It might be happening when my application on Heroku takes too much time to respond, but I'm not sure.

Perhaps, it's a problem on the client-side. But I'd like to know more about what this means: `EOFError("line without CRLF")` so that I know what next steps to take in order to debug it.

**Comment by aaugustin** [comment]
The situation wile be clearer if you read the chained stack traces from bottom to top:

- `websockets.exceptions.InvalidMessage: did not receive a valid HTTP request` because
  - `EOFError: connection closed while reading HTTP request line` because
    - `EOFError: line without CRLF`

This indicates that the connection was closed before you received an opening handshake request. Specifically, CR LF is the line terminator in the HTTP protocol, but you don't really need that level of detail.

**Comment by aaugustin** [comment]
(closing based on your follow-up issue where you narrowed down on the issue)
