### ISSUE TITLE
Test failure in test_close_idempotency_race_condition

### ISSUE THREAD

**Issue by aaugustin** [aaugustin/websockets#1314]
Logs here: https://github.com/aaugustin/websockets/actions/runs/4547546325/jobs/8017577679#step:5:46

**Comment by aaugustin** [comment]
And here: https://github.com/aaugustin/websockets/actions/runs/4550699083/jobs/8023966186#step:5:46

**Comment by aaugustin** [comment]
This happens because PyPY crashes with a RuntimeError in `threading.Thread.join`.

```
======================================================================
ERROR: test_close_idempotency_race_condition (tests.sync.test_connection.ServerConnectionTests)
close waits if the connection is already closing.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/websockets/websockets/tests/sync/test_connection.py", line 488, in test_close_idempotency_race_condition
    self.connection.close()
  File "/home/runner/work/websockets/websockets/.tox/py/lib/pypy3.9/site-packages/websockets/sync/connection.py", line 399, in close
    with self.send_context():
  File "/opt/hostedtoolcache/PyPy/3.9.16/x64/lib/pypy3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/runner/work/websockets/websockets/.tox/py/lib/pypy3.9/site-packages/websockets/sync/connection.py", line 693, in send_context
    self.recv_events_thread.join(timeout)
  File "/opt/hostedtoolcache/PyPy/3.9.16/x64/lib/pypy3.9/threading.py", line 1064, in join
    self._wait_for_tstate_lock(timeout=max(timeout, 0))
  File "/opt/hostedtoolcache/PyPy/3.9.16/x64/lib/pypy3.9/threading.py", line 1081, in _wait_for_tstate_lock
    lock.release()
RuntimeError: cannot release un-acquired lock

----------------------------------------------------------------------
```

I don't want to investigate that. I'll ignore the test.
