### ISSUE TITLE
Pong are not sent which result in connection drop with ConnectionClosedError 

### ISSUE THREAD

**Issue by tynianovddi** [aaugustin/websockets#1318]
Hey guys,

I try to connect to websocket server (Binance WS server in my case), its doc says that ping are sent periodically to check if the connection is still alive. Everything works just fine until PING is received. It seems to me that PONGs are not sent back, because I get this error:

> websockets.exceptions.ConnectionClosedError: sent 1011 (unexpected error) keepalive ping timeout; no close frame received

Here is my code snippet where I connect to the ws server and handle incoming messages:
Please note that I omit some functions such as convert_subscribe_pairs_name, _on_message, subscribe_on_topics etc because they are related to business logic and have nothing to do with websocket.
```
async def create_connection(self, observed_pairs: List[str]):
    self._observed_pairs = observed_pairs
    subscribe_pairs = list(
        map(
            self.convert_subscribe_pairs_name,
            self._observed_pairs
        )
    )
    async with websockets.connect(self.SOCKET_URL) as ws:
        await self.subscribe_on_topics(ws, subscribe_pairs, self._ident)

        async for message in ws:
            await self._on_message(message)
```

Here is full traceback of the error:
```
Traceback (most recent call last):
  File "/usr/src/app/manage.py", line 22, in <module>
    main()
  File "/usr/src/app/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/usr/src/app/crypto_websocket/management/commands/start_socket.py", line 22, in handle
    loop.run_until_complete(start_async_sockets())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/src/app/arbitrage/start_exchanger.py", line 150, in start_async_sockets
    await start_provider_async_socket(name, handlers)
  File "/usr/src/app/arbitrage/start_exchanger.py", line 145, in start_provider_async_socket
    await starter_instance.start()
  File "/usr/src/app/crypto_websocket/socket_starter.py", line 201, in start
    await asyncio.gather(*self._tasks)
  File "/usr/src/app/crypto_websocket/webscoket.py", line 468, in create_connection
    async for message in ws:
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 482, in __aiter__
    yield await self.recv()
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 553, in recv
    await self.ensure_open()
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 930, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
```
As far as i can see from the doc, pings are handled automatically. 
Any suggestion would be useful, thanks in advance!

**Comment by ottoshark** [comment]
hi, i'm getting the same error and i do think it's because how websockets handle pings. can you please explain how did you solve this?

**Comment by aaugustin** [comment]
https://websockets.readthedocs.io/en/stable/topics/keepalive.html should help.

**Comment by ottoshark** [comment]
> https://websockets.readthedocs.io/en/stable/topics/keepalive.html should help.

I implemented that keepalive function but it didn't help. The server side recommended me to use websocket-client library instead of websockets. They told that websockets library couldn't handle their ping frames. However, my entire application is written with websockets and I want to stick with it, I am sure I can find a solution for that with websockets!

**Comment by aaugustin** [comment]
> They told that websockets library couldn't handle their ping frames. 

There's absolutely no evidence of this claim. I think it's bullshit. 

> I am able to postpone the connection close by setting ping_interval a high number.

I know what's happening but I will not help you for this reason:

https://websockets.readthedocs.io/en/stable/project/support.html#cryptocurrency-users

**Comment by aaugustin** [comment]
> They told that websockets library couldn't handle their ping frames. 

There's zero evidence of this claim. I call bullshit.

> I am able to postpone the connection close by setting ping_interval a high number.

If this makes a difference, then them most probable causes are:

1. The server sends data faster than you can read it. Send `ping_interval` to a value high enough for your app to catch up. (If your app never catches up, you have a more fundamental problem.)
2. The server doesn't answer pings with pongs. Just disable keepalive entirely in that case.

**Comment by ottoshark** [comment]
Thank you. setting ping_interval and ping_timeout to None helped, I don't get any error.
