### ISSUE TITLE
how to handle ConnectionAbortedError [10053]

### ISSUE THREAD

**Issue by Megido6** [aaugustin/websockets#138]
```
Error in closing handshake
Traceback (most recent call last):
  File "C:\python34\lib\site-packages\websockets-3.2-py3.4.egg\websockets\server.py", line 91, in handler
    yield from self.close()
  File "C:\python34\lib\site-packages\websockets-3.2-py3.4.egg\websockets\protocol.py", line 241, in close
    self.worker_task, self.timeout, loop=self.loop)
  File "C:\python34\lib\asyncio\tasks.py", line 413, in wait_for
    return fut.result()
  File "C:\python34\lib\asyncio\futures.py", line 243, in result
    raise self._exception
  File "C:\python34\lib\asyncio\tasks.py", line 279, in _step
    result = coro.throw(exc)
  File "C:\python34\lib\site-packages\websockets-3.2-py3.4.egg\websockets\protocol.py", line 413, in run
    msg = yield from self.read_message()
  File "C:\python34\lib\site-packages\websockets-3.2-py3.4.egg\websockets\protocol.py", line 435, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "C:\python34\lib\site-packages\websockets-3.2-py3.4.egg\websockets\protocol.py", line 490, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "C:\python34\lib\site-packages\websockets-3.2-py3.4.egg\websockets\protocol.py", line 525, in read_frame
    self.reader.readexactly, is_masked, max_size=max_size)
  File "C:\python34\lib\site-packages\websockets-3.2-py3.4.egg\websockets\framing.py", line 80, in read_frame
    data = yield from reader(2)
  File "C:\python34\lib\asyncio\streams.py", line 461, in readexactly
    block = yield from self.read(n)
  File "C:\python34\lib\asyncio\streams.py", line 432, in read
    yield from self._waiter
  File "C:\python34\lib\asyncio\futures.py", line 348, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\python34\lib\asyncio\tasks.py", line 332, in _wakeup
    value = future.result()
  File "C:\python34\lib\asyncio\futures.py", line 243, in result
    raise self._exception
  File "C:\python34\lib\site-packages\websockets-3.2-py3.4.egg\websockets\protocol.py", line 566, in write_frame
    yield from self.writer.drain()
  File "C:\python34\lib\asyncio\streams.py", line 284, in drain
    raise self._reader._exception
  File "C:\python34\lib\asyncio\selector_events.py", line 487, in write
    n = self._sock.send(data)
ConnectionAbortedError: [WinError 10053] 
```
This error occurs when client close connection

**Comment by aaugustin** [comment]
This happens when the client closes the connection summarily, without a closing handshake. There isn't much websockets can do in this situation.

Would you like to suggest a different behavior?

**Comment by Megido6** [comment]
i want just  hide error

**Comment by aaugustin** [comment]
Configure logging to set the `websockets.server` logger at the level ERROR or higher.

See the documentation of the logging module in Python's standard library for details.

**Comment by Megido6** [comment]
its not enought
asyncio returns error too
| asyncio |  ERROR: Fatal write error on socket transport

need setup logger for asyncio too

```
formatter = logging.Formatter('%(asctime)s | %(name)s |  %(levelname)s: %(message)s')

server_logger =  logging.getLogger('websockets.server')
fh = logging.FileHandler('error.log',mode='a')
fh.setLevel(logging.DEBUG)
fh.setFormatter(formatter)
server_logger.addHandler(fh)

asyncio_logger =  logging.getLogger('asyncio')
fh = logging.FileHandler('error.log',mode='a')
fh.setLevel(logging.DEBUG)
fh.setFormatter(formatter)
asyncio_logger.addHandler(fh)
```
