### ISSUE TITLE
Exception that I cannot get handled

### ISSUE THREAD

**Issue by jacksonofalltrades** [aaugustin/websockets#184]
Hi,

I'm trying to implement your producer/consumer example, and it's working fine until the client closes their side of the connection. Then, I get exceptions on the server that I can't seem to handle gracefully. I've tried researching how to deal with exceptions for Futures, but nothing has worked. Here is what it looks like:

<details>

```
Unexpected error: WebSocket connection is closed: code = 1006, no reason.
User mik closed their connection
Error in closing handshake
Traceback (most recent call last):
  File "/Users/dej/wa/dragonfly/bigsur/venv/lib/python3.6/site-packages/websockets/protocol.py", line 571, in write_frame
    yield from self.writer.drain()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/streams.py", line 323, in drain
    raise exc
  File "/Users/dej/wa/dragonfly/bigsur/venv/lib/python3.6/site-packages/websockets/protocol.py", line 571, in write_frame
    yield from self.writer.drain()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/streams.py", line 333, in drain
    yield from self._protocol._drain_helper()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/streams.py", line 211, in _drain_helper
    yield from waiter
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/selector_events.py", line 785, in _write_ready
    n = self._sock.send(self._buffer)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dej/wa/dragonfly/bigsur/venv/lib/python3.6/site-packages/websockets/server.py", line 94, in handler
    yield from self.close()
  File "/Users/dej/wa/dragonfly/bigsur/venv/lib/python3.6/site-packages/websockets/protocol.py", line 242, in close
    self.worker_task, self.timeout, loop=self.loop)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/tasks.py", line 352, in wait_for
    return fut.result()
  File "/Users/dej/wa/dragonfly/bigsur/venv/lib/python3.6/site-packages/websockets/protocol.py", line 414, in run
    msg = yield from self.read_message()
  File "/Users/dej/wa/dragonfly/bigsur/venv/lib/python3.6/site-packages/websockets/protocol.py", line 436, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "/Users/dej/wa/dragonfly/bigsur/venv/lib/python3.6/site-packages/websockets/protocol.py", line 499, in read_data_frame
    yield from self.write_frame(OP_CLOSE, frame.data)
  File "/Users/dej/wa/dragonfly/bigsur/venv/lib/python3.6/site-packages/websockets/protocol.py", line 576, in write_frame
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006, no reason.
^CTraceback (most recent call last):
  File "src/locix/websocket/server.py", line 156, in <module>
    asyncio.get_event_loop().run_forever()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 421, in run_forever
    self._run_once()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 1389, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/selectors.py", line 577, in select
    kev_list = self._kqueue.control(None, max_ev, timeout)
KeyboardInterrupt
```

</details>

All I want to be able to do is not have the exception spew to the console, but show a nice message, "user 1 has disconnected"

The main difference from your example is that I don't have consumer() and producer() methods, I just do my consuming and producing directly in the consumer_handler() and producer_handler() async methods. To be honest, I'm still pretty new to asyncio, so that may be part of the problem.

Thanks!

**Comment by aaugustin** [comment]
This output is generated by logging.

Since the last release, there have been changes to reduce verbosity. Now the code looks like this: https://github.com/aaugustin/websockets/blob/5d361a361a31ce19896dd0fb2c9dc684514e2a09/websockets/server.py#L108-L117

I don't think you should see these errors anymore with the current implementation in the `master` branch. If you can try it and confirm if it solves the problem for you, that's useful.

**Comment by aaugustin** [comment]
Given the lack of feedback, I'm going to close this ticket. Please reopen if the problem still exists in `master`.

**Comment by jacksonofalltrades** [comment]
Hey sorry for the delay. I just hadn't had a chance yet to try what you suggested. I'll let you know if I do run into it again, thanks! Otherwise the library has been working great so far, thank you!

**Comment by aaugustin** [comment]
Okay! I know it isn't easy to test until I put out a new release. I'd like to get #93 done.
