### ISSUE TITLE
Ensure server stops on test failure

### ISSUE THREAD

**Issue by cjerdonek** [aaugustin/websockets#218]
When developing `websockets` locally and running tests, it is currently not so convenient because a single failing test can result in 50+ test failures like the following, making it harder to find the root failure.

This is because the `self.stop_server()` line in many tests isn't in a finally block.

    ERROR: test_subprotocol_error (websockets.test_client_server.SSLClientServerTests)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/.../versions/3.6.1/lib/python3.6/asyncio/base_events.py", line 1043, in create_server
        sock.bind(sa)
    OSError: [Errno 48] Address already in use

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/.../versions/3.6.1/lib/python3.6/unittest/mock.py", line 1179, in patched
        return func(*args, **keywargs)
      File "/.../websockets/websockets/test_client_server.py", line 319, in test_subprotocol_error
        self.start_server(subprotocols=['superchat'])
      File "/.../websockets/websockets/test_client_server.py", line 506, in start_server
        self.server = self.loop.run_until_complete(server)
      File "/.../versions/3.6.1/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
        return future.result()
      File "/.../versions/3.6.1/lib/python3.6/asyncio/tasks.py", line 530, in _wrap_awaitable
        return (yield from awaitable.__await__())
      File "/.../websockets/websockets/py35/server.py", line 20, in __await__
        return (yield from self.server)
      File "/.../websockets/websockets/server.py", line 487, in serve
        server = yield from loop.create_server(factory, host, port, **kwds)
      File "/.../versions/3.6.1/lib/python3.6/asyncio/base_events.py", line 1047, in create_server
        % (sa, err.strerror.lower()))
    OSError: [Errno 48] error while attempting to bind on address ('fe80::1%lo0', 8642, 0, 1): address already in use

Patch forthcoming.

**Comment by cjerdonek** [comment]
I added PR #219 for this.

**Comment by aaugustin** [comment]
Ha! This has been annoying me since I started this library and I never took the time to fix it! You rock!

I took a cursory look at the patch and it looks very promising. I'll review it more thoroughly today, hopefully.

**Comment by cjerdonek** [comment]
Cool, thank you for being receptive!

**Comment by cjerdonek** [comment]
Closed by PR #219. Thanks again!
