### ISSUE TITLE
Flaky tests on macOS

### ISSUE THREAD

**Issue by aaugustin** [aaugustin/websockets#241]
From #239.

`test_close_handshake_timeout` fails on macOS with error `AssertionError: 0.03943201599997792 not less than 0.029 : Too slow: 0.03943201599997792 >= 0.029`

Full stack trace: https://travis-ci.org/mayeut/websockets/jobs/259532227

**Comment by aaugustin** [comment]
See also https://github.com/aaugustin/websockets/pull/239#issuecomment-319685628

**Comment by aaugustin** [comment]
Definitely flaky, I just got this locally:
```
======================================================================
FAIL: test_close_handshake_timeout (websockets.test_protocol.ClientTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/myk/Documents/dev/websockets/websockets/test_protocol.py", line 775, in test_close_handshake_timeout
    self.loop.run_until_complete(self.protocol.close(reason='close'))
  File "/Users/myk/.pyenv/versions/3.6.2/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/Users/myk/Documents/dev/websockets/websockets/test_protocol.py", line 249, in assertCompletesWithin
    dt, max_time, "Too slow: {} >= {}".format(dt, max_time))
AssertionError: 0.029119426995748654 not less than 0.029 : Too slow: 0.029119426995748654 >= 0.029

----------------------------------------------------------------------
Ran 274 tests in 0.681s

FAILED (failures=1)
```

**Comment by aaugustin** [comment]
There's a chance #267 might fix it as it re-implements timeouts on connection close in a much more obvious way.

**Comment by aaugustin** [comment]
Apparently #267 fixed it.
