### ISSUE TITLE
Validate Sec-WebSocket-Protocol and Sec-WebSocket-Extensions values

### ISSUE THREAD

**Issue by aaugustin** [aaugustin/websockets#263]
`websockets` trusts the user to provide suitable values for these headers.

We may want to enforce that values meet the RFC's requirements -- everything must be a token (as defined by the ABNF for HTTP headers).

**Comment by aaugustin** [comment]
In https://github.com/aaugustin/websockets/issues/331#issuecomment-361160100 the OP got confused when they passed a string instead of a list of string as extensions.

**Comment by aaugustin** [comment]
Also https://github.com/aaugustin/websockets/issues/331#issuecomment-358787179 suggests to disallow passing reserved headers in `extra_headers`, another possible validation.

**Comment by aaugustin** [comment]
This is harder than it seems:

- subprotocols can be validated statically when creating the server. However, doing so in the the protocol's __init__ doesn't work well in tests, because the socket is already open and leaks
- extensions may be validated statically on the client side, but it isn't very elegant, and they can only be validated for each response on the server side

Here's how far I went before giving up:

```diff
diff --git a/websockets/client.py b/websockets/client.py
index f873903..754c64c 100644
--- a/websockets/client.py
+++ b/websockets/client.py
@@ -14,7 +14,7 @@ from .extensions.permessage_deflate import ClientPerMessageDeflateFactory
 from .handshake import build_request, check_response
 from .headers import (
     build_extension_list, build_protocol_list, parse_extension_list,
-    parse_protocol_list
+    parse_protocol_list, validate_extension_list, validate_protocol_list
 )
 from .http import USER_AGENT, basic_auth_header, build_headers, read_response
 from .protocol import WebSocketCommonProtocol
@@ -39,7 +39,17 @@ class WebSocketClientProtocol(WebSocketCommonProtocol):
                  origin=None, extensions=None, subprotocols=None,
                  extra_headers=None, **kwds):
         self.origin = origin
+        if extensions is not None:
+            validate_extension_list([
+                (
+                    extension_factory.name,
+                    extension_factory.get_request_params(),
+                )
+                for extension_factory in extensions
+            ])
         self.available_extensions = extensions
+        if subprotocols is not None:
+            validate_protocol_list(subprotocols)
         self.available_subprotocols = subprotocols
         self.extra_headers = extra_headers
         super().__init__(**kwds)
diff --git a/websockets/headers.py b/websockets/headers.py
index c5b228c..ca6a011 100644
--- a/websockets/headers.py
+++ b/websockets/headers.py
@@ -7,14 +7,15 @@ from :mod:`websockets.headers`.

 """

+import collections.abc
 import re

 from .exceptions import InvalidHeader


 __all__ = [
-    'parse_extension_list', 'build_extension_list',
-    'parse_protocol_list', 'build_protocol_list',
+    'parse_extension_list', 'build_extension_list', 'validate_extension_list',
+    'parse_protocol_list', 'build_protocol_list', 'validate_protocol_list',
 ]


@@ -235,6 +236,25 @@ def build_extension_list(extensions):
     )


+def validate_extension_list(extensions):
+    """
+    Validate that ``extensions`` is suitable for :func:`build_extension_list`.
+
+    """
+    if not isinstance(extensions, collections.abc.Iterable):
+        raise TypeError("Subprotocols must be a list")
+    if isinstance(extensions, str):
+        raise TypeError("extensions must be a list, not a str")
+    for name, parameters in extensions:
+        if not _token_re.fullmatch(name):
+            raise ValueError("Invalid extension name: %r" % name)
+        for name, value in parameters:
+            if not _token_re.fullmatch(name):
+                raise ValueError("Invalid parameter name: %r" % name)
+            if value is not None and not _token_re.fullmatch(value):
+                raise ValueError("Invalid parameter value: %r" % value)
+
+
 def parse_protocol(string, pos):
     """
     Parse a protocol definition from ``string`` at the given position.
@@ -307,3 +327,17 @@ def build_protocol_list(protocols):

     """
     return ', '.join(protocols)
+
+
+def validate_protocol_list(protocols):
+    """
+    Validate that ``protocols`` is suitable for :func:`build_protocol_list`.
+
+    """
+    if not isinstance(protocols, collections.abc.Iterable):
+        raise TypeError("Subprotocols must be a list")
+    if isinstance(protocols, str):
+        raise TypeError("Subprotocols must be a list, not a str")
+    for protocol in protocols:
+        if not _token_re.fullmatch(protocol):
+            raise ValueError("Invalid subprotocol: %r" % protocol)
diff --git a/websockets/server.py b/websockets/server.py
index e58c0ac..ae1630a 100644
--- a/websockets/server.py
+++ b/websockets/server.py
@@ -19,7 +19,8 @@ from .exceptions import (
 from .extensions.permessage_deflate import ServerPerMessageDeflateFactory
 from .handshake import build_response, check_request
 from .headers import (
-    build_extension_list, parse_extension_list, parse_protocol_list
+    build_extension_list, parse_extension_list, parse_protocol_list,
+    validate_extension_list, validate_protocol_list
 )
 from .http import USER_AGENT, build_headers, read_request
 from .protocol import WebSocketCommonProtocol
@@ -50,7 +51,10 @@ class WebSocketServerProtocol(WebSocketCommonProtocol):
         self.ws_handler = ws_handler
         self.ws_server = ws_server
         self.origins = origins
+        # extensions can only be validated after processing a request
         self.available_extensions = extensions
+        if subprotocols is not None:
+            validate_protocol_list(subprotocols)
         self.available_subprotocols = subprotocols
         self.extra_headers = extra_headers
         super().__init__(**kwds)
@@ -341,6 +345,7 @@ class WebSocketServerProtocol(WebSocketCommonProtocol):

         # Serialize extension header.
         if response_header:
+            validate_extension_list(response_header)
             response_header = build_extension_list(response_header)
         else:
             response_header = None
diff --git a/websockets/test_client_server.py b/websockets/test_client_server.py
index 7ee8b78..2d70e3e 100644
--- a/websockets/test_client_server.py
+++ b/websockets/test_client_server.py
@@ -204,6 +204,23 @@ class NoOpExtension:
         return frame


+class ClientBadExtensionFactory:
+    name = 'x-no-op'
+
+    def get_request_params(self):
+        return [('not good', None)]
+
+    def process_response_params(self, params, accepted_extensions):
+        return NoOpExtension()
+
+
+class ServerBadExtensionFactory:
+    name = 'x-no-op'
+
+    def process_request_params(self, params, accepted_extensions):
+        return [('not good', None)], NoOpExtension()
+
+
 class ClientServerTests(unittest.TestCase):

     secure = False
@@ -540,6 +557,16 @@ class ClientServerTests(unittest.TestCase):
     def test_client_create_protocol_over_klass(self):
         self.assertIsInstance(self.client, BarClientProtocol)

+    @with_server()
+    def test_extension_value_error_client(self):
+        with self.assertRaises(ValueError):
+            self.start_client(extensions=[ClientBadExtensionFactory()])
+
+    @with_server(extensions=[ServerBadExtensionFactory()])
+    def test_extension_value_error_server(self):
+        with self.assertRaises(InvalidStatusCode):
+            self.start_client(extensions=[ClientNoOpExtensionFactory()])
+
     @with_server()
     @with_client('/extensions')
     def test_no_extension(self):
@@ -698,6 +725,28 @@ class ClientServerTests(unittest.TestCase):
         with self.assertRaises(ValueError):
             self.loop.run_until_complete(self.start_client(compression='xz'))

+    @with_server()
+    def test_subprotocol_type_error_client(self):
+        with self.assertRaises(TypeError):
+            self.loop.run_until_complete(
+                self.start_client(subprotocols='chat'))
+
+    @with_server()
+    def test_subprotocol_value_error_client(self):
+        with self.assertRaises(ValueError):
+            self.loop.run_until_complete(
+                self.start_client(subprotocols=['spacy chat']))
+
+    def test_subprotocol_type_error_server(self):
+        with self.assertRaises(TypeError):
+            self.loop.run_until_complete(
+                self.start_server(subprotocols='chat'))
+
+    def test_subprotocol_value_error_server(self):
+        with self.assertRaises(ValueError):
+            self.loop.run_until_complete(
+                self.start_server(subprotocols=['spacy chat']))
+
     @with_server()
     @with_client('/subprotocol')
     def test_no_subprotocol(self):
@@ -705,6 +754,7 @@ class ClientServerTests(unittest.TestCase):
         self.assertEqual(server_subprotocol, repr(None))
         self.assertEqual(self.client.subprotocol, None)

+
     @with_server(subprotocols=['superchat', 'chat'])
     @with_client('/subprotocol', subprotocols=['otherchat', 'chat'])
     def test_subprotocol(self):
diff --git a/websockets/test_headers.py b/websockets/test_headers.py
index 230aadf..adfb048 100644
--- a/websockets/test_headers.py
+++ b/websockets/test_headers.py
@@ -69,6 +69,67 @@ class HeadersTests(unittest.TestCase):
                 with self.assertRaises(InvalidHeader):
                     parse_extension_list(header)

+    def test_validate_extension_list(self):
+        for extensions in [
+            [],
+            [('foo', [])],
+            [('foo-bar', [])],
+            [('foo', []), ('bar', [])],
+            [('foo', [('bar', None), ('baz', 'baz')])],
+            [('foo', []), ('bar', [('baz', 'quux')])],
+            [('foo', []), ('bar', [('baz', 'quux'), ('quuux', None)])],
+        ]:
+            with self.subTest(extensions=extensions):
+                # This does not raise an exception.
+                validate_extension_list(extensions)
+
+    def test_validate_extension_list_invalid_type(self):
+        for extensions in [
+            None,
+            'foo',
+        ]:
+            with self.subTest(extensions=extensions):
+                with self.assertRaises(TypeError):
+                    validate_extension_list(extensions)
+
+
+    def test_validate_extension_list_invalid_value(self):
+        for extensions in [
+            [('', [])],
+            [(' ', [])],
+            [('foo ', [])],
+            [('foo bar', [])],
+            [('foo', []), ('', []), ('bar', [])],
+            [('foo', []), (' ', []), ('bar', [])],
+            [('foo', [('', None)])],
+            [('foo', [(' ', None)])],
+            [('foo', [('bar ', None)])],
+            [('foo', [('bar baz', None)])],
+            [('foo', [('bar', '')])],
+            [('foo', [('bar', ' ')])],
+            [('foo', [('bar', 'baz ')])],
+            [('foo', [('bar', 'baz quux')])],
+            [('foo', [('bar', 'baz'), ('', None)])],
+            [('foo', [('bar', 'baz'), (' ', None)])],
+            [('foo', [('bar', 'baz'), ('quux ', None)])],
+            [('foo', [('bar', 'baz'), ('quux quux', None)])],
+            [('foo', [('bar', 'baz'), ('quux', '')])],
+            [('foo', [('bar', 'baz'), ('quux', ' ')])],
+            [('foo', [('bar', 'baz'), ('quux', 'quuux ')])],
+            [('foo', [('bar', 'baz'), ('quux', 'quuux xxx')])],
+            [('foo', []), ('bar', [('', None)])],
+            [('foo', []), ('bar', [(' ', None)])],
+            [('foo', []), ('bar', [('baz ', None)])],
+            [('foo', []), ('bar', [('baz quux', None)])],
+            [('foo', []), ('bar', [('baz', '')])],
+            [('foo', []), ('bar', [('baz', ' ')])],
+            [('foo', []), ('bar', [('baz', 'quux ')])],
+            [('foo', []), ('bar', [('baz', 'quux quux')])],
+         ]:
+            with self.subTest(extensions=extensions):
+                with self.assertRaises(ValueError):
+                    validate_extension_list(extensions)
+
     def test_parse_protocol_list(self):
         for header, parsed in [
             # Synthetic examples
@@ -103,3 +164,40 @@ class HeadersTests(unittest.TestCase):
             with self.subTest(header=header):
                 with self.assertRaises(InvalidHeader):
                     parse_protocol_list(header)
+
+    def test_validate_protocol_list(self):
+        for protocols in [
+            [],
+            ['foo'],
+            ['foo', 'bar'],
+            ['foo-bar'],
+        ]:
+            with self.subTest(protocols=protocols):
+                # This does not raise an exception.
+                validate_protocol_list(protocols)
+
+    def test_validate_protocol_list_invalid_type(self):
+        for protocols in [
+            None,
+            'foo',
+        ]:
+            with self.subTest(protocols=protocols):
+                with self.assertRaises(TypeError):
+                    validate_protocol_list(protocols)
+
+    def test_validate_protocol_list_invalid_value(self):
+        for protocols in [
+            [''],
+            [' '],
+            [','],
+            ['foo '],
+            ['foo,'],
+            ['foo bar'],
+            ['foo,bar'],
+            ['foo', '', 'bar'],
+            ['foo', ' ', 'bar'],
+            ['foo', ',', 'bar'],
+        ]:
+            with self.subTest(protocols=protocols):
+                with self.assertRaises(ValueError):
+                    validate_protocol_list(protocols)
```

**Comment by cjerdonek** [comment]
> However, doing so in the the protocol's init doesn't work well in tests, because the socket is already open and leaks

Can you elaborate on the problem here? Is there something that makes adding the necessary test isolation hard?

**Comment by aaugustin** [comment]
Mostly, it was 11pm, I wrote that comment for future reference and went to bed :-)

I was getting warnings like:

```
/Users/myk/.pyenv/versions/3.6.5/lib/python3.6/traceback.py:216: ResourceWarning: unclosed <socket.socket fd=12, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 51640, 0, 0), raddr=('::1', 51639, 0, 0)>
```

and errors like:

```
======================================================================
ERROR: test_subprotocol_type_error_client (websockets.test_client_server.ClientServerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/myk/Documents/dev/websockets/websockets/test_client_server.py", line 89, in _decorate
    return func(self, *_args, **_kwds)
  File "/Users/myk/.pyenv/versions/3.6.5/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/Users/myk/Documents/dev/websockets/websockets/test_client_server.py", line 68, in temp_test_server
    test.stop_server()
  File "/Users/myk/Documents/dev/websockets/websockets/test_client_server.py", line 267, in stop_server
    asyncio.wait_for(self.server.wait_closed(), timeout=1))
  File "/Users/myk/.pyenv/versions/3.6.5/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/Users/myk/.pyenv/versions/3.6.5/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/Users/myk/Documents/dev/websockets/websockets/server.py", line 587, in wait_closed
    loop=self.loop)
  File "/Users/myk/.pyenv/versions/3.6.5/lib/python3.6/asyncio/tasks.py", line 311, in wait
    fs = {ensure_future(f, loop=loop) for f in set(fs)}
  File "/Users/myk/.pyenv/versions/3.6.5/lib/python3.6/asyncio/tasks.py", line 311, in <setcomp>
    fs = {ensure_future(f, loop=loop) for f in set(fs)}
  File "/Users/myk/.pyenv/versions/3.6.5/lib/python3.6/asyncio/tasks.py", line 526, in ensure_future
    raise TypeError('An asyncio.Future, a coroutine or an awaitable is '
TypeError: An asyncio.Future, a coroutine or an awaitable is required
```

**Comment by cjerdonek** [comment]
Okay. Those errors look unrelated. For the first one, if it's indeed a test isolation issue, I have suggestions on that which continue a suggestion I made in a PR (I believe the PR is still outstanding). It doesn't seem like there should be anything "hard" getting in the way of test isolation.

**Comment by aaugustin** [comment]
Yes, the testing problems should be tractable.

One thing I'm uncomfortable about when we run validations:

- subprotocols are simply lists of strings: it's pretty clear that they can and should be validated once when instantiating the protocol
- extensions are classes implementing a small API:
    - on the client side, they always generate the same header, which can be validated when instantiating the protocol
    - on the server side, there's no way to know all possible responses, so validation needs to be performed at each request, which has a small overhead and adds no value for properly implemented and tested extensions

We can keep the validation of subprotocols (which are directly defined by the user) and fix the tests. As you say, that seems doable.

I'm thinking of simplifying or even removing the validation of extensions. Since they won't be directly written by the user, errors are less likely.

**Comment by aaugustin** [comment]
At this point I'm convinced that it isn't useful to perform validation of extensions. I haven't ruled out validation of subprotocols, as the risk of error is slightly higher, but I'm far from convinced it's useful.

**Comment by aaugustin** [comment]
Perhaps this is just going to end with:

```python
        if isinstance(subprotocols, str):
            subprotocols = [subprotocols]
```

which would solve 90% of the problem...

**Comment by aaugustin** [comment]
Final call — I'm going to validate the `subprotocols` argument passed to `connect()` and `serve()` because, if you're just adding an argument to `connect()` or `serve()`, you could get it wrong; I'm not going to validate `extensions` because, if you're writing three classes, probably you'll manage to get the parameters right.

Also, there's dozen of registered subprotocols vs. only two extensions, one of which is natively supported by websockets, so there's a much higher chance that users will attempt to use the subprotocols argument than extensions argument.
