### ISSUE TITLE
Common Patterns example causing TypeError

### ISSUE THREAD

**Issue by Triztian** [aaugustin/websockets#332]
## Env

 * OS: Darwin MacTristian 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
 * Python 3.6.3

## Cause

The following snippet causes the exception which is a combination of the [Basic Example][0] and the [Consumer Pattern][1].

```
import asyncio
import websockets

async def hello():
    async with websockets.connect('ws://localhost:9061', origin='*') as websocket:
        async for msg in websocket:
            print("< {}".format(msg))

asyncio.get_event_loop().run_until_complete(hello())
```

```
Traceback (most recent call last):
  File "./ws.py", line 9, in <module>
    asyncio.get_event_loop().run_until_complete(hello())
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "./ws.py", line 6, in hello
    async for msg in websocket:
TypeError: 'async for' requires an object with __aiter__ method, got WebSocketClientProtocol
```

[0]: https://websockets.readthedocs.io/en/stable/intro.html#basic-example
[1]: https://websockets.readthedocs.io/en/stable/intro.html#consumer

**Comment by Triztian** [comment]
Fixed was using version `3.4` I determined that by:
```
from websockets.version import version as wsv

print('websockets version: ', wsv)
```
