### ISSUE TITLE
4.x BrokenPipe error (Error in data transfer)

### ISSUE THREAD

**Issue by NotSoSuper** [aaugustin/websockets#349]
This error seems to have originated in the 4.0 release of WebSockets, it was nonexistent in 3.x

```py
Error in data transfer
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 496, in transfer_data
    msg = yield from self.read_message()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 526, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 591, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 632, in read_frame
    extensions=self.extensions,
  File "/usr/local/lib/python3.6/site-packages/websockets/framing.py", line 100, in read
    data = yield from reader(2)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 663, in readexactly
    raise self._exception
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 761, in write
    n = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
```

Not too sure what's causing it, any feedback would be appreciated!

**Comment by aaugustin** [comment]
This means the network connection breaks, either because the other end disconnects brutally or times out, while websockets is waiting for the next frame.

This might be related to #348.

**Comment by aaugustin** [comment]
I'm confident that #389 solves this problem but it's always useful if you can confirm :-)

**Comment by aaugustin** [comment]
Please reopen if the error still occurs after #389 or with the upcoming 5.0 release.

**Comment by NotSoSuper** [comment]
Hey, thank you for the fix!

Sorry for not responding earlier, I've been stumped with school work and completely forgot about this.

I'll test it and let you know of any problems that might arise!

**Comment by aaugustin** [comment]
No hurry :-) There's still quite a few things I'd like to get in 5.0, I don't expect to release it before a few weeks.
