### ISSUE TITLE
unix_serve() is not a context manager

### ISSUE THREAD

**Issue by avdd** [aaugustin/websockets#355]
Great package!  Simple and effective.

It seems (on python3.6) that `unix_serve()` does not return the same object as `serve()`, so it cannot be used as a context manager, which is useful for the signal handler example:

```python
import signal, asyncio, websockets

async def echo(ws, path):
    while True:
        msg = await ws.recv()
        await ws.send(msg)

async def run():
    async with server:
        await stop

# works:
#server = websockets.serve(echo, 'localhost', 8765, reuse_port=True)
#server = websockets.serve(echo, path='/tmp/websocket')
# doesn't work:
server = websockets.unix_serve(echo, '/tmp/websocket')
loop = asyncio.get_event_loop()
stop = asyncio.Future()
loop.add_signal_handler(signal.SIGTERM, stop.set_result, None)
loop.run_until_complete(run())
loop.run_forever()
```
result:
```
Traceback (most recent call last):
  File "websocket-unixsocket.py", line 20, in <module>
    loop.run_until_complete(run())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "websocket-unixsocket.py", line 9, in run
    async with server:
AttributeError: __aexit__
```

**Comment by aaugustin** [comment]
Interesting.

Removing the `@asyncio.coroutine` decorator here https://github.com/aaugustin/websockets/blob/13eb4a09815b7edf3ac6270cbdf131b89b4ccc9d/websockets/server.py#L732 might be enough to fix the issue, would you be able to test that?
