### ISSUE TITLE
test_local_close_connection_lost_timeout_after_close is flaky

### ISSUE THREAD

**Issue by aaugustin** [aaugustin/websockets#390]
```
======================================================================
FAIL: test_local_close_connection_lost_timeout_after_close (websockets.test_protocol.ClientTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/myk/Documents/dev/websockets/websockets/test_protocol.py", line 980, in test_local_close_connection_lost_timeout_after_close
    self.loop.run_until_complete(self.protocol.close(reason='close'))
  File "/Users/myk/.pyenv/versions/3.6.5/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/Users/myk/Documents/dev/websockets/websockets/test_protocol.py", line 316, in assertCompletesWithin
    dt, max_time, "Too slow: {} >= {}".format(dt, max_time))
AssertionError: 0.03926077499636449 not less than 0.039 : Too slow: 0.03926077499636449 >= 0.039

----------------------------------------------------------------------
```

**Comment by aaugustin** [comment]
I haven't seen it fail in a while... I'm going to cross fingers and close this issue (which could make the bug reappear, of course).
