### ISSUE TITLE
example request

### ISSUE THREAD

**Issue by nlsgs** [aaugustin/websockets#395]
Dear Aymeric,

I have come across you work on websockets on  https://websockets.readthedocs.io/en/stable/intro.html
And I would like to thank you for that. Especially the browser based example was helpful.

Just below that example you suggest to use two-way communication and registration. And that is where I get lost. If one is into it, it will all be clear (I suppose) but I do not see what I should put together to get it going both ways.

What I try to make is a html page in the browser containing a field showing a number and two buttons. One to increase the number, and one to decrease it. With a web socket connection to a server it should be possible to open this html page on two devices and use the buttons on either device. Of course the number shown should come from the server and be the same on both devices. Or on all three devices, or four etc.
Maybe it would be nice to show a list of connected IP devices too.

Could you give some more hints how to set this up, or could I get you to extend the html example on the page mentioned to something like I described. It should help more people.

Anyway thank you so far, I hope you will provide some pointers on how to proceed.

Kind regards,

Simon

**Comment by aaugustin** [comment]
This is a good, simple example that involves interactions between connected users. Definitely worth adding to the documentation.

**Comment by aaugustin** [comment]
Here's a proposal.

**CLIENT**

```
<!DOCTYPE html>
<html>
    <head>
        <title>WebSocket demo</title>
        <style type="text/css">
            body {
                font-family: "Courier New", sans-serif;
                text-align: center;
            }
            .buttons {
                font-size: 4em;
                display: flex;
                justify-content: center;
            }
            .button, .value {
                line-height: 1;
                padding: 2rem;
                margin: 2rem;
                border: medium solid;
                min-height: 1em;
                min-width: 1em;
            }
            .button {
                cursor: pointer;
                user-select: none;
            }
            .minus {
                color: red;
            }
            .plus {
                color: green;
            }
            .value {
                min-width: 2em;
            }
            .state {
                font-size: 2em;
            }
        </style>
    </head>
    <body>
        <div class="buttons">
            <div class="minus button">-</div>
            <div class="value">?</div>
            <div class="plus button">+</div>
        </div>
        <div class="state">
            <span class="users">?</span> online
        </div>
        <script>
            var minus = document.querySelector('.minus'),
                plus = document.querySelector('.plus'),
                value = document.querySelector('.value'),
                users = document.querySelector('.users'),
                websocket = new WebSocket("ws://127.0.0.1:6789/");
            minus.onclick = function (event) {
                websocket.send(JSON.stringify({action: 'minus'}));
            }
            plus.onclick = function (event) {
                websocket.send(JSON.stringify({action: 'plus'}));
            }
            websocket.onmessage = function (event) {
                data = JSON.parse(event.data);
                switch (data.type) {
                    case 'state':
                        value.textContent = data.value;
                        break;
                    case 'users':
                        users.textContent = (
                            data.count.toString() + " user" +
                            (data.count == 1 ? "" : "s"));
                        break;
                    default:
                        console.error(
                            "unsupported event", data);
                }
            };
        </script>
    </body>
</html>
```

**SERVER**

```
#!/usr/bin/env python

import asyncio
import json
import logging
import websockets

logging.basicConfig()

STATE = {'value': 0}

USERS = set()

def state_event():
    return json.dumps({'type': 'state', **STATE})

def users_event():
    return json.dumps({'type': 'users', 'count': len(USERS)})

async def notify_state():
    message = state_event()
    await asyncio.gather(*[user.send(message) for user in USERS])

async def notify_users():
    message = users_event()
    await asyncio.gather(*[user.send(message) for user in USERS])

async def register(websocket):
    USERS.add(websocket)
    await notify_users()

async def unregister(websocket):
    USERS.remove(websocket)
    await notify_users()

async def counter(websocket, path):
    # register(websocket) sends user_event() to websocket
    await register(websocket)
    await websocket.send(state_event())
    try:
        async for message in websocket:
            data = json.loads(message)
            if data['action'] == 'minus':
                STATE['value'] -= 1
                await notify_state()
            elif data['action'] == 'plus':
                STATE['value'] += 1
                await notify_state()
            else:
                logging.error(
                    "unsupported event: {}", data)
    finally:
        await unregister(websocket)

asyncio.get_event_loop().run_until_complete(
    websockets.serve(counter, 'localhost', 6789))
asyncio.get_event_loop().run_forever()
```

Notes:

- Currently the server spews errors when a client disconnects. #397 fixes it.
- I committed a critical regression to master. I'm working on fixing it.

**Comment by aaugustin** [comment]
Also there's no error handling in this example.

**Comment by nlsgs** [comment]
Dear Aymeric,
This is more than I bargained for! Thank you. However, I have to tell you not all went well. I suspect it is one of the technicalities with Python. As a Python newby I am horrified with all changes between versions 3.3, 3.4, 3.5 in the area of coroutines. Probably my issue also has to do with this. Starting the server is okay. It sits and waits. When I connect with the html page I get:

ERROR:websockets.server:Exception in connection handler
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/server.py", line 78, in handler
    yield from self.ws_handler(self, path)
  File "aaserver.py", line 41, in counter
    async for message in websocket:
TypeError: 'async for' requires an object with __aiter__ method, got WebSocketServerProtocol

My conclusion  would be that the websocket module I am using is a prehistoric version that does not have this "__aiter__ method", whatever that means or is supposed to do. But I installed the module somewhere last week?! Probably the answer is "move to Python 3.6"?

Anyway, thank you so far!

Simon.

**Comment by aaugustin** [comment]
Yes, the example I provided requires Python 3.6.

If you start a shell with `python`, it will tell you the version of Python. You can also put `import sys; print(sys.version_info)` in the script to be sure.

If you're running Python 3.5, you can replace:

```python
        async for message in websocket:
            ...
```

with:

```python
        while True:
            message = await websocket.recv()
            ...
```

and things should work.

**Comment by aaugustin** [comment]
This should also solve your issue if you're running an version of websockets < 4.0.

You can check the version of websockets by adding `from websockets.version import version; print(version)` in the server script.

**Comment by nlsgs** [comment]
I would like to confirm that with the proposed changes it works using websockets 3.0 and Python 3.5.  Can I say "thank you" once again. This is a nice basis to proceed from. At first I had the idea to have the server send out commands over a serial line to motor controllers (say you change a position by increasing and decreasing the number). That was when I realised that the "network handler" simply also is one of those clients connecting to the server. What a nice and practical thing you have demonstrated here.

**Comment by Melferas** [comment]
Hello @aaugustin,

First, thank you for your hard work. I was wondering about this part of the code you posted:

`        async for message in websocket:`

It works just as fine as using the while loop, but how?

I've been working to make a threaded Websocket Server, so my exit condition was an event I raise manually. 
```
    async def getMessage(self, websocket, path):
        try:
            while not self.stopped():
                msg = await websocket.recv()
                logging.debug(f"Received: {msg}")
        except websockets.exceptions.ConnectionClosed:
            logging.exception()
            raise
        finally:
            logging.debug("Going out!")
```
In the following code, without the loop, it would just listen to one message, then leave. 

But your new way works just fine. **How does 'async for' keep the task alive?** The task it's also killed when connection is closed if I manage the exception, so I'm at awe.
