### ISSUE TITLE
getting errors when trying to connecting to remote websocket server with multiple users

### ISSUE THREAD

**Issue by DowneyTung** [aaugustin/websockets#430]
Hey, there:
I used websockets lib to do api testing via connecting remote websocket server. 
I am able to connect, send, receive data, which could help me do testing. But I am running into issue when I testing scenario like this:
In a single test, user A connect, send, receive data from remote websocket server, then I make User B connect, send, receive data from the same remote webosocket server. The test is running okay, but it will giving me warning/error message like this, I tried multiple ways to suppress the error message, but did not help. Please help. 

```
00:33:57.651 ERROR Fatal write error on socket transport
protocol:
transport: <_SelectorSocketTransport fd=21>
Traceback (most recent call last):
File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/selector_events.py", line 761, in write
n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor
00:33:57.654 ERROR Fatal error on SSL transport
protocol:
transport: <_SelectorSocketTransport closing fd=21>
During handling of the above exception, another exception occurred:
File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/sslproto.py", line 646, in _process_write_backlog
self._transport.write(chunk)
File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/selector_events.py", line 765, in write
self._fatal_error(exc, 'Fatal write error on socket transport')
File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/selector_events.py", line 645, in _fatal_error
self._force_close(exc)
File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/selector_events.py", line 657, in _force_close
self._loop.call_soon(self._call_connection_lost, exc)
File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 574, in call_soon
self._check_closed()
File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 357, in _check_closed
raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
00:33:57.656 ERROR Task was destroyed but it is pending!
task: wait_for=()]> cb=[()]>
00:33:57.659 ERROR Task was destroyed but it is pending!
task: wait_for= wait_for=()]> cb=[()]>>
```

I wrote a close_websocket_conn function but does not seems to work

```
def websocket_close_conn():
    """Close a websocket connection.
    """
    pending = asyncio.Task.all_tasks()
    count=0
    for task in pending:     
        task.cancel()
        with suppress(asyncio.CancelledError):
            asyncio.get_event_loop().run_until_complete(task)
            count +=1
    execution.logger.info('The count for pending task is: ' + str(count))    
    asyncio.get_event_loop().stop()
    asyncio.get_event_loop().close()
    step_message = 'closing websocket connection....' 
    execution.logger.info(step_message)   
    is_closed = asyncio.get_event_loop().is_closed()    
    check_connection = 'Checking whether the websocket event loop is closed? ' + str(is_closed)
    # _capture_or_add_step(step_message, False)
    asyncio.Future().cancel()
    is_cancelled = asyncio.Future().cancelled()   
    execution.logger.info('The future is cancelled? ' + str(is_cancelled)) 
    execution.logger.info(check_connection)
```

**Comment by aaugustin** [comment]
We exchanged some private emails. I think close / wait_closed aren't being used correctly. Narrowing down the error is likely to show that websockets isn't at fault.
