### ISSUE TITLE
Run "Hello World" example Failed in Python3.7

### ISSUE THREAD

**Issue by ppaanngggg** [aaugustin/websockets#442]
I try to run the client example in website [https://websockets.readthedocs.io/en/stable/#](url).

The code:

```python
#!/usr/bin/env python

import asyncio
import websockets

async def hello(uri):
    async with websockets.connect(uri) as websocket:
        await websocket.send("Hello world!")

asyncio.get_event_loop().run_until_complete(
    hello('ws://localhost:8765'))
```

Then I get the error like this:

```text
Traceback (most recent call last):
  File "client.py", line 9, in <module>
    hello('ws://localhost:8765'))
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "client.py", line 5, in hello
    async with websockets.connect(uri) as websocket:
  File "/usr/local/lib/python3.7/site-packages/websockets/client.py", line 390, in __aenter__
    return (yield from self)
  File "/usr/local/lib/python3.7/site-packages/websockets/client.py", line 397, in __await__
    transport, protocol = yield from self._creating_connection
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
sys:1: RuntimeWarning: coroutine 'BaseEventLoop.create_connection' was never awaited
```

**Comment by aaugustin** [comment]
Python 3.7 isn't supported yet.

**Comment by aaugustin** [comment]
Version 6.0 adds support for Python 3.7 and is now available on PyPI: https://pypi.org/project/websockets/6.0/#files

**Comment by ppaanngggg** [comment]
Awesome! Many thank you!
