### ISSUE TITLE
Improve error messages during HTTP parsing

### ISSUE THREAD

**Issue by aaugustin** [aaugustin/websockets#494]
For example, if the remote endpoint closes the connection without sending a HTTP response, currently this results in:

```
Traceback (most recent call last):
  File "/Users/myk/dev/websockets/src/websockets/client.py", line 90, in read_http_response
    status_code, headers = yield from read_response(self.reader)
  File "/Users/myk/dev/websockets/src/websockets/http.py", line 122, in read_response
    status_line = yield from read_line(stream)
  File "/Users/myk/dev/websockets/src/websockets/http.py", line 196, in read_line
    raise ValueError("Line without CRLF")
ValueError: Line without CRLF

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "issue-338-client.py", line 20, in <module>
    loop.run_until_complete(echo())
  File "/Users/myk/.pyenv/versions/3.7.0/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "issue-338-client.py", line 11, in echo
    async with websockets.connect("ws://localhost:8765") as websocket:
  File "/Users/myk/dev/websockets/src/websockets/py35/client.py", line 2, in __aenter__
    return await self
  File "/Users/myk/dev/websockets/src/websockets/py35/client.py", line 20, in __await_impl__
    extra_headers=protocol.extra_headers,
  File "/Users/myk/dev/websockets/src/websockets/client.py", line 283, in handshake
    status_code, response_headers = yield from self.read_http_response()
  File "/Users/myk/dev/websockets/src/websockets/client.py", line 92, in read_http_response
    raise InvalidMessage("Malformed HTTP message") from exc
websockets.exceptions.InvalidMessage: Malformed HTTP message
```

which isn't enlightening.

**Comment by aaugustin** [comment]
With the patch, the same situation produces:

```
Traceback (most recent call last):
  File "/Users/myk/dev/websockets/src/websockets/http.py", line 149, in read_response
    status_line = await read_line(stream)
  File "/Users/myk/dev/websockets/src/websockets/http.py", line 235, in read_line
    raise EOFError("Line without CRLF")
EOFError: Line without CRLF

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/myk/dev/websockets/src/websockets/client.py", line 100, in read_http_response
    status_code, reason, headers = await read_response(self.reader)
  File "/Users/myk/dev/websockets/src/websockets/http.py", line 151, in read_response
    raise EOFError("Connection closed while reading HTTP status line") from exc
EOFError: Connection closed while reading HTTP status line

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "example/client.py", line 19, in <module>
    asyncio.get_event_loop().run_until_complete(hello())
  File "/Users/myk/.pyenv/versions/3.7.3/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "example/client.py", line 10, in hello
    async with websockets.connect(uri) as websocket:
  File "/Users/myk/dev/websockets/src/websockets/client.py", line 501, in __aenter__
    return await self
  File "/Users/myk/dev/websockets/src/websockets/client.py", line 528, in __await_impl__
    extra_headers=protocol.extra_headers,
  File "/Users/myk/dev/websockets/src/websockets/client.py", line 293, in handshake
    status_code, response_headers = await self.read_http_response()
  File "/Users/myk/dev/websockets/src/websockets/client.py", line 102, in read_http_response
    raise InvalidMessage("did not receive a valid HTTP response") from exc
websockets.exceptions.InvalidMessage: did not receive a valid HTTP response
```
