### ISSUE TITLE
websockets requires Python >= 3.4 when installin on Python 3.5.3

### ISSUE THREAD

**Issue by evlo** [aaugustin/websockets#523]
websockets requires Python >= 3.4.

```
Collecting websockets (from hbmqtt)
  Using cached https://files.pythonhosted.org/packages/4b/c6/026da2eeed75a49dd0b72a0c7ed6ee5cb2943e396ca9753eabff7359b27b/websockets-5.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-HWInX6/websockets/setup.py", line 24, in <module>
        raise Exception("websockets requires Python >= 3.4.")
    Exception: websockets requires Python >= 3.4.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-HWInX6/websockets/
root@DietPi:~# python3 --version
Python 3.5.3
```

```
root@DietPi:~# pip -V
pip 18.1 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)
```

So I  guess I need something like pip3?

**Comment by lgrahl** [comment]
Yes, you need to use pip3... or consider [using a virtual environment](https://docs.python.org/3/tutorial/venv.html).
