### ISSUE TITLE
Pyinstaller isssues when generating package with websockets

### ISSUE THREAD

**Issue by androzo** [aaugustin/websockets#529]
I'm trying to generate a package using:

pyinstaller.exe -F --clean --hidden-import=win32timezone ".\operations\myservice.py"

But when installing windows service there is no issue, only when I run it, my requirements.txt has the websockets==7.0 line and I'm using tox to compile, there is no error at all.

```
Traceback (most recent call last):
  File "lib\site-packages\win32\lib\win32serviceutil.py", line 839, in SvcRun
  File "myservice.py", line 26, in SvcDoRun
  File "c:\git\device-services\.tox\py36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "services.py", line 13, in <module>
  File "c:\git\device-services\.tox\py36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "device_services\api\__init__.py", line 5, in <module>
  File "c:\git\device-services\.tox\py36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "device_services\api\rpc_api.py", line 23, in <module>
  File "c:\git\device-services\.tox\py36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "device_services\api\transport\socket_server.py", line 5, in <module>
ModuleNotFoundError: No module named 'websockets'

The message resource is present but the message was not found in the message table\
```

I appreciate any help,

**Comment by aaugustin** [comment]
This looks more like an issue with your packaging toolchain than with websockets itself.
