### ISSUE TITLE
running from django

### ISSUE THREAD

**Issue by Six-wars** [aaugustin/websockets#546]
I'm trying to run this websocket script from django

    async def get_cells(websocket, path):
	  async for message in websocket:

		message = json.loads(message)
		...
				if percentage % 5 == 0:
					await websocket.send(json.dumps({'complete': False, 'status': percentage}))
        ...

			await websocket.send(json.dumps({'complete': True, 'filename': filename}))

asyncio.get_event_loop().run_until_complete(
	websockets.serve(get_cells, 'localhost', 8765))
	
asyncio.get_event_loop().run_forever()

I've saved is as path.py and in the urls imported it

    import path
    
It's throwing this error

    ^C(pixelart) sam@sam-Lenovo-G51-35:~/code/pixelart$ python manage.py runserver
    Performing system checks...

    Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f38e007f1e0>
    Traceback (most recent call last):
    File "/home/sam/code/envs/pixelart/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
        fn(*args, **kwargs)
    File "/home/sam/code/envs/pixelart/lib/python3.6/site-packages/django/core/management/commands/runserver.py",line 117, in inner_run
        self.check(display_num_errors=True)
    File "/home/sam/code/envs/pixelart/lib/python3.6/site-packages/django/core/management/base.py", line 379, in check
        include_deployment_checks=include_deployment_checks,
    File "/home/sam/code/envs/pixelart/lib/python3.6/site-packages/django/core/management/base.py", line 366, in _run_checks
        return checks.run_checks(**kwargs)
    File "/home/sam/code/envs/pixelart/lib/python3.6/site-packages/django/core/checks/registry.py", line 71, in run_checks
        new_errors = check(app_configs=app_configs)
    File "/home/sam/code/envs/pixelart/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
        return check_resolver(resolver)
    File "/home/sam/code/envs/pixelart/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
        return check_method()
    File "/home/sam/code/envs/pixelart/lib/python3.6/site-packages/django/urls/resolvers.py", line 396, in check
        for pattern in self.url_patterns:
    File "/home/sam/code/envs/pixelart/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
        res = instance.__dict__[self.name] = self.func(instance)
    File "/home/sam/code/envs/pixelart/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
        patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
    File "/home/sam/code/envs/pixelart/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
        res = instance.__dict__[self.name] = self.func(instance)
    File "/home/sam/code/envs/pixelart/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
        return import_module(self.urlconf_name)
    File "/home/sam/code/envs/pixelart/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 994, in _gcd_import
    File "<frozen importlib._bootstrap>", line 971, in _find_and_load
    File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 678, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/home/sam/code/pixelart/pixelart/urls.py", line 7, in <module>
        import path
    File "/home/sam/code/pixelart/path.py", line 55, in <module>
        asyncio.get_event_loop().run_until_complete(
    File "/usr/lib/python3.6/asyncio/events.py", line 694, in get_event_loop
        return get_event_loop_policy().get_event_loop()
    File "/usr/lib/python3.6/asyncio/events.py", line 602, in get_event_loop
        % threading.current_thread().name)
    RuntimeError: There is no current event loop in thread 'Dummy-1'.

**Comment by lgrahl** [comment]
I'm quite sure this is not a websockets-related issue. But can you provide an example script where this can be reproduced?

**Comment by Six-wars** [comment]
thanks, it's not a websocket issue more of an implementation hitch from my end.

Here's the code for the websocket https://gist.github.com/Six-wars/56d2ba174d6c8a695ee582a547e6298f

and the urls.py where it's imported from the main urls file

https://gist.github.com/Six-wars/c76f9f8bbd8a678c7a49c69361e01656

in case you'd prefer to view the entire repo since this belong to a project I've licenced under GNU licence it's available on github: https://github.com/Six-wars/pixelart

**Comment by aaugustin** [comment]
asyncio initializes an event loop in the main thread by default. It doesn't initialize an event loop in other threads.

You're using Django's development server which starts the server in a thread for its autoreloading functionality and also runs each request it its own thread.

You need to initialize an event loop in each thread where you're using it e.g.:

```python
try:
    loop = asyncio.get_event_loop()
except RuntimeError:
    loop = asyncio.new_event_loop()

loop.run_until_complete(...)
```

You might want to look at Django Channels, the official way of using websockets with Django.

**Comment by Six-wars** [comment]
Thanks, I've tried to implement it this way since it based on my code on running multiple sockets...

```
try:
	loop = asyncio.get_event_loop().run_until_complete(
    	websockets.serve(router, 'localhost', 8765))
except RuntimeError:
	loop = asyncio.new_event_loop().run_until_complete(
    	websockets.serve(router, 'localhost', 8765))

loop.get_event_loop().run_forever()
```

I throws this error

```
(pixelart) sam@sam-Lenovo-G51-35:~/code/pixelart$ python path.py
Traceback (most recent call last):
  File "path.py", line 153, in <module>
    loop.get_event_loop().run_forever()
AttributeError: 'WebSocketServer' object has no attribute 'get_event_loop'
```

since this isn't intended for a site going live I'm considering your repo has the upper hand being simpler to understand and implement

**Comment by aaugustin** [comment]
You need:

```python
loop = asyncio.new_event_loop()
loop.run_until_complete(websockets.serve(router, 'localhost', 8765))

# do more things with loop
```

Your code does:

```
loop = asyncio.new_event_loop()
loop = loop.run_until_complete(websockets.serve(router, 'localhost', 8765))

# loop is now the result of awaiting websockets.serve, which isn't what you intend
```
