### ISSUE TITLE
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes - unclear error reporting

### ISSUE THREAD

**Issue by vgoklani** [aaugustin/websockets#579]
I'm not sure how to fix this error:

      Traceback (most recent call last):
        File "/root/src/streamer/stocks_producer.py", line 44, in <module>
          main()
        File "/root/src/streamer/stocks_producer.py", line 40, in main
          streamer.start()
        File "/root/src/streamer/polygon_streamer.py", line 67, in start
          self.loop.run_until_complete(asyncio.gather(*tasks))
        File "uvloop/loop.pyx", line 1451, in uvloop.loop.Loop.run_until_complete
        File "/root/src/streamer/polygon_streamer.py", line 47, in connect
          raise Exception(error_message)
      Exception: resetting connection: ()
      103 - 2019-02-13 15:30:14,095 - streamer.polygon_streamer - ERROR - resetting connection: ('WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason',)
      Traceback (most recent call last):
        File "/opt/conda/lib/python3.7/site-packages/websockets/protocol.py", line 528, in transfer_data
          msg = yield from self.read_message()
        File "/opt/conda/lib/python3.7/site-packages/websockets/protocol.py", line 580, in read_message
          frame = yield from self.read_data_frame(max_size=self.max_size)
        File "/opt/conda/lib/python3.7/site-packages/websockets/protocol.py", line 645, in read_data_frame
          frame = yield from self.read_frame(max_size)
        File "/opt/conda/lib/python3.7/site-packages/websockets/protocol.py", line 710, in read_frame
          extensions=self.extensions,
        File "/opt/conda/lib/python3.7/site-packages/websockets/framing.py", line 100, in read
          data = yield from reader(2)
        File "/opt/conda/lib/python3.7/asyncio/streams.py", line 677, in readexactly
          raise IncompleteReadError(incomplete, n)
      asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

here is my code snippet, thank you!

	async def connect(self):
		while True:
			async with websockets.connect(self.url, max_queue=8 * 2**10,) as websocket:
				await websocket.send(json.dumps({"action": "auth", "params": self._api_key}))
				await websocket.send(json.dumps({"action": "subscribe", "params": self._symbols_str}))
				log.info("connected: {}".format(websocket.remote_address))
				while(True):
					try:
						message_str = await asyncio.wait_for(websocket.recv(), timeout=self._timeout)
						# await self.queue.put(message_str)
						self.queue.put_nowait(message_str)
					except asyncio.TimeoutError:
						log.warn("timeout error - no data in {} seconds, pinging connection".format(self._timeout))
						pong_waiter = await asyncio.wait_for(websocket.ping(data="keepalive"), timeout=self._timeout)
						await asyncio.wait_for(pong_waiter, timeout=2 * self._timeout)
						log.warn('ping/pong received, keeping connection alive...')
					except Exception as e:
						error_message = "resetting connection: {}".format(e.args)
						log.error(error_message)
						raise Exception(error_message)

**Comment by aaugustin** [comment]
The remote endpoint closed the connection summarily.

I believe you aren't the first person to be confused by this exception. Perhaps we could make it more user-friendly.

**Comment by vgoklani** [comment]
Thanks for the reply!
How would I validate that the remote endpoint closed the connection? 

I spoke with the vendor, and he claims that the issue is on our end. 

I also had this same error when pulling data from coinbase, and they also said that  the error was on our end.

**Comment by lgrahl** [comment]
Wouldn't this be a case for reporting [status code 1006](https://tools.ietf.org/html/rfc6455#section-7.4.1)?

**Comment by aaugustin** [comment]
Well there's this in the report (line breaks added)

```
   103 - 2019-02-13 15:30:14,095 - streamer.polygon_streamer - ERROR - resetting connection: 
        ('WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason',)
```

So the error 1006 is reported.

That said many websockets users aren't familiar with close codes and won't know what 1006 means.

**Comment by vgoklani** [comment]
thanks for the response @lgrahl  and @aaugustin 

would it be possible that the remote closed the connection because the server wasn't processing the requests fast enough? i set the  max_queue=8 * 2**10 which should be sufficient (?)

is there a way to get additional logging around the error? 

btw, no more bitcoin stuff (it's crashing anyway)

**Comment by aaugustin** [comment]
This may help: https://websockets.readthedocs.io/en/stable/cheatsheet.html#debugging

**Comment by lgrahl** [comment]
It looks like this exception sometimes fires into a void. From our production servers:

```
Time:      2019-04-04 11:25:55
Level:     ERROR
Channel:   asyncio
File:      /usr/lib/python3.7/collections/__init__.py:414
Module:    collections
Function:  _replace

Message:

Future exception was never retrieved
future: <Future finished exception=ConnectionClosed('WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason')>
Traceback (most recent call last):
  File "/var/venv/saltyrtc-server/lib/python3.7/site-packages/websockets/protocol.py", line 674, in transfer_data
    message = yield from self.read_message()
  File "/var/venv/saltyrtc-server/lib/python3.7/site-packages/websockets/protocol.py", line 742, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "/var/venv/saltyrtc-server/lib/python3.7/site-packages/websockets/protocol.py", line 815, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "/var/venv/saltyrtc-server/lib/python3.7/site-packages/websockets/protocol.py", line 884, in read_frame
    extensions=self.extensions,
  File "/var/venv/saltyrtc-server/lib/python3.7/site-packages/websockets/framing.py", line 99, in read
    data = yield from reader(2)
  File "/usr/lib/python3.7/asyncio/streams.py", line 677, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
```

**Comment by gslusarek-cic** [comment]
any updates here?

I've got the same issue during connection to server in google cloud so I wonder is it ingress fault (connection through regular nginx works like a charm)

here is the log


> 2019-07-01 15:51:20,838 websockets.protocol DEBUG    client - state = CONNECTING
2019-07-01 15:51:20,856 websockets.protocol DEBUG    client - event = connection_made(<asyncio.sslproto._SSLProtocolTransport object at 0x10f416978>)
2019-07-01 15:51:20,993 websockets.protocol DEBUG    client - state = OPEN
2019-07-01 15:51:41,000 websockets.protocol DEBUG    client > Frame(fin=True, opcode=9, data=b'5u$\x80', rsv1=False, rsv2=False, rsv3=False)
2019-07-01 15:51:41,118 websockets.protocol DEBUG    client < Frame(fin=True, opcode=10, data=b'5u$\x80', rsv1=False, rsv2=False, rsv3=False)
2019-07-01 15:51:41,118 websockets.protocol DEBUG    client - received solicited pong: 35752480
2019-07-01 15:51:42,490 websockets.protocol DEBUG    client < Frame(fin=True, opcode=9, data=b'QUoi', rsv1=False, rsv2=False, rsv3=False)
2019-07-01 15:51:42,490 websockets.protocol DEBUG    client - received ping, sending pong: 51556f69
2019-07-01 15:51:42,490 websockets.protocol DEBUG    client > Frame(fin=True, opcode=10, data=b'QUoi', rsv1=False, rsv2=False, rsv3=False)
2019-07-01 15:51:50,992 websockets.protocol DEBUG    client - event = eof_received()
2019-07-01 15:51:50,993 websockets.protocol DEBUG    client ! failing WebSocket connection in the OPEN state: 1006 [no reason]
2019-07-01 15:51:50,994 websockets.protocol DEBUG    client - event = connection_lost(None)
2019-07-01 15:51:50,994 websockets.protocol DEBUG    client - state = CLOSED
2019-07-01 15:51:50,994 websockets.protocol DEBUG    client x code = 1006, reason = [no reason]
2019-07-01 15:51:50,995 agent        ERROR    Connection error!
Traceback (most recent call last):
`
  File "/Users/xxxx/.virtualenvs/aaa-PdF-yTXF/lib/python3.7/site-packages/websockets/protocol.py", line 674, in transfer_data
    message = yield from self.read_message()
  File "/Users/xxx/.pyenv/versions/3.7.3/lib/python3.7/asyncio/coroutines.py", line 58, in __next__
    return self.gen.send(None)
  File "/Users/xxx/.virtualenvs/aaa-PdF-yTXF/lib/python3.7/site-packages/websockets/protocol.py", line 742, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "/Users/xxx/.pyenv/versions/3.7.3/lib/python3.7/asyncio/coroutines.py", line 58, in __next__
    return self.gen.send(None)
  File "/Users/xxx/.virtualenvs/aaa-PdF-yTXF/lib/python3.7/site-packages/websockets/protocol.py", line 815, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "/Users/xxx/.pyenv/versions/3.7.3/lib/python3.7/asyncio/coroutines.py", line 58, in __next__
    return self.gen.send(None)
  File "/Users/xxx/.virtualenvs/aaa-PdF-yTXF/lib/python3.7/site-packages/websockets/protocol.py", line 884, in read_frame
    extensions=self.extensions,
  File "/Users/xxx/.pyenv/versions/3.7.3/lib/python3.7/asyncio/coroutines.py", line 58, in __next__
    return self.gen.send(None)
  File "/Users/xxx/.virtualenvs/aaa-PdF-yTXF/lib/python3.7/site-packages/websockets/framing.py", line 99, in read
    data = yield from reader(2)
  File "/Users/xxx/.pyenv/versions/3.7.3/lib/python3.7/asyncio/streams.py", line 677, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes`

**Comment by aaugustin** [comment]
I'm not sure which circumstances produce this. It requires investigating.

A deterministic way to reproduce the error would be most helpful, but I know it's an ambitious thing to ask...

**Comment by aaugustin** [comment]
@gslusarek-cic The TCP connection drops after 30 seconds exactly: it opens at 15:51:20,993 and  closes at 15:51:50,992. This can't be an accident. It looks like you're connecting through something that doesn't allow long-lived HTTP connections. 30 seconds is a very common threshold is such cases.

----

@vgoklani If you're able to turn on debug logs like gslusarek-cic did, we could get a hint. Otherwise, if you don't believe me, you can inspect network traffic with wireshark and check that you receive a TCP FIN or RST.

----

@lgrahl Unlike the two other situations discussed here which are on the client side, you are on the server side. I'm going to move it to a separate issue.

----

To sup up, possible next steps on this ticket include:

1. figuring out why this traceback is printed: it should only be recorded in `transfer_data_exc` and added as the `__cause__` of a `ConnectionClosed` exception.
2. clarifying the error report in that case
3. explaining that situation in the FAQ

**Comment by aaugustin** [comment]
This is the same as #624 but on the other side of the connection.

**Comment by aaugustin** [comment]
I don't understand why you're getting truncated tracebacks.

When I try to reproduce thiserror, I get:

```
Traceback (most recent call last):
  File "/Users/myk/dev/websockets/src/websockets/protocol.py", line 768, in transfer_data
    message = await self.read_message()
  File "/Users/myk/dev/websockets/src/websockets/protocol.py", line 836, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/myk/dev/websockets/src/websockets/protocol.py", line 911, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/myk/dev/websockets/src/websockets/protocol.py", line 984, in read_frame
    extensions=self.extensions,
  File "/Users/myk/dev/websockets/src/websockets/framing.py", line 125, in read
    data = await reader(2)
  File "/Users/myk/.pyenv/versions/3.7.3/lib/python3.7/asyncio/streams.py", line 679, in readexactly
    await self._wait_for_data('readexactly')
  File "/Users/myk/.pyenv/versions/3.7.3/lib/python3.7/asyncio/streams.py", line 473, in _wait_for_data
    await self._waiter
  File "/Users/myk/.pyenv/versions/3.7.3/lib/python3.7/asyncio/selector_events.py", line 801, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 54] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "example/secure_client.py", line 27, in <module>
    asyncio.get_event_loop().run_until_complete(hello())
  File "/Users/myk/.pyenv/versions/3.7.3/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "example/secure_client.py", line 24, in hello
    greeting = await websocket.recv()
  File "/Users/myk/dev/websockets/src/websockets/protocol.py", line 460, in recv
    await self.ensure_open()
  File "/Users/myk/dev/websockets/src/websockets/protocol.py", line 744, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
```

**Comment by gslusarek-cic** [comment]
@aaugustin You were right about that 30s connection drop is not an accident, it was done by google load balancer, which just cut connection after default timeout. Thanks for the help finding the issue.

The only thing that bothers me that `Connect` class specify both ping and pong timeouts and as I understand, this tasks are for check or maintain websockets connections. So since there is a traffic on websocket channels why google loadbalancer has cut the connection? Will try to find the answer for that.

**Comment by aaugustin** [comment]
Probably because it isn't designed for long running connections, just for short HTTP requests.

**Comment by xiandong79** [comment]
I also had this same error when pulling data from coinbase

**Comment by snenkov** [comment]
Have you discovered a solution to this? I still have this persisting issue.

**Comment by e0003315** [comment]
Receive the same error as above. Had to restart my program frequently. It will be good if there is fix.

**Comment by MRGLabs** [comment]
Any new findings/fixes regarding this issue? I observe the frequency of these exceptions increases when I perform more processing on each receive, and also when there is heavier server (websocket message) traffic. By playing with the buffer size, ping times, and minimizing receive processing that blocks the asyncio event loop I've been able to reduce the frequency of these exceptions to a tolerable level (for me that's once or twice per 24 hours) but I'd really like to eliminate them completely (they cause data drops which adversely impact some machine learning I'm doing).

I would love to know if it's strictly a server-side issue for me at this point, or if my asyncio event loop processing still needs more optimization.

Here is a relevant traceback:

```
Traceback (most recent call last):
  File ".../venv/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File ".../venv/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File ".../venv/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File ".../venv/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File ".../venv/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 737, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File '...'
    async for msg in ws:
  File ".../venv/lib/python3.8/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File ".../venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File ".../venv/lib/python3.8/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

```

**Comment by simaiden** [comment]
> Any new findings/fixes regarding this issue? I observe the frequency of these exceptions increases when I perform more processing on each receive, and also when there is heavier server (websocket message) traffic. By playing with the buffer size, ping times, and minimizing receive processing that blocks the asyncio event loop I've been able to reduce the frequency of these exceptions to a tolerable level (for me that's once or twice per 24 hours) but I'd really like to eliminate them completely (they cause data drops which adversely impact some machine learning I'm doing).
> 
> I would love to know if it's strictly a server-side issue for me at this point, or if my asyncio event loop processing still needs more optimization.
> 
> Here is a relevant traceback:
> 
> ```
> Traceback (most recent call last):
>   File ".../venv/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
>     message = await self.read_message()
>   File ".../venv/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
>     frame = await self.read_data_frame(max_size=self.max_size)
>   File ".../venv/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
>     frame = await self.read_frame(max_size)
>   File ".../venv/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
>     frame = await Frame.read(
>   File ".../venv/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
>     data = await reader(2)
>   File "/usr/lib/python3.8/asyncio/streams.py", line 737, in readexactly
>     raise exceptions.IncompleteReadError(incomplete, n)
> asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File '...'
>     async for msg in ws:
>   File ".../venv/lib/python3.8/site-packages/websockets/protocol.py", line 439, in __aiter__
>     yield await self.recv()
>   File ".../venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
>     await self.ensure_open()
>   File ".../venv/lib/python3.8/site-packages/websockets/protocol.py", line 803, in ensure_open
>     raise self.connection_closed_exc()
> websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
> ```

Hi, can you share your websocket connection parameters? 

Thanks

**Comment by MRGLabs** [comment]
@simaiden 

```
websockets.connect(uri, ping_interval=13, ping_timeout=30, max_queue=10000)
```

**Comment by QGB** [comment]
serve subprotocols 
js ` new WebSocket('ws://' + location.host + '/ws',['tty']) `

cause python
`asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes`

**Comment by zeckem19** [comment]
having the same issue on google loadbalancer, changed the backend timeout and the disconnection still happens at the frequency of the new timeout.

**Comment by pseudotensor** [comment]
I can easily reproduce this issue when hitting gradio server with >32 simultaneous requests, say 64.  Then about 1/3 first hits (using pytest -n 64) always fail with this error.

```
Exception in ASGI application
Traceback (most recent call last):
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 959, in transfer_data
    message = await self.read_message()
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1029, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1104, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1161, in read_frame
    frame = await Frame.read(
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/data/conda/h2ogpt/lib/python3.10/asyncio/streams.py", line 706, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 247, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/starlette/middleware/cors.py", line 75, in __call__
    await self.app(scope, receive, send)
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/starlette/routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/starlette/routing.py", line 82, in app
    await func(session)
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/fastapi/routing.py", line 325, in app
    await dependant.call(**values)
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/gradio/routes.py", line 564, in join_queue
    await asyncio.wait_for(
  File "/data/conda/h2ogpt/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/starlette/websockets.py", line 173, in send_json
    await self.send({"type": "websocket.send", "text": text})
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/starlette/websockets.py", line 85, in send
    await self._send(message)
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in sender
    await send(message)
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 320, in asgi_send
    await self.send(data)  # type: ignore[arg-type]
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 647, in send
    await self.write_frame(True, opcode, data)
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1205, in write_frame
    await self.drain()
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1194, in drain
    await self.ensure_open()
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 935, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
Exception in ASGI application
```


The server that I'm reaching out to doesn't have an errors at all, so I think it is client side.
