### ISSUE TITLE
Document sending multiple messages

### ISSUE THREAD

**Issue by mikehooper** [aaugustin/websockets#591]
Please could a complete example be added to the documentation for opening a websocket, sending multiple messages then closing the websocket. The following is the best that I could come up with, however it throws 'WebSocket connection is closed: code = 1000 (OK), no reason'. How can this be handled cleanly?

```
# Client
import asyncio,websockets,time

async def hello():
    async with websockets.connect('ws://localhost:8765') as websocket:
        for i in range(1,4):
            await websocket.send(str(i))
            print("send > {}".format(str(i)))
            time.sleep(1)
         
asyncio.get_event_loop().run_until_complete(hello())
```

```
send > 1
send > 2
send > 3
```

```
# Server
import asyncio,websockets

async def hello(websocket, path):
    while True:
        text = await websocket.recv()
        print("receive < {}".format(text))

start_server = websockets.serve(hello, 'localhost', 8765)
asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()

```

```
receive < 1
receive < 2
receive < 3
Error in connection handler
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/websockets/server.py", line 169, in handler
    yield from self.ws_handler(self, path)
  File "wsserver3.py", line 6, in hello
    text = await websocket.recv()
  File "/home/pi/.local/lib/python3.5/site-packages/websockets/protocol.py", line 434, in recv
    yield from self.ensure_open()
  File "/home/pi/.local/lib/python3.5/site-packages/websockets/protocol.py", line 658, in ensure_open
    ) from self.transfer_data_exc
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000 (OK), no reason
```

**Comment by aaugustin** [comment]
```python
async def hello(websocket, path):
    async for text in websocket:
        print("receive < {}".format(text))
```

Besides, don't use `time.sleep`, use `asyncio.sleep` instead.

**Comment by mikehooper** [comment]
That throws a TypeError:

```
Error in connection handler
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/websockets/server.py", line 169, in handler
    yield from self.ws_handler(self, path)
  File "wsserver3.py", line 5, in hello
    async for text in websocket:
TypeError: 'async for' requires an object with __aiter__ method, got WebSocketServerProtocol

```

**Comment by aaugustin** [comment]
Perhaps you aren't using the latest versions of Python and websockets.

```python
async def hello(websocket, path):
    while True:
        try:
            text = await websocket.recv()
        except websockets.ConnectionClosed:
            break
        print("receive < {}".format(text))
```

**Comment by mikehooper** [comment]
Yes, should have mentioned I'm on Python 3.5.3 (on a Raspberry Pi). I came to the same result - and the documentation does state it throws a ConnectionClosed. Thanks for your help.

```
async def hello(websocket, path):
    while True:
        try:
            text = await websocket.recv()
        except websockets.ConnectionClosed as e:
            if e.code == 1000:
                break
            else:
                raise e
        print("receive < {}".format(text))
```
