### ISSUE TITLE
I always encounter this abnormality. How can I solve it? Thank you.

### ISSUE THREAD

**Issue by xnys** [aaugustin/websockets#595]
[2019-04-10 14:14:39,305 DEBUG websockets.server] Invalid handshake
Traceback (most recent call last):
  File "/usr/zb/.local/lib/python3.6/site-packages/websockets/server.py", line 213, in read_http_request
    path, headers = yield from read_request(self.reader)
  File "/usr/zb/.local/lib/python3.6/site-packages/websockets/http.py", line 80, in read_request
    request_line = yield from read_line(stream)
  File "/usr/zb/.local/lib/python3.6/site-packages/websockets/http.py", line 196, in read_line
    raise ValueError("Line without CRLF")
ValueError: Line without CRLF

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/zb/.local/lib/python3.6/site-packages/websockets/server.py", line 117, in handler
    extra_headers=self.extra_headers,
  File "/usr/zb/.local/lib/python3.6/site-packages/websockets/server.py", line 467, in handshake
    path, request_headers = yield from self.read_http_request()
  File "/usr/zb/.local/lib/python3.6/site-packages/websockets/server.py", line 215, in read_http_request
    raise InvalidMessage("Malformed HTTP message") from exc
websockets.exceptions.InvalidMessage: Malformed HTTP message

**Comment by aaugustin** [comment]
Usually this means the server closed the connection without sending anything in response to the websocket handshake request.

The error reporting needs to be improved in this case. This is #494.
