### ISSUE TITLE
Pass event loop explicitly to all asyncio objects

### ISSUE THREAD

**Issue by SzieberthAdam** [aaugustin/websockets#60]
Python: 3.4
OS: Windows 7 (Firewall turned off)
Virtual environment was used (pyvenv).

Server code:

```python
#!/usr/bin/env python

import asyncio
import threading
import websockets

@asyncio.coroutine
def hello(websocket, path):
    name = yield from websocket.recv()
    print("< {}".format(name))
    greeting = "Hello {}!".format(name)
    yield from websocket.send(greeting)
    print("> {}".format(greeting))

class ServerThread(threading.Thread):

  def run(self):
    self.loop = asyncio.new_event_loop()
    coro = websockets.serve(hello, 'localhost', 8765,
                            loop=self.loop)
    self.loop.run_until_complete(coro)
    self.loop.run_forever()

ServerThread().start()
```

Exception traceback in client.py (documentation example code):

```
Traceback (most recent call last):
  File "C:\tajf\lib\site-packages\websockets\client.py", line 61, in handshake
    status_code, headers = yield from read_response(self.reader)
  File "C:\tajf\lib\site-packages\websockets\http.py", line 63, in read_response

    status_line, headers = yield from read_message(stream)
  File "C:\tajf\lib\site-packages\websockets\http.py", line 80, in read_message
    start_line = yield from read_line(stream)
  File "C:\tajf\lib\site-packages\websockets\http.py", line 99, in read_line
    line = yield from stream.readline()
  File "c:\Python34_32bit\lib\asyncio\streams.py", line 425, in readline
    yield from self._wait_for_data('readline')
  File "c:\Python34_32bit\lib\asyncio\streams.py", line 393, in _wait_for_data
    yield from self._waiter
  File "c:\Python34_32bit\lib\asyncio\futures.py", line 386, in __iter__
    yield self  # This tells Task to wait for completion.
  File "c:\Python34_32bit\lib\asyncio\tasks.py", line 287, in _wakeup
    value = future.result()
  File "c:\Python34_32bit\lib\asyncio\futures.py", line 275, in result
    raise self._exception
  File "c:\Python34_32bit\lib\asyncio\selector_events.py", line 662, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "client.py", line 15, in <module>
    asyncio.get_event_loop().run_until_complete(hello())
  File "c:\Python34_32bit\lib\asyncio\base_events.py", line 316, in run_until_complete
    return future.result()
  File "c:\Python34_32bit\lib\asyncio\futures.py", line 275, in result
    raise self._exception
  File "c:\Python34_32bit\lib\asyncio\tasks.py", line 234, in _step
    result = coro.throw(exc)
  File "client.py", line 8, in hello
    websocket = yield from websockets.connect('ws://localhost:8765/')
  File "C:\tajf\lib\site-packages\websockets\client.py", line 124, in connect
    wsuri, origin=origin, subprotocols=subprotocols)
  File "C:\tajf\lib\site-packages\websockets\client.py", line 63, in handshake
    raise InvalidHandshake("Malformed HTTP message") from exc
websockets.exceptions.InvalidHandshake: Malformed HTTP message
Task was destroyed but it is pending!
task: <Task pending coro=<run() running at C:\tajf\lib\site-packages\websockets\protocol.py:232> wait_for=<Future pending cb=[Task._wakeup()]>>
```

Some other time it raises `ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host` with the same traceback.

**Comment by SzieberthAdam** [comment]
I added `loop=loop` to server.serve() | factory's arguments (which is a bug) but that did not solved the problem.

**Comment by SzieberthAdam** [comment]
Still i get `Exception in closing handshake: [WinError 10054] An existing connection was forcibly closed by the remote host` at server side by connecting multiple times with connect.py.

**Comment by aaugustin** [comment]
I made a commit yesterday that adds `yield from websocket.close()` to the client exemple (but I haven't redeployed the documentation yet). You're right on this front.

I'll keep this ticket open to pass the event loop around explicitly everywhere. I'm changing the title accordingly. (Previous title was " Server in a thread raises an exception in client side").

**Comment by SzieberthAdam** [comment]
Nice! I hope I did the job for you well.
Thanks for the module and keep up the good work!

**Comment by aaugustin** [comment]
@SzieberthAdam, I pull and squashed the two commits related to this issue in your repository. You should now be able to use the master branch from this repository instead of your fork. Please let me know if you run into any other issues. Thanks!

**Comment by SzieberthAdam** [comment]
Works nicely, thanks!
