### ISSUE TITLE
collections.abc should get imported explicitly

### ISSUE THREAD

**Issue by SzieberthAdam** [aaugustin/websockets#62]
Currently some of the failures of the unittests are involving that `abc` is not part of the `collections` module since version 3.3.

https://docs.python.org/3/library/collections.abc.html#module-collections.abc

“New in version 3.3: Formerly, this module was part of the collections module.”

```python
======================================================================
ERROR: test_protocol_custom_request_headers_list (websockets.test_client_server.SSLClientServerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adam/github/notmy/websockets/websockets/test_client_server.py", line 97, in test_protocol_custom_request_headers_list
    self.start_client('raw_headers', extra_headers=[('X-Spam', 'Eggs')])
  File "/home/adam/github/notmy/websockets/websockets/test_client_server.py", line 279, in start_client
    self.client = self.loop.run_until_complete(client)
  File "/usr/lib/python3.4/asyncio/base_events.py", line 316, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/home/adam/github/notmy/websockets/websockets/client.py", line 143, in connect
    extra_headers=extra_headers)
  File "/home/adam/github/notmy/websockets/websockets/client.py", line 53, in handshake
    if isinstance(extra_headers, collections.abc.Mapping):
AttributeError: 'module' object has no attribute 'abc'
```

`collections.abc` should get explicitly imported in `client.py` and `server.py`.

```python
…
import collections
import collections.abc
…
```

**Comment by aaugustin** [comment]
In fact, these modules should just `import collections.abc` instead of `import collections`.

**Comment by SzieberthAdam** [comment]
Well, I missed that. :)
