### ISSUE TITLE
Unexpected exception in keepalive ping task

### ISSUE THREAD

**Issue by sunqm** [aaugustin/websockets#625]
I came across an keepalive error that rarely happen. The code on server
```
import time
import asyncio
import websockets
from websockets.protocol import ConnectionClosed

async def ping(n):
    print('call ping at', time.asctime())
    time.sleep(float(n))

async def main(websocket, path):
    try:
        while True:
            n = await websocket.recv()
            response = await ping(n)
            await websocket.send(str(response))
    except ConnectionClosed:
        pass

loop = asyncio.get_event_loop()
start_server = websockets.serve(main, "localhost", 5000)
loop.run_until_complete(start_server)
loop.run_forever()
```

The code on client
```
import time
import asyncio
import websockets

async def main():
    async with websockets.connect('ws://localhost:5000') as ws:
        print('ping', time.asctime())
        await ws.send(str(10))
        await ws.recv()

loop = asyncio.get_event_loop()
loop.run_until_complete(asyncio.gather(loop.create_task(main()),
                                       loop.create_task(main())))
```

It raises an error on server
```
Unexpected exception in keepalive ping task
Traceback (most recent call last):
  File "/Users/qssun/Software/opt/miniconda3/3.7/lib/python3.7/site-packages/websockets/protocol.py", line 984, in keepalive_ping
    ping_waiter = yield from self.ping()
  File "/Users/qssun/Software/opt/miniconda3/3.7/lib/python3.7/site-packages/websockets/protocol.py", line 583, in ping
    yield from self.ensure_open()
  File "/Users/qssun/Software/opt/miniconda3/3.7/lib/python3.7/site-packages/websockets/protocol.py", line 658, in ensure_open
    ) from self.transfer_data_exc
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000 (OK), no reason
```

Python version 3.7.1
websockets version 7.0

**Comment by aaugustin** [comment]
Thanks for reporting this issue. Yes, I know, this is #551. I should really fix this. Use `ping_interval=None` until then.
