### ISSUE TITLE
Tests are broken on Python 3.8

### ISSUE THREAD

**Issue by Jenselme** [aaugustin/websockets#648]
From what I saw, many tests break on Python 3.8 beta (118 as time of writing) because new `DeprecationWarning` are raised. One I spotted is _class 'websockets.protocol.WebSocketCommonProtocol'> should be instaniated by asyncio internals only, please avoid its creation from user code_ which is not reported on Python 3.7. This causes the assertions on how many warnings are logged to fail.

I tested on the current `master` branch.

Since Python 3.8 is still in beta, I don't think this is urgent. I should be able to help on that if you want.

Original report: https://bugzilla.redhat.com/show_bug.cgi?id=1718208

**Comment by aaugustin** [comment]
https://bugs.python.org/issue24885 comes back and bites me here...

**Comment by aaugustin** [comment]
I asked for clarifications about these undocumented, backwards-incompatible changes in Python: https://bugs.python.org/issue37639

**Comment by Harmon758** [comment]
For reference, `StreamReaderProtocol` was removed from the documentation with https://github.com/python/cpython/commit/8be876e44b2dffb96b551029454cbfb16d697992 (https://bugs.python.org/issue33649, https://github.com/python/cpython/pull/9192) and backported to Python 3.7 with https://github.com/python/cpython/commit/512d7101098b971837cbb406942215244f636547 (https://github.com/python/cpython/pull/9377).

The `DeprecationWarning` was added with https://github.com/python/cpython/commit/ad4ed872415d00fcdfaa52a08108ec752b115000 (https://bugs.python.org/issue36806, https://github.com/python/cpython/pull/13101).

**Comment by StephenBrown2** [comment]
Here's a list of several DeprecationWarnings I've also seen, notably in the tests for [httpx on 3.8](https://travis-ci.org/encode/httpx/jobs/575060921), mostly about the [coroutine decorator](https://docs.python.org/3/library/asyncio-task.html#generator-based-coroutines):

<details><summary>

```
      4   /websockets/client.py
      1   /websockets/framing.py
      4   /websockets/http.py
     17   /websockets/protocol.py
      8   /websockets/server.py
```

```
     33  "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
      1  Using asyncio internal class StreamReaderProtocol is deprecated since Python 3.8  and scheduled for removal in Python 3.10
```

</summary>

```
  /websockets/framing.py:76: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def read(cls, reader, *, mask, max_size=None, extensions=None):

  /websockets/http.py:53: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def read_request(stream):

  /websockets/http.py:98: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def read_response(stream):

  /websockets/http.py:142: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def read_headers(stream):

  /websockets/http.py:182: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def read_line(stream):

  /websockets/protocol.py:58: DeprecationWarning: Using asyncio internal class StreamReaderProtocol is deprecated since Python 3.8  and scheduled for removal in Python 3.10
    class WebSocketCommonProtocol(asyncio.StreamReaderProtocol):

  /websockets/protocol.py:357: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def wait_closed(self):

  /websockets/protocol.py:370: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def recv(self):

  /websockets/protocol.py:447: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def send(self, data):

  /websockets/protocol.py:514: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def close(self, code=1000, reason=''):

  /websockets/protocol.py:564: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def ping(self, data=None):

  /websockets/protocol.py:603: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def pong(self, data=b''):

  /websockets/protocol.py:623: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def ensure_open(self):

  /websockets/protocol.py:665: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def transfer_data(self):

  /websockets/protocol.py:733: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def read_message(self):

  /websockets/protocol.py:804: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def read_data_frame(self, max_size):

  /websockets/protocol.py:875: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def read_frame(self, max_size):

  /websockets/protocol.py:890: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def write_frame(self, fin, opcode, data, *, _expected_state=State.OPEN):

  /websockets/protocol.py:941: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def write_close_frame(self, data=b''):

  /websockets/protocol.py:962: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def keepalive_ping(self):

  /websockets/protocol.py:1003: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def close_connection(self):

  /websockets/protocol.py:1068: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def wait_for_connection_lost(self):

  /websockets/client.py:61: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def write_http_request(self, path, headers):

  /websockets/client.py:77: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def read_http_response(self):

  /websockets/client.py:215: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def handshake(

  /websockets/client.py:443: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def __iter__(self):  # pragma: no cover

  /websockets/server.py:101: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def handler(self):

  /websockets/server.py:200: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def read_http_request(self):

  /websockets/server.py:223: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def write_http_response(self, status, headers, body=None):

  /websockets/server.py:243: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def process_request(self, path, request_headers):

  /websockets/server.py:436: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def handshake(

  /websockets/server.py:602: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def _close(self):

  /websockets/server.py:643: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def wait_closed(self):

  /websockets/server.py:837: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def __iter__(self):  # pragma: no cover
```

</details>

**Comment by bsergean** [comment]
I am running in prod now with python-3.8b4 and everything works well, fyi.

When I run tests I get this other warning btw.
```
  /xxx/cobra/venv/lib/python3.8/site-packages/websockets/server.py:722: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
    await asyncio.wait(
```

**Comment by jayvdb** [comment]
I am still encountering this Python 3.8.0~rc1 , with v8.0.2, and I dont see anything on master which would have fixed this.

https://github.com/aaugustin/websockets/compare/8.0.2...master

In addition to the deprecation warnings breaking the tests, there are two other failures I am encountering - same test method `test_server_shuts_down_during_connection_close` in two classes.

```py
======================================================================
FAIL: test_server_shuts_down_during_connection_close (tests.test_client_server.ClientServerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/abuild/rpmbuild/BUILD/websockets-8.0.2/tests/test_client_server.py", line 299, in stop_client
    self.loop.run_until_complete(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 608, in run_until_complete
    return future.result()
  File "/usr/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abuild/rpmbuild/BUILD/websockets-8.0.2/tests/test_client_server.py", line 114, in _decorate
    return func(self, *_args, **_kwargs)
  File "/usr/lib/python3.8/unittest/mock.py", line 1342, in patched
    return func(*newargs, **newkeywargs)
  File "/home/abuild/rpmbuild/BUILD/websockets-8.0.2/tests/test_client_server.py", line 1205, in test_server_shuts_down_during_connection_close
    self.assertEqual(reply, "Hello!")
  File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/home/abuild/rpmbuild/BUILD/websockets-8.0.2/tests/test_client_server.py", line 333, in temp_client
    yield
  File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/home/abuild/rpmbuild/BUILD/websockets-8.0.2/tests/test_client_server.py", line 101, in temp_test_client
    test.stop_client()
  File "/home/abuild/rpmbuild/BUILD/websockets-8.0.2/tests/test_client_server.py", line 303, in stop_client
    self.fail("Client failed to stop")
AssertionError: Client failed to stop

======================================================================
FAIL: test_server_shuts_down_during_connection_close (tests.test_client_server.SecureClientServerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/abuild/rpmbuild/BUILD/websockets-8.0.2/tests/test_client_server.py", line 299, in stop_client
    self.loop.run_until_complete(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 608, in run_until_complete
    return future.result()
  File "/usr/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abuild/rpmbuild/BUILD/websockets-8.0.2/tests/test_client_server.py", line 114, in _decorate
    return func(self, *_args, **_kwargs)
  File "/usr/lib/python3.8/unittest/mock.py", line 1342, in patched
    return func(*newargs, **newkeywargs)
  File "/home/abuild/rpmbuild/BUILD/websockets-8.0.2/tests/test_client_server.py", line 1205, in test_server_shuts_down_during_connection_close
    self.assertEqual(reply, "Hello!")
  File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/home/abuild/rpmbuild/BUILD/websockets-8.0.2/tests/test_client_server.py", line 333, in temp_client
    yield
  File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/home/abuild/rpmbuild/BUILD/websockets-8.0.2/tests/test_client_server.py", line 101, in temp_test_client
    test.stop_client()
  File "/home/abuild/rpmbuild/BUILD/websockets-8.0.2/tests/test_client_server.py", line 303, in stop_client
    self.fail("Client failed to stop")
AssertionError: Client failed to stop
```

**Comment by aaugustin** [comment]
@jayvdb This test no longer made sense since 7.0 I removed it.
