### ISSUE TITLE
ERROR:root:code = 1006 (connection closed abnormally [internal]), no reason

### ISSUE THREAD

**Issue by KasraAhmadi** [aaugustin/websockets#663]
I got this error when the client starts to send data to server. before sending data everything is fine.
How can i fix it? 
Thanks in advance

 ```
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), no reason')>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/websockets/protocol.py", line 796, in transfer_data
    message = await self.read_message()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/websockets/protocol.py", line 864, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/websockets/protocol.py", line 939, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/websockets/protocol.py", line 1019, in read_frame
    extensions=self.extensions,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/websockets/framing.py", line 121, in read
    data = await reader(2)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/streams.py", line 677, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes
The above exception was the direct cause of the following exception:
```

**Comment by aaugustin** [comment]
Please see https://websockets.readthedocs.io/en/stable/faq.html#what-does-connectionclosederror-code-1006-mean.
