### ISSUE TITLE
AttributeError: module 'http' has no attribute 'HTTPStatus'

### ISSUE THREAD

**Issue by CodeM01** [aaugustin/websockets#682]
I have tried to install and unistall the websockets module but whenever I import it, it throws an error. What do I need to do to stop this error?

I have tried to install and unistall the websockets module from pip install websockets and pip uninstall websockets.

Here is the error :

Traceback (most recent call last):
  File "C:\Users\x\PycharmProjects\NewProject\RawDiscordBot\client.py", line 1, in <module>
    import websockets
  File "C:\Users\x\AppData\Local\Programs\Python\Python37-32\lib\site-packages\websockets\__init__.py", line 3, in <module>
    from .auth import *
  File "C:\Users\x\AppData\Local\Programs\Python\Python37-32\lib\site-packages\websockets\auth.py", line 12, in <module>
    from .exceptions import InvalidHeader
  File "C:\Users\x\AppData\Local\Programs\Python\Python37-32\lib\site-packages\websockets\exceptions.py", line 294, in <module>
    class AbortHandshake(InvalidHandshake):
  File "C:\Users\x\AppData\Local\Programs\Python\Python37-32\lib\site-packages\websockets\exceptions.py", line 305, in AbortHandshake
    self, status: http.HTTPStatus, headers: HeadersLike, body: bytes = b""
AttributeError: module 'http' has no attribute 'HTTPStatus'
[Finished in 0.907s]

**Comment by aaugustin** [comment]
I suspect something is wrong with your Python installation.

What happens if, at the very beginning of your `client.py`, you add these lines?

```
import http
print(http.HTTPStatus.OK)
```

If you get the same crash, then it's definitely a problem with your Python installation.

**Comment by CodeM01** [comment]
Thank you for your reply,

It turns out that I made a rookie mistake of naming the module wrong; I am
reasonably new to programming

Thanks a lot!
