### ISSUE TITLE
Error code 1006

### ISSUE THREAD

**Issue by LanDeQuHuXi** [aaugustin/websockets#687]
Is there anyway to get more specific error messages?
My application is suffering from some abnormal close issues and the error message does not really help. 
This application has some heavy traffic, using DEBUG mode might not be a good idea.

**Version 8.0.2**

The error log is as follows:
**On server side**
```
2019-11-05 22:11:26,991 websocket.server.handler [ERROR]: 
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/websockets/protocol.py", line 795, in transfer_data
    message = await self.read_message()
  File "/root/.local/lib/python3.6/site-packages/websockets/protocol.py", line 863, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/root/.local/lib/python3.6/site-packages/websockets/protocol.py", line 938, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/root/.local/lib/python3.6/site-packages/websockets/protocol.py", line 1018, in read_frame
    extensions=self.extensions,
  File "/root/.local/lib/python3.6/site-packages/websockets/framing.py", line 121, in read
    data = await reader(2)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 672, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/server/__init__.py", line 60, in listen_streams
    await websocket.send(ujson.dumps(one_action))
  File "/root/.local/lib/python3.6/site-packages/websockets/protocol.py", line 530, in send
    await self.ensure_open()
  File "/root/.local/lib/python3.6/site-packages/websockets/protocol.py", line 771, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```
**On the client side:**
```
Unexpected exception in keepalive ping task
Traceback (most recent call last):
  File "/home/ec2-user/env/lib64/python3.7/site-packages/websockets/protocol.py", line 989, in keepalive_ping
    ping_waiter, self.ping_timeout, loop=self.loop
  File "/usr/lib64/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
Error in data transfer
Traceback (most recent call last):
  File "/home/ec2-user/env/lib64/python3.7/site-packages/websockets/protocol.py", line 674, in transfer_data
    message = yield from self.read_message()
  File "/home/ec2-user/env/lib64/python3.7/site-packages/websockets/protocol.py", line 742, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "/home/ec2-user/env/lib64/python3.7/site-packages/websockets/protocol.py", line 835, in read_data_frame
    yield from self.pong(frame.data)
  File "/home/ec2-user/env/lib64/python3.7/site-packages/websockets/protocol.py", line 614, in pong
    yield from self.ensure_open()
  File "/home/ec2-user/env/lib64/python3.7/site-packages/websockets/protocol.py", line 646, in ensure_open
    ) from self.transfer_data_exc
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
```

**Comment by aaugustin** [comment]
In case you haven't read it — https://websockets.readthedocs.io/en/stable/faq.html#what-does-connectionclosederror-code-1006-mean

There isn't much more than websockets can do. When a TCP connection drops, the application don't get any additional information it could surface to users.
