### ISSUE TITLE
Unable to unregister clients when using a queue based consumer/producer

### ISSUE THREAD

**Issue by hjpotter92** [aaugustin/websockets#700]
Taking inspiration from [this post][1], I built a small threaded websocket server:

```python
class WebsocketServer:
    def __init__(self, db_session=None):
        self.loop = asyncio.new_event_loop()
        self.db_session = db_session
        self.clients = set()

    def serve_forever(self):
        asyncio.set_event_loop(self.loop)
        server = websockets.serve(self.handler, '', Config.SERVER_PORT)
        print(f"Started websocket server on {Config.SERVER_PORT}")
        asyncio.get_event_loop().run_until_complete(server)
        asyncio.get_event_loop().run_forever()

    async def handler(self, websocket, path):
        print(f"Received websocket client on {path}")
        self.clients.add(websocket)
        loop = asyncio.get_event_loop()
        master = SessionService(websocket, self.db_session)
        await master.send_session()
        try:
            while True:
                listener_task = asyncio.ensure_future(master.get_message())
                producer_task = asyncio.ensure_future(master.produce())
                done, pending = await asyncio.wait(
                    [listener_task, producer_task],
                    return_when=asyncio.FIRST_COMPLETED,
                )
                if listener_task in done:
                    await master.consume()
                else:
                    listener_task.cancel()
                if producer_task in done:
                    if producer_task.result():
                        await master.send_message()
                else:
                    print("Cancelling producer")
                    producer_task.cancel()
        finally:
            self.clients.remove(websocket)
```

where `SessionService` class creates and maintains websocket sessions inside a db.

```python
class SessionService:
    def __init__(self, websocket, db):
        self.incoming = asyncio.Queue()
        self.outgoing = asyncio.Queue()
        self.ws = websocket
        self.db = db

    async def send_session(self):
        session = self._create_object(
            Session,
            ip_addr=self.ws.remote_address[0],
        )
        await self.ws.send(f'{{"session_id": "{session.id}"}}')

    async def get_message(self):
        self.incoming.append(self.ws.recv())

    async def send_message(self):
        self.ws.send(self.outgoing.pop(0))

    async def consume(self):
        self.outgoing.append(self.incoming.pop(0))

    async def produce(self):
        if self.outgoing:
            return True
```

In this, while new clients are getting added to the `clients` set, disconnected clients are not being removed.

Am I doing something wrong? I think this is due to the `while True:` block just inside my `try-finally` clause.

  [1]: https://stackoverflow.com/q/40723047/1190388

**Comment by aaugustin** [comment]
I'm not seeing an obvious problem with your code. Perhaps adding [debug logs](https://websockets.readthedocs.io/en/stable/cheatsheet.html#debugging) will help.

**Comment by hjpotter92** [comment]
Added debug logging, and also added print statements after the `self.clients.add/remove` operations:

```
Started websocket server on 12345
server - state = CONNECTING
server - event = connection_made(<_SelectorSocketTransport fd=8 read=idle write=<idle, bufsize=0>>)
server - event = data_received(<154 bytes>)
server < GET / HTTP/1.1
server < Headers([('Host', '127.0.0.1:12345'), ('Connection', 'Upgrade'), ('Upgrade', 'websocket'), ('Sec-WebSocket-Version', '13'), ('Sec-WebSocket-Key', 'D4oLihb5AiiXhDU126cAOw==')])
server > HTTP/1.1 101 Switching Protocols
server > Headers([('Upgrade', 'websocket'), ('Connection', 'Upgrade'), ('Sec-WebSocket-Accept', 'xNeNRQXyiQL31e2X8jvnzXjuoUg='), ('Date', 'Tue, 10 Dec 2019 06:53:50 GMT'), ('Server', 'Python/3.7 websockets/8.1')])
server - state = OPEN
Received websocket client on /
server > Frame(fin=True, opcode=1, data=b'{"session_id": "6e4b08b7-322c-4abb-bcbb-efa61ab54d05"}', rsv1=False, rsv2=False, rsv3=False)
{<websockets.server.WebSocketServerProtocol object at 0x7f1420817850>}
server - event = eof_received()
server ! failing OPEN WebSocket connection with code 1006
server - event = connection_lost(None)
server - state = CLOSED
server x code = 1006, reason = [no reason]
server x half-closing TCP connection
server - state = CONNECTING
server - event = connection_made(<_SelectorSocketTransport fd=8 read=idle write=<idle, bufsize=0>>)
server - event = data_received(<154 bytes>)
server < GET / HTTP/1.1
server < Headers([('Host', '127.0.0.1:12345'), ('Connection', 'Upgrade'), ('Upgrade', 'websocket'), ('Sec-WebSocket-Version', '13'), ('Sec-WebSocket-Key', 'rIJOurE7w7Y4hKZM8NC1Kw==')])
server > HTTP/1.1 101 Switching Protocols
server > Headers([('Upgrade', 'websocket'), ('Connection', 'Upgrade'), ('Sec-WebSocket-Accept', 'zt+VZ0S7IEGXwybU5fhqY09C2sY='), ('Date', 'Tue, 10 Dec 2019 06:54:05 GMT'), ('Server', 'Python/3.7 websockets/8.1')])
server - state = OPEN
Received websocket client on /
server > Frame(fin=True, opcode=1, data=b'{"session_id": "5191a502-73f4-4a84-9988-8ac9b161fb96"}', rsv1=False, rsv2=False, rsv3=False)
{<websockets.server.WebSocketServerProtocol object at 0x7f14207dac90>, <websockets.server.WebSocketServerProtocol object at 0x7f1420817850>}
server - event = eof_received()
server ! failing OPEN WebSocket connection with code 1006
server - event = connection_lost(None)
server - state = CLOSED
server x code = 1006, reason = [no reason]
server x half-closing TCP connection
```

**Comment by aaugustin** [comment]
Hrm, now I'm seeing the issue.

You aren't awaiting the recv() coroutine here:

```
    async def get_message(self):
        self.incoming.append(self.ws.recv())
```

As a consequence, `listener_task` doesn't raise a `ConnectionClosed` exception when the connection drops and you never exit the `while True: ...` loop.

**Comment by aaugustin** [comment]
(This isn't a bug in websockets.)

**Comment by hjpotter92** [comment]
I created an [MCVE][1]:

```python
import asyncio
from json import dumps, loads
from json.decoder import JSONDecodeError
from sys import exit
from threading import Thread

import websockets

import logging
logger = logging.getLogger('websockets')
logger.setLevel(logging.DEBUG)
logger.addHandler(logging.StreamHandler())


class Config:
    SERVER_PORT = 12345


class BaseService:
    def __init__(self, websocket, db_session):
        self.ws = websocket
        self.incoming = asyncio.Queue()
        self.outgoing = asyncio.Queue()
        self.db = db_session

    async def send_session(self):
        await self.ws.send('{"session_id": 1}')

    async def get_message(self):
        message = await self.ws.recv()
        try:
            message = loads(message)
        except JSONDecodeError:
            message = message
        print(f"Received {message} from connection")
        await self.incoming.put(message)

    async def send_message(self):
        message = await self.outgoing.get()
        if not isinstance(message, str):
            message = dumps(message)
        print("Sending message")
        await self.ws.send(message)

    async def consume(self):
        print('Consuming')

    async def produce(self):
        return not self.outgoing.empty()


class WebsocketServer:
    def __init__(self, db_session=None):
        self.loop = asyncio.new_event_loop()
        self.db_session = db_session
        self.clients = set()

    def serve_forever(self):
        asyncio.set_event_loop(self.loop)
        server = websockets.serve(self.handler, '', Config.SERVER_PORT)
        print(f"Started websocket server on {Config.SERVER_PORT}")
        asyncio.get_event_loop().run_until_complete(server)
        asyncio.get_event_loop().run_forever()

    async def handler(self, websocket, path):
        print(f"Received websocket client on {path}")
        self.clients.add(websocket)
        loop = asyncio.get_event_loop()
        master = BaseService(websocket, self.db_session)
        await master.send_session()
        try:
            print(self.clients)
            while True:
                listener_task = asyncio.ensure_future(master.get_message())
                producer_task = asyncio.ensure_future(master.produce())
                done, pending = await asyncio.wait(
                    [listener_task, producer_task],
                    return_when=asyncio.FIRST_COMPLETED,
                )
                if listener_task in done:
                    await master.consume()
                else:
                    listener_task.cancel()
                if producer_task in done:
                    if producer_task.result():
                        await master.send_message()
                else:
                    print("Cancelling producer")
                    producer_task.cancel()
        finally:
            self.clients.remove(websocket)
            print(self.clients)


if __name__ == '__main__':
    try:
        db_session = None
        sock = WebsocketServer(db_session)
        thread = Thread(target=sock.serve_forever)
        thread.daemon = True
        thread.start()
        thread.join()
    except KeyboardInterrupt:
        exit(0)
```

try running:

    docker run -p 12345:12345 hjpotter92/mcve

and then connect to the socket at `ws://localhost:12345`. When leaving the connection, it raises an exception:

```
Task exception was never retrieved
future: <Task finished coro=<BaseService.get_message() done, defined at server.py:29> exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), no reason')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/usr/local/lib/python3.7/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/usr/local/lib/python3.7/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/usr/local/lib/python3.7/site-packages/websockets/protocol.py", line 1051, in read_frame
    extensions=self.extensions,
  File "/usr/local/lib/python3.7/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/local/lib/python3.7/asyncio/streams.py", line 677, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "server.py", line 30, in get_message
    message = await self.ws.recv()
  File "/usr/local/lib/python3.7/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/usr/local/lib/python3.7/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

  [1]: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by aaugustin** [comment]
Catch the `ConnectionClosed` exception if you don't want to log it.

```python
while True:
   try:
       ...
    except ConnectionClosed:
        break
    finally:
        ...
```

**Comment by hjpotter92** [comment]
I did it slightly differently:

```python
while websocket.state.value is 1:
```

**Comment by aaugustin** [comment]
What about using public APIs rather than implementation details? ;-)

```python

while websocket.open:
   ...
```
