### ISSUE TITLE
Synchronous version of the websockets client 

### ISSUE THREAD

**Issue by ye** [aaugustin/websockets#71]
Thanks Aymeric for this great library. While [the WebSocket client example code](https://github.com/aaugustin/websockets/blob/master/example/client.py) works great in async fashion, I can't seem to get the `websocket.clients` to work in synchronous code. 

```python
import websockets
from flask import Flask
from flask_restful import Resource, Api

app = Flask(__name__)
api = Api(app)

class HelloWorld(Resource):
    def get(self):
        ws = websockets.client.connect('ws://localhost:8765')
        ws.send('Hello')
        response = ws.recv()
        return {'hello': response}

api.add_resource(HelloWorld, '/')

if __name__ == '__main__':
    app.run(debug=True)
```

I am actually getting a `TypeError: can't send non-None value to a just-started generator`
```
127.0.0.1 - - [25/Aug/2015 18:01:08] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/ye/.envs/py3k-flask/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/ye/.envs/py3k-flask/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/ye/.envs/py3k-flask/lib/python3.4/site-packages/flask_restful/__init__.py", line 261, in error_router
    return self.handle_error(e)
  File "/Users/ye/.envs/py3k-flask/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ye/.envs/py3k-flask/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ye/.envs/py3k-flask/lib/python3.4/site-packages/flask_restful/__init__.py", line 261, in error_router
    return self.handle_error(e)
  File "/Users/ye/.envs/py3k-flask/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ye/.envs/py3k-flask/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/ye/.envs/py3k-flask/lib/python3.4/site-packages/flask_restful/__init__.py", line 430, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/ye/.envs/py3k-flask/lib/python3.4/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/ye/.envs/py3k-flask/lib/python3.4/site-packages/flask_restful/__init__.py", line 520, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/ye/dev/temp/flask-restful-ws.py", line 11, in get
    ws.send('Hello')
TypeError: can't send non-None value to a just-started generator
```

So my question is, is it possible to use a synchronous fashion to use `websockets.client` APIs? Assuming that's a no, how would I integration the websockets client api into a non-async webapp like Flask? I am having a hard time figuring out how to get the event loop embedded into an existing web app. It would be great to another example to use `websockets.client` APIs, thanks!

**Comment by aaugustin** [comment]
Well, the downside of explicit async programming (the model chosen by asyncio) is that it's hard to combine with sync programming...

Technically you can wrap every call to a `websockets` coroutine in `asyncio.get_event_loop().run_until_complete` but you'll get synchronous execution, which means no concurrency (and your code will look bad).

If you want to run in the same process as a synchronous web framework such as Flask with decent concurrency, you need an implicit async framework such as gevent.

Searching for "flask gevent websockets" should turn up libraries more suitable to you use case.

**Comment by ye** [comment]
@aaugustin thanks for the insight and direction guidance! I came across [a very thoughtful blog post](http://python-notes.curiousefficiency.org/en/latest/pep_ideas/async_programming.html) about explicit vs. implicit async programming in Python by @ncoghlan, which is very helpful for me to understand better about this topic.

Also, perhaps [`aiohttp`](https://github.com/KeepSafe/aiohttp) or [`Flask Async`](https://github.com/mrdon/flask/) is more suitable in my use case to integrate with `websockets`?

**Comment by aaugustin** [comment]
aiohttp has its own built-in websockets API so that's one option.

If you want to stick with Flask you con try [flask-sockets](https://github.com/kennethreitz/flask-sockets).

**Comment by ye** [comment]
:+1:
