### ISSUE TITLE
AttributeError: module 'websockets' has no attribute 'send'

### ISSUE THREAD

**Issue by sxv** [aaugustin/websockets#715]
Fresh install. Trying out the browser example:
```
#!/usr/bin/env python

# WS server that sends messages at random intervals

import asyncio
import datetime
import random
import websockets

async def time(websocket, path):
    while True:
        now = datetime.datetime.utcnow().isoformat() + "Z"
        await websockets.send(now)
        await asyncio.sleep(random.random() * 3)

start_server = websockets.serve(time, "127.0.0.1", 5678)

asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()
```

When webpage is loaded, server fails with:

```
python serverws.py 
Error in connection handler
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/websockets/server.py", line 191, in handler
    await self.ws_handler(self, path)
  File "serverws.py", line 11, in time
    await websockets.send(now)
AttributeError: module 'websockets' has no attribute 'send'
```

I confirmed that this attribute / function doesn't exist manually in the command-line. Ideas?

**Comment by aaugustin** [comment]
This line should read `await websocket.send(...)`.

`websocket` is the first argument received by your connection handler.
