### ISSUE TITLE
Block forever if connection closed then try to reconnect

### ISSUE THREAD

**Issue by zmrenwu** [aaugustin/websockets#716]
1. Connecting to an echo server: ws://demos.kaazing.com/echo
2. Sending message and receive back periodically
3. Turning off the Internet, therefore connection to ws://demos.kaazing.com/echo closed
4. Disconnection detected and try to restart above task
5. Recover the internet connection
6. Block forever at `await close()` or `await connect()` (if skip await close()).

Let me show you a simple example:

```python
import asyncio
import logging
import random
import websockets

logger = logging.getLogger("websockets")
logger.setLevel(logging.DEBUG)
logger.addHandler(logging.StreamHandler())


class ReconnectExample:
    def __init__(self):
        self.sock = None
        self.uri = "ws://demos.kaazing.com/echo"
        self.consume_task = None

    async def connect(self):
        self.sock = await websockets.connect(self.uri, close_timeout=3)
        logger.info("Connect -> %s successfully.", self.uri)

    async def consume(self):
        try:
            while True:
                await self.sock.send("hello " + str(random.randint(1, 100)))
                msg = await self.sock.recv()
                print(msg)
                await asyncio.sleep(3)
        except websockets.ConnectionClosedError as e:
            logger.exception(e)
            logger.info("Detect websocket connection closed, restating...")

            cnt = 3
            while cnt > 0:
                try:
                    await asyncio.wait_for(self.restart(), timeout=5)
                    break
                except asyncio.TimeoutError:
                    logger.debug("Restarting failed, retry (%s times left)", cnt)
                    cnt -= 1

    async def start(self):
        await self.connect()
        self.consume_task = asyncio.create_task(self.consume())
        logger.info("Started!")

    async def stop(self):
        try:
            self.consume_task.cancel()
        except asyncio.CancelledError:
            logger.debug("Consume task has already been cancelled.")
        # await self.sock.close()
        logger.info("Stopped!")

    async def restart(self):
        await self.stop()
        await self.start()
        logger.info("Restarted!")


if __name__ == "__main__":
    app = ReconnectExample()
    loop = asyncio.get_event_loop()
    loop.set_debug(True)

    try:
        loop.create_task(app.start())
        loop.run_forever()
    except Exception as e:
        print(e)
    finally:
        loop.close()

```

The debug logs:
```
client - state = CONNECTING
client - event = connection_made(<_SelectorSocketTransport fd=648 read=idle write=<idle, bufsize=0>>)
client > GET /echo HTTP/1.1
client > Headers([('Host', 'demos.kaazing.com'), ('Upgrade', 'websocket'), ('Connection', 'Upgrade'), ('Sec-WebSocket-Key', 'XyaKAATatv8patdukWrdfQ=='), ('Sec-WebSocket-Version', '13'), ('Sec-WebSocket-Extensions', 'permessage-deflate; client_max_window_bits'), ('User-Agent', 'Python/3.7 websockets/8.1')])
client - event = data_received(<201 bytes>)
client < HTTP/1.1 101 Web Socket Protocol Handshake
client < Headers([('Connection', 'Upgrade'), ('Date', 'Wed, 08 Jan 2020 13:07:14 GMT'), ('Sec-WebSocket-Accept', 'b3QRd3fV+zebEMJDbEb+14lTdw0='), ('Server', 'Kaazing Gateway'), ('Upgrade', 'websocket')])
client - state = OPEN
Connect -> ws://demos.kaazing.com/echo successfully.
Started!
client > Frame(fin=True, opcode=1, data=b'hello 59', rsv1=False, rsv2=False, rsv3=False)
hello 59
client - event = data_received(<10 bytes>)
client < Frame(fin=True, opcode=1, data=b'hello 59', rsv1=False, rsv2=False, rsv3=False)
client > Frame(fin=True, opcode=1, data=b'hello 36', rsv1=False, rsv2=False, rsv3=False)
client - event = data_received(<10 bytes>)
hello 36
client < Frame(fin=True, opcode=1, data=b'hello 36', rsv1=False, rsv2=False, rsv3=False)
client > Frame(fin=True, opcode=1, data=b'hello 49', rsv1=False, rsv2=False, rsv3=False)
client - event = data_received(<10 bytes>)
client < Frame(fin=True, opcode=1, data=b'hello 49', rsv1=False, rsv2=False, rsv3=False)
hello 49
client > Frame(fin=True, opcode=1, data=b'hello 53', rsv1=False, rsv2=False, rsv3=False)
client > Frame(fin=True, opcode=9, data=b'+\xa9j7', rsv1=False, rsv2=False, rsv3=False)
client - event = connection_lost([WinError 10054] An existing connection was forcibly closed by the remote host)
client - state = CLOSED
client x code = 1006, reason = [no reason]
client - aborted pending ping: 2ba96a37
client ! failing CLOSED WebSocket connection with code 1006
code = 1006 (connection closed abnormally [internal]), no reason
Traceback (most recent call last):
  File "C:\Users\user\.virtualenvs\intella-yEnSJRcR\lib\site-packages\websockets\protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "C:\Users\user\.virtualenvs\intella-yEnSJRcR\lib\site-packages\websockets\protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "C:\Users\user\.virtualenvs\intella-yEnSJRcR\lib\site-packages\websockets\protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "C:\Users\user\.virtualenvs\intella-yEnSJRcR\lib\site-packages\websockets\protocol.py", line 1051, in read_frame
    extensions=self.extensions,
  File "C:\Users\user\.virtualenvs\intella-yEnSJRcR\lib\site-packages\websockets\framing.py", line 105, in read
    data = await reader(2)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\Lib\asyncio\streams.py", line 679, in readexactly
    await self._wait_for_data('readexactly')
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\Lib\asyncio\streams.py", line 473, in _wait_for_data
    await self._waiter
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\Lib\asyncio\selector_events.py", line 804, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/user/SpaceLocal/Workspace/L_Work/intella/intella/reconnect_test.py", line 25, in consume
    msg = await self.sock.recv()
  File "C:\Users\user\.virtualenvs\intella-yEnSJRcR\lib\site-packages\websockets\protocol.py", line 509, in recv
    await self.ensure_open()
  File "C:\Users\user\.virtualenvs\intella-yEnSJRcR\lib\site-packages\websockets\protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
Detect websocket connection closed, restating...
Stopped!
(blocked at await self.connect() forever)
```

Looks like `await asyncio.wait_for(self.restart(), timeout=5)` doesn't throw the TimeoutError.
```
            while cnt > 0:
                try:
                    await asyncio.wait_for(self.restart(), timeout=5)
                    break
                except asyncio.TimeoutError:
                    logger.debug("Restarting failed, retry (%s times left)", cnt)
                    cnt -= 1
```
The expected behavior is restart the app after recovering the internet connection or failed after 3 times retrying.
What's the problem, I have no idea how to debug it.

**Comment by aaugustin** [comment]
There's a problem with the logic in your script.

`loop.create_task(app.start())` runs `start()` in a task. Let's call it task 1.

`self.consume_task = asyncio.create_task(self.consume())` runs `consume()` in a task. Let's call it task 2. At this point `start()` returns and task 1 exits.

`await asyncio.wait_for(self.restart(), timeout=5)` runs `restart()` in a task. Let's call it task 3.

`restart()` calls `stop()`, which calls `self.consume_task.cancel()`, which kills task 2.

Furthermore, cancelling `wait_for` cancels the task it's waiting for, which kills task 3.

At this point you've cancelled all your tasks which is why your script hangs.

Modify your script as follows to see for yourself:

```python
                try:
                    await asyncio.wait_for(self.restart(), timeout=5)
                    break
                # add the next three lines
                except asyncio.CancelledError:
                    logger.critical("Oops, I committed seppuku")
                    raise
                except asyncio.TimeoutError:
                    logger.debug("Restarting failed, retry (%s times left)", cnt)
                    cnt -= 1
```

**Comment by aaugustin** [comment]
I agree that this is hard to debug, but it's really an issue about asyncio, not an issue about websockets. If you were using plain TCP connections you'd have the same problem.
