### ISSUE TITLE
Enabling debugging increase the message size

### ISSUE THREAD

**Issue by adriansev** [aaugustin/websockets#724]
Hi! Is is expected that the enabling the debug mode for websocket would increase the message size? I have a situation for a quite big answer that i can receive without problem but with debugging enabled i get this:    
``` 
DEBUG:websockets.protocol:client - event = data_received(<8196 bytes>)
DEBUG:websockets.protocol:client - event = data_received(<8196 bytes>)
DEBUG:websockets.protocol:client ! failing OPEN WebSocket connection with code 1009
DEBUG:websockets.protocol:client - state = CLOSING
DEBUG:websockets.protocol:client > Frame(fin=True, opcode=8, data=b'\x03\xf1', rsv1=False, rsv2=False, rsv3=False)
DEBUG:websockets.protocol:client ! timed out waiting for TCP close
DEBUG:websockets.protocol:client x closing TCP connection
DEBUG:websockets.protocol:client ! timed out waiting for TCP close
DEBUG:websockets.protocol:client x aborting TCP connection
DEBUG:websockets.protocol:client - event = connection_lost(None)
DEBUG:websockets.protocol:client - state = CLOSED
DEBUG:websockets.protocol:client x code = 1006, reason = [no reason]
ERROR:root:code = 1006 (connection closed abnormally [internal]), no reason
Traceback (most recent call last):
  File "/home/adrian/.local/lib/python3.7/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/adrian/.local/lib/python3.7/site-packages/websockets/protocol.py", line 950, in read_message
    frame = await self.read_data_frame(max_size=max_size)
  File "/home/adrian/.local/lib/python3.7/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/adrian/.local/lib/python3.7/site-packages/websockets/protocol.py", line 1051, in read_frame
    extensions=self.extensions,
  File "/home/adrian/.local/lib/python3.7/site-packages/websockets/framing.py", line 127, in read
    f"payload length exceeds size limit ({length} > {max_size} bytes)"
websockets.exceptions.PayloadTooBig: payload length exceeds size limit (8192 > 0 bytes)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/adrian/bin/alien.py", line 1159, in SendMsg_json
    result = await wb.recv()
  File "/home/adrian/.local/lib/python3.7/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/adrian/.local/lib/python3.7/site-packages/websockets/protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
DEBUG:root:SendMsg_json:: Websocket connection was closed while waiting the answer. Either network problem or ALIENPY_TIMEOUT should be set >20s
DEBUG:root:WB ping failed!!!
ERROR:root:code = 1006 (connection closed abnormally [internal]), no reason
```
Any idea why debugging would increase the message size? (i had 16MiB, going to 17 solved the problem). Can i monitor/record the message sizes that the client receive?
Thank you!

**Comment by aaugustin** [comment]
`(8192 > 0 bytes)` suggests that you set `max_size` to `0`. This doesn't work. Try `None` instead.

**Comment by adriansev** [comment]
not really, initially it was 16 MiB and now is 20 MiB see https://github.com/adriansev/jalien_py/blob/master/xjalienfs/alien.py#L1335

**Comment by aaugustin** [comment]
Are you able to add some debug logs around the point where PayloadTooBig is raised, to check the value of max_size there? Perhaps it's just a problem with the log message, or perhaps websockets lost the proper value of max_size somewhere.

**Comment by aaugustin** [comment]
Since the discussion has stalled a few months ago, I'll close this issue now.

**Comment by adriansev** [comment]
yeah, sorry, i just had to make things work and i increased the max_size until problems went away. also, if i'm the only reporter/observer of such a problems i will assume by default that the problem is mine :). Thanks!
