### ISSUE TITLE
Assigning websocket to anything but localhost throws errno 99

### ISSUE THREAD

**Issue by LinuxRocks2000** [aaugustin/websockets#733]
I am working on a simple websocket server to run in parallel with a socket server, for a very basic web app. I have written an HTML site, programmed the socket server, and all that, but when I run the websocket server (regardless of whether or not the socket server was running) it gives me this error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1062, in create_server
    sock.bind(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/awesome/desk/programs/python_dnd_server/mywebsocketserver.py", line 15, in <module>
    asyncio.get_event_loop().run_until_complete(server)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/lib/python3.6/asyncio/tasks.py", line 537, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/awesome/.local/lib/python3.6/site-packages/websockets/server.py", line 965, in __await_impl__
    server = await self._create_server()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1066, in create_server
    % (sa, err.strerror.lower()))
OSError: [Errno 99] error while attempting to bind on address ('2600:1700:8000:ff00:ab7b:cc80:d82d:e6f2', 2344, 0, 0): cannot assign requested address
```
Here is my websocket server code:
```
import asyncio
import json
import websockets
configfile=open("config.json")
config=json.loads(configfile.read())
configfile.close()
tick=0
print("This is a websocket server only. Run the actual server to push html data.")
print(config["address"])
async def system(websocket,path):
    print("Run")
    async for x in websocket:
        await websocket.send_all(x)
server=websockets.serve(system,config["address"],2344)
asyncio.get_event_loop().run_until_complete(server)
asyncio.get_event_loop().run_forever()
```

Thanks, from LinuxRocks2000!

**Comment by hilbix** [comment]
This has nothing to do with `websocket`, this is just a pure low level networking problem.

**It looks like `2600:1700:8000:ff00:ab7b:cc80:d82d:e6f2` is none of your local addresses**.  Check:

    ip a s | fgrep -- 2600:1700:8000:ff00:ab7b:cc80:d82d:e6f2 || echo NOPE && echo YAY

Example `service.py` for Ubuntu 18.04:

```
# Ubuntu Bionic: Python 3.6 and websockets 3.4
import sys
import logging
import asyncio
import websockets

log     = logging.getLogger('websockets.server')
log.setLevel(logging.DEBUG)
log.addHandler(logging.StreamHandler())

async def service(ws,pth):
        log.debug('client %s for %s', ws.remote_address, pth)
        while ws.open:
                data    = await ws.recv()
                log.debug('client %s echo %s', ws.remote_address, data)
                await ws.send(data)

serv    = websockets.serve(service, sys.argv[1], int(sys.argv[2]))
serv    = asyncio.get_event_loop().run_until_complete(serv)

log.debug('serving %s', [x.getsockname() for x in serv.server.sockets])
asyncio.get_event_loop().run_forever()
```

Running it:

```
$ python3 service.py '*' 2222
serving [('::', 2222, 0, 0), ('0.0.0.0', 2222)]
client ('127.0.0.1', 49128) for /hurz
client ('127.0.0.1', 49128) echo huhu
client ('127.0.0.1', 49128) closed: WebSocket connection is closed: code = 1006, no reason.
client ('192.168.0.2', 56606) for /hurz
client ('192.168.0.2', 56606) echo huhu
client ('192.168.0.2', 56606) closed: WebSocket connection is closed: code = 1006, no reason.
client ('2a01:1a1a:1c1c:1a1a::1', 47444, 0, 0) for /hurz
client ('2a01:1a1a:1c1c:1a1a::1', 47444, 0, 0) echo huhu
client ('2a01:1a1a:1c1c:1a1a::1', 47444, 0, 0) closed: WebSocket connection is closed: code = 1006, no reason.
```

Works perfectly.

```
$ python3 service.py 2a01:1c1c:1c1c:1c1c::1 2222
serving [('2a01:1c1c:1c1c:1c1c::1', 2222, 0, 0)]
```

Works, too.  But this does not work (as I do not have the address):

```
$ python3 service.py 2600:1700:8000:ff00:ab7b:cc80:d82d:e6f2 2222                                                                              
Traceback (most recent call last):                                                          
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1062, in create_server             
    sock.bind(sa)                                                                           
OSError: [Errno 99] Cannot assign requested address                                         

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "service.py", line 23, in <module>
    serv        = asyncio.get_event_loop().run_until_complete(serv)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/lib/python3.6/asyncio/tasks.py", line 537, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/usr/lib/python3/dist-packages/websockets/py35/server.py", line 20, in __await__
    return (yield from self.server)
  File "/usr/lib/python3/dist-packages/websockets/server.py", line 531, in serve
    server = yield from loop.create_server(factory, host, port, **kwds)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1066, in create_server
    % (sa, err.strerror.lower()))
OSError: [Errno 99] error while attempting to bind on address ('2600:1700:8000:ff00:ab7b:cc80:d82d:e6f2', 2222, 0, 0): cannot assign requested address
```

> Note: Changed my local IP addresses for safety.

**Comment by aaugustin** [comment]
Please reopen if something works with asyncio's [create_server](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.create_server) but doesn't work with websockets.
