### ISSUE TITLE
Websocket handshake fails with "did not receive a valid HTTP response"

### ISSUE THREAD

**Issue by nardew** [aaugustin/websockets#741]
Hello,

I am facing an issue I cannot get around. While initiating a websocket connection, the handshake fails with error specified below (the error is related to a specific websocket endpoint, other endpoints work). Interestingly enough, when I try to open the connection via other clients (I tried a chrome extension and online websocket.org), the connection is opened properly, hence I assume the issue on the client side. On the other hand, the exception says the connection was reset by peer. I analyzed the request headers between `websockets` and the other client and they more or less matched. I even tried to match them 1:1 (where applicable) using `extra_headers` but to no avail.

Thanks for any help.

websockets 8.1
Python 3.7.5
MacOS Catalyna 10.15.4 (19E266), same for AmazonLinux

`client - state = CONNECTING
client - event = connection_made(<_SelectorSocketTransport fd=9 read=idle write=<idle, bufsize=0>>)
client > GET /spotWS HTTP/1.1
client > Headers([('Host', 'ws.btse.com'), ('Upgrade', 'websocket'), ('Connection', 'Upgrade'), ('Sec-WebSocket-Key', 'PDwE3zjU2jM1MoMNQBVRIg=='), ('Sec-WebSocket-Version', '13'), 
('User-Agent', 'Python/3.7 websockets/8.1')])
client - event = connection_lost([Errno 54] Connection reset by peer)
client - state = CLOSED
client x code = 1006, reason = [no reason]

...

Traceback (most recent call last):
  File "../lib/python3.7/site-packages/websockets/client.py", line 101, in read_http_response
    status_code, reason, headers = await read_response(self.reader)
  File "../lib/python3.7/site-packages/websockets/http.py", line 139, in read_response
    status_line = await read_line(stream)
  File "../lib/python3.7/site-packages/websockets/http.py", line 213, in read_line
    line = await stream.readline()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/streams.py", line 496, in readline
    line = await self.readuntil(sep)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/streams.py", line 588, in readuntil
    await self._wait_for_data('readuntil')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/streams.py", line 473, in _wait_for_data
    await self._waiter
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/selector_events.py", line 804, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 54] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
...  
File "/Users/nardew/Development/python_venv/cryptolib/lib/python3.7/site-packages/websockets/client.py", line 519, in __aenter__
    return await self
  File "/Users/nardew/Development/python_venv/cryptolib/lib/python3.7/site-packages/websockets/client.py", line 549, in __await_impl__
    extra_headers=protocol.extra_headers,
  File "/Users/nardew/Development/python_venv/cryptolib/lib/python3.7/site-packages/websockets/client.py", line 292, in handshake
    status_code, response_headers = await self.read_http_response()
  File "/Users/nardew/Development/python_venv/cryptolib/lib/python3.7/site-packages/websockets/client.py", line 105, in read_http_response
    raise InvalidMessage("did not receive a valid HTTP response") from exc
websockets.exceptions.InvalidMessage: did not receive a valid HTTP response`

**Comment by aaugustin** [comment]
Sorry, I can't help: https://websockets.readthedocs.io/en/stable/contributing.html#bitcoin-users

**Comment by nardew** [comment]
Hi aaugistin, while I respect your decision since I was asking for free support, I just want to recommend to you to read about blockchain because for some unknown reason you are mixing it with bitcoin. Learning always helps. It's a pity your neat library cannot reach broader audience just because you tag them as 'bitcoin-users'  based on imaginary/false premises.

**Comment by thomasleveil** [comment]
@nardew you might be affected by #743

Could you see if you still have that error if you remove cookies from the request ?

**Comment by aaugustin** [comment]
I'm fully aware that blockchain != bitcoin and of attempts at reducing the energy consumption of cryptocurrencies. I'm just bored of explaining.

Happy to revisit when the energy consumed by the average cryptocurrency transaction is less than 2x the energy consumed by the average credit card transaction.

**Comment by aaugustin** [comment]
In fact there's already a fix: 4f1964295ad0e81c8c96b99c3fe9dafc96f11f28 — it's just waiting for a release.

**Comment by nardew** [comment]
@thomasleveil The application in question is a client and it does not send out any cookies, see the headers at the beginning of the issue. Or maybe I just misunderstood your point.

**Comment by nardew** [comment]
In case anyone stumbles over it and it is complete show stopper for her/him, `websockets` can be replaced to some extent by `aiohttp` (https://aiohttp.readthedocs.io/en/v0.18.2/client_websockets.html). This is applicable only for *clients* and of course you lose all bells and whistles of `websockets`. In my case it helped.
