### ISSUE TITLE
Are there any recommended approaches for queuing websockets? websockets.exceptions.ConnectionClosedOK: code = 1000 (OK), no reason

### ISSUE THREAD

**Issue by animesh-sharama** [aaugustin/websockets#748]
I have a question regarding storing multiple websockets in a queue and then processing those websockets.

Below is the code
```
import asyncio
import logging
import os

import websockets

logging.basicConfig(level=logging.INFO)


class Server:
    my_queue = asyncio.Queue()

    async def register(self, websocket):
        await self.my_queue.put(websocket)
        logging.info(f'{websocket.remote_address} connects.')
        if self.my_queue.qsize() >= 3:
            while not self.my_queue.empty():
                websocket = await self.my_queue.get()
                await websocket.send('Welcome 3 clients')

    async def unregister(self, websocket):
        if websocket.closed:
            logging.info(f'{websocket.remote_address} disconnects.')

    async def process(self):
        pass

    async def ws_handler(self, websocket, path):
        await self.register(websocket)
        try:
            await self.process()
        finally:
            await self.unregister(websocket)


asyncio.get_event_loop().run_until_complete(
    websockets.serve(Server().ws_handler, 'localhost', int(os.environ['PORT'])))
print('server started at port:', os.environ['PORT'])
asyncio.get_event_loop().run_forever()

```
When I run the server I keep on getting the error
```
ERROR:websockets.server:Error in connection handler
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/websockets/server.py", line 191, in handler
    await self.ws_handler(self, path)
  File "tmp.py", line 30, in ws_handler
    try:
  File "tmp.py", line 20, in register
  File "/usr/local/lib/python3.7/dist-packages/websockets/protocol.py", line 555, in send
    await self.ensure_open()
  File "/usr/local/lib/python3.7/dist-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: code = 1000 (OK), no reason
```
Looking into the exception code [doc](https://github.com/aaugustin/websockets/issues/new)
didn't helped much, it works well with one client the problem starts when I starting queuing them up?

Is there any recommended approaches for queuing websockets?

**Comment by aaugustin** [comment]
In `process`, you're returning immediately, so you're unregistering sockets right after registering them.

You should wait (e.g. `await asyncio.sleep(1000)`) or do something else that doesn't return immediately.
