### ISSUE TITLE
Getting "root" cause of connection close

### ISSUE THREAD

**Issue by ctlaltdefeat** [aaugustin/websockets#761]
When using a client that terminates due to a ping timeout (and perhaps other issues, they're more difficult to reproduce), the ```ConnectionClosedError``` just has code 1006 instead of the "root" cause:

```
2020-05-15 16:39:49,846 DEBUG client > Frame(fin=True, opcode=9, data=b'$\x99W\xf7', rsv1=False, rsv2=False, rsv3=False)
client ! timed out waiting for pong
2020-05-15 16:39:49,847 DEBUG client ! timed out waiting for pong
client ! failing OPEN WebSocket connection with code 1011
2020-05-15 16:39:49,847 DEBUG client ! failing OPEN WebSocket connection with code 1011
client - state = CLOSING
2020-05-15 16:39:49,848 DEBUG client - state = CLOSING
client > Frame(fin=True, opcode=8, data=b'\x03\xf3', rsv1=False, rsv2=False, rsv3=False)
2020-05-15 16:39:49,848 DEBUG client > Frame(fin=True, opcode=8, data=b'\x03\xf3', rsv1=False, rsv2=False, rsv3=False)
client - event = data_received(<292 bytes>)
2020-05-15 16:39:49,870 DEBUG client - event = data_received(<292 bytes>)
client - event = data_received(<6 bytes>)
2020-05-15 16:39:50,010 DEBUG client - event = data_received(<6 bytes>)
client - event = data_received(<4 bytes>)
2020-05-15 16:39:50,012 DEBUG client - event = data_received(<4 bytes>)
client - event = connection_lost(None)
2020-05-15 16:39:50,012 DEBUG client - event = connection_lost(None)
client - state = CLOSED
2020-05-15 16:39:50,013 DEBUG client - state = CLOSED
client x code = 1006, reason = [no reason]
2020-05-15 16:39:50,013 DEBUG client x code = 1006, reason = [no reason]
client - aborted pending ping: 249957f7
2020-05-15 16:39:50,013 DEBUG client - aborted pending ping: 249957f7
client x closing TCP connection
2020-05-15 16:39:50,013 DEBUG client x closing TCP connection
```
```
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```
Is there a way to capture the code that initially caused the error?
I found a commit that referenced this issue https://github.com/aaugustin/websockets/commit/7e736b0db23070f18d6bcf6705e39156ca404aee but I'm using 8.1 and that's the behaviour.

**Comment by aaugustin** [comment]
If you catch the ConnectionClosed exception and dump a stack trace, you should see the original exception.

**Comment by ctlaltdefeat** [comment]
This is the stacktrace:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/usr/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/usr/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/usr/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/usr/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib/python3.8/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "websockets_test.py", line 51, in hello
    async for ds in websocket:
  File "/usr/lib/python3.8/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/usr/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/usr/lib/python3.8/site-packages/websockets/protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

**Comment by aaugustin** [comment]
:-(

It looks like we're only getting traces of websockets shutting down the connection here.

**Comment by cjerdonek** [comment]
Is this relevant? https://bugs.python.org/issue31033

**Comment by zymergen-stian** [comment]
https://github.com/aaugustin/websockets/blob/2b0f8cf0bc2c74ee9e39a1ff379543420d83b25e/src/websockets/protocol.py#L801

Seems the root cause is saved there but usually won't be captured by any logger. Should we add a logger line for it at least?

**Comment by zymergen-stian** [comment]
Also to note that I had a similar issue, and my investigation has gone to `fail_connection` cancelling the `transfer_data_task` due to a variety of possible error. My understanding is cancelling a parent asyncio task that is awaiting on a child task would result in the `CancelledError` "appear" on the child task. But without the `transfer_data_exc` logged anywhere I can't really tell what's going on.

**Comment by zymergen-stian** [comment]
nvm just learnt about `__cause__`

**Comment by aaugustin** [comment]
I've been trying to reproduce this by disabling responses to pings, which triggers a ping timeout, but I'm not getting the same results as you do.

If you still care about this issue, would you be able to provide a small script that reproduces it? You can probably reuse the examples in the `example` directory of this repository.

**Comment by aaugustin** [comment]
Perhaps https://github.com/aaugustin/websockets/issues/868#issuecomment-830869135 is what you originally wanted, so it's still tracked in another issue. https://github.com/aaugustin/websockets/issues/587 may help as well.
