### ISSUE TITLE
[QUESTION] Handling ConnectionClosedError in counter.py example

### ISSUE THREAD

**Issue by leonh** [aaugustin/websockets#773]
Hello, 

I have been using the **counter.py** example as a test simulating clients arriving quickly and leaving quickly using artillery testing tool.

my config for artillery is 

```
config:
    target: "ws://0.0.0.0:6789"
    ensure:
      maxErrorRate: 1
    phases:
      - duration: 10
        arrivalCount: 20
        name: "Warming up"
      - duration: 60
        arrivalCount: 500
        name: "Max load"
scenarios:
  - engine: ws
    flow:
      - think: 90
```
1 html ui arrival
20 arrivals in 20seconds
500 arrivals in the first minute 

connections stay open for 90 seconds
connections disconnect in order of arrival

I am monitoring the process of clients arriving and leaving via the html UI part of the counter demo. Which remains connect throughout the test.

I notice that the clients arrive in a fairly predictable way no major problems with html UI incrementing the counter and number of users online as clients arrive.

However when the client leave I see many of this type of error (below). 
The UI becomes very slow in updating increments to the counter during the period clients are disconnecting.

Is there any way to improve the handling of client disconnections?

```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-276734' coro=<WebSocketCommonProtocol.send() done, defined at /Users/leon/envs/kinto/lib/python3.8/site-packages/websockets/protocol.py:521> exception=ConnectionClosedError('code = 1005 (no status code [internal]), no reason') created at /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py:424>
source_traceback: Object created at (most recent call last):
  File "websockets_counter.py", line 77, in <module>
    asyncio.get_event_loop().run_forever()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 567, in run_forever
    self._run_once()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1847, in _run_once
    handle._run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/leon/envs/kinto/lib/python3.8/site-packages/websockets/server.py", line 191, in handler
    await self.ws_handler(self, path)
  File "websockets_counter.py", line 71, in counter
    await unregister(websocket)
  File "websockets_counter.py", line 50, in unregister
    await notify_users()
  File "websockets_counter.py", line 38, in notify_users
    await asyncio.wait([user.send(message) for user in USERS])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 424, in wait
    fs = {ensure_future(f, loop=loop) for f in set(fs)}
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 424, in <setcomp>
    fs = {ensure_future(f, loop=loop) for f in set(fs)}
Traceback (most recent call last):
  File "/Users/leon/envs/kinto/lib/python3.8/site-packages/websockets/protocol.py", line 555, in send
    await self.ensure_open()
  File "/Users/leon/envs/kinto/lib/python3.8/site-packages/websockets/protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1005 (no status code [internal]), no reason
```

**Comment by leonh** [comment]
Having tested some more (using the libraries interactive client) and a different example, I don't see any disparity as clients connect or disconnect. This suggests to me that the issue is more specific to my browser (chrome on mac) and the specific counter example.

**Comment by aaugustin** [comment]
`counter.py` is a toy example without error management.

The error occurs when a connection is closed and the script tries to notify other connections, but some of the other connections have also closed in the mean time. Adding error handling in `notify_users()` would help.
