### ISSUE TITLE
Strange Websocket error at coro=<RPCSession._throttled_request() with a 1005 code

### ISSUE THREAD

**Issue by PavlosTze** [aaugustin/websockets#781]
Hello,

I am currently using ElectrumX 1.15.0 with Protocol version 1.4.2 for Bitcoin and Websockets 8.1. I was trying to debug another issue and I got the following in my way. I need to mention that the following error did **not** cause my server to crash, but when I tried to reproduce it multiple times it eventually crashed but with a different exception.

Coin: Bitcoin (happens with BitcoinSV as well)
ElectrumX: latest (1.15.0 with Protocol version 1.4.2)
Services: RPC, WebSockets 8.1
OS: Ubuntu 18.04 (in Docker)

**I was testing it with artillery.io in a local REGTEST enviroment, setup:**
1) `npm install -g artillery `
2) `vim test.yml`
3) In test.yml insert the following: 
```
config:
  target: "ws://XXXX:XXX"
  tls:
    rejectUnauthorized: false
  plugins:
    fuzzer: {}
  phases:
    - duration: 60
      arrivalRate: 20
subprotocols:
    - json
scenarios:
  - engine: "ws"
    flow:
      - send: '{"id":0,"method":"server.version","params":["1.18.8-dev_289_android","1.4.2"]}'
      - send: '{"id":1,"method":"blockchain.headers.subscribe"}'
      - send: '{"id":2,"method":"blockchain.scripthash.subscribe","params":["963c7985bf4123e2d650c707458d6f731b2a0de6ffebbbcb3198f973aecb52c5"]}'
      - send: '{"id":3,"method":"blockchain.scripthash.subscribe","params":["578b41ac4333609a6216b0595d88df72070e734fcbd6ec58c3f2b6900d1f14cf"]}'
      - send: '{"id":4,"method":"blockchain.scripthash.subscribe","params":["6be90d7a1835ad86fa647e429e7e4f849c8da575abbcbf77178b4e80008217ba"]}'
      - send: '{"id":5,"method":"blockchain.scripthash.subscribe","params":["fc9794b06359653b29a2425f16401dba7e18e2f59ba63275d8146f2e420b8f59"]}'
```
4) `artillery run test.yml`

**The error logs are the following:**

```
INFO:electrumx:ElectrumX server starting
INFO:electrumx:logging level: DEBUG
INFO:Controller:Python version: 3.9.0b3 (default, Jun 12 2020, 00:52:24)  [GCC 9.3.0]
INFO:Controller:software version: ElectrumX 1.15.0
INFO:Controller:aiorpcX version: 0.18.4
INFO:Controller:supported protocol versions: 1.4-1.4.2
INFO:Controller:event loop policy: None
INFO:Controller:reorg limit is 8,000 blocks
INFO:Daemon:daemon #1 at node:19001/ (current)
INFO:DB:switching current directory to /data
INFO:DB:using leveldb for DB backend
ERROR:Daemon:starting up checking blocks.  Retrying occasionally...
INFO:Daemon:running normally
INFO:DB:created new database
INFO:DB:creating metadata directory
INFO:DB:UTXO DB version: 8
INFO:DB:coin: BitcoinSegwit
INFO:DB:network: regtest
INFO:DB:height: -1
INFO:DB:tip: 0000000000000000000000000000000000000000000000000000000000000000
INFO:DB:tx count: 0
INFO:DB:flushing DB cache at 1,200 MB
INFO:DB:sync time so far: 00s
INFO:History:history DB version: 1
INFO:History:flush count: 0
INFO:SessionManager:RPC server listening on 0.0.0.0:8000
INFO:Prefetcher:catching up to daemon height 0 (1 blocks behind)
INFO:Prefetcher:verified genesis block with hash 0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206
INFO:BlockProcessor:our height: 0 daemon: 0 UTXOs 0MB hist 0MB
INFO:BlockProcessor:caught up to height 0
INFO:DB:flushed filesystem data in 0.00s
INFO:History:flushed history in 0.0s for 0 addrs
INFO:DB:flushed 1 blocks with 0 txs, 0 UTXO adds, 0 spends in 0.0s, committing...
INFO:DB:flush #1 took 0.0s.  Height 0 txs: 0 (+0)
INFO:DB:tx/sec since genesis: 0, since last flush: 1
INFO:DB:sync time: 00s  ETA: -1d 23h 59m
INFO:BlockProcessor:ElectrumX 1.15.0 synced to height 0
INFO:DB:closing DBs to re-open for serving
INFO:DB:opened UTXO DB (for sync: False)
INFO:DB:UTXO DB version: 8
INFO:DB:coin: BitcoinSegwit
INFO:DB:network: regtest
INFO:DB:height: 0
INFO:DB:tip: 0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206
INFO:DB:tx count: 0
INFO:History:history DB version: 1
INFO:History:flush count: 1
INFO:DB:populating header merkle cache...
INFO:MemPool:beginning processing of daemon mempool.  This can take some time...
INFO:DB:header merkle cache populated in 0.0s
INFO:SessionManager:max session count: 1,000
INFO:SessionManager:session timeout: 600 seconds
INFO:SessionManager:session cost hard limit 10,000
INFO:SessionManager:session cost soft limit 1,000
INFO:SessionManager:bandwidth unit cost 5,000
INFO:SessionManager:request sleep 2,500ms
INFO:SessionManager:request timeout 30s
INFO:SessionManager:initial concurrent 10
INFO:SessionManager:max response size 1,000,000 bytes
INFO:ElectrumX:[265] WS 172.18.0.1:51658, 0 total
INFO:ElectrumX:[266] WS 172.18.0.1:51662, 0 total
INFO:ElectrumX:[267] WS 172.18.0.1:51666, 0 total
Task exception was never retrieved
future: <Task finished name='Task-3565' coro=<RPCSession._process_messages() done, defined at /usr/local/lib/python3.9/site-packages/aiorpcX-0.18.4-py3.9.egg/aiorpcx/session.py:432> exception=ConnectionClosedError('code = 1005 (no status code [internal]), no reason')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiorpcX-0.18.4-py3.9.egg/aiorpcx/session.py", line 435, in _process_messages
    message = await recv_message()
  File "/usr/local/lib/python3.9/site-packages/aiorpcX-0.18.4-py3.9.egg/aiorpcx/websocket.py", line 63, in recv_message
    message = await self.websocket.recv()
  File "/usr/local/lib/python3.9/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/usr/local/lib/python3.9/site-packages/websockets/protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1005 (no status code [internal]), no reason
Task exception was never retrieved
future: <Task finished name='Task-3569' coro=<RPCSession._throttled_request() done, defined at /usr/local/lib/python3.9/site-packages/aiorpcX-0.18.4-py3.9.egg/aiorpcx/session.py:458> exception=ConnectionClosedError('code = 1005 (no status code [internal]), no reason')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiorpcX-0.18.4-py3.9.egg/aiorpcx/session.py", line 488, in _throttled_request
    await self._send_message(message)
  File "/usr/local/lib/python3.9/site-packages/aiorpcX-0.18.4-py3.9.egg/aiorpcx/session.py", line 153, in _send_message
    await self.transport.write(message)
  File "/usr/local/lib/python3.9/site-packages/aiorpcX-0.18.4-py3.9.egg/aiorpcx/websocket.py", line 85, in write
    await self.websocket.send(framed_message)
  File "/usr/local/lib/python3.9/site-packages/websockets/protocol.py", line 555, in send
    await self.ensure_open()
  File "/usr/local/lib/python3.9/site-packages/websockets/protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1005 (no status code [internal]), no reason
```

I noticed that these errors occur for:
`      - send: '{"id":any_id,"method":"blockchain.scripthash.subscribe","params":["put_anything_valid_here"]}'`
and again, not all the times. Sometimes they take place, others don't, what I have observed is that they don't take place that much at the start of the server.

Any ideas what is causing this type of behavior?

PS: I have posted it on the ElectrumX error as well because I'm not sure if the issue is in websockets or ElectrumX.

**Comment by aaugustin** [comment]
Sorry, I don't wish to spend my time helping ElectrumX: https://websockets.readthedocs.io/en/latest/contributing.html#bitcoin-users

If you determine that websockets is at fault — based on the stack trace, I don't think it is — you're welcome to file a bug with a reproducible example that doesn't involve ElectrumX.
