### ISSUE TITLE
loop argument to asyncio.Queue is deprecated

### ISSUE THREAD

**Issue by wom-bat** [aaugustin/websockets#801]
When I run the built-in client using:
   `python3 -m websockets ws://a.ur.i/`
I see:
`/usr/local/lib/python3.8/dist-packages/websockets/__main__.py:180: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  inputs: asyncio.Queue[str] = asyncio.Queue(loop=loop)`

**Comment by aaugustin** [comment]
This is easily reproduced.

Annoyingly, simply removing the loop argument on Python ≥ 3.8 causes trouble:

```
$ PYTHONPATH=src python3.8 -m websockets ws://echo.websocket.org/
Connected to ws://echo.websocket.org/.
Connection closed: code = 1000 (OK), no reason.
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<run_client() done, defined at /Users/myk/dev/websockets/src/websockets/__main__.py:91> exception=RuntimeError("Task <Task pending name='Task-6' coro=<Queue.get() running at /Users/myk/.pyenv/versions/3.8.2/lib/python3.8/asyncio/queues.py:163> cb=[_wait.<locals>._on_completion() at /Users/myk/.pyenv/versions/3.8.2/lib/python3.8/asyncio/tasks.py:507]> got Future <Future pending> attached to a different loop")>
Traceback (most recent call last):
  File "/Users/myk/dev/websockets/src/websockets/__main__.py", line 134, in run_client
    message = outgoing.result()
  File "/Users/myk/.pyenv/versions/3.8.2/lib/python3.8/asyncio/queues.py", line 163, in get
    await getter
RuntimeError: Task <Task pending name='Task-6' coro=<Queue.get() running at /Users/myk/.pyenv/versions/3.8.2/lib/python3.8/asyncio/queues.py:163> cb=[_wait.<locals>._on_completion() at /Users/myk/.pyenv/versions/3.8.2/lib/python3.8/asyncio/tasks.py:507]> got Future <Future pending> attached to a different loop
```

This is because websockets creates a new loop and the queue needs to be tied to that loop.
