### ISSUE TITLE
Error in data transfer

### ISSUE THREAD

**Issue by Urkallinger** [aaugustin/websockets#810]
I am currently developing a WebApp which communicates with a server via a WebSocket. For this I use websockets on the server side.
If I open the web app with my smartphone, the connection works fine. But if I don't do anything with my smartphone for about 5 minutes, the connection is terminated with the following traceback:

```
Error in data transfer

Traceback (most recent call last):
  File "C:\Users\Philipp\.virtualenvs\DartScoreBoardServer-VlgEWMq_\lib\site-packages\websockets\protocol.py", line 827, in transfer_data
	message = await self.read_message()
  File "C:\Users\Philipp\.virtualenvs\DartScoreBoardServer-VlgEWMq_\lib\site-packages\websockets\protocol.py", line 895, in read_message
	frame = await self.read_data_frame(max_size=self.max_size)
  File "C:\Users\Philipp\.virtualenvs\DartScoreBoardServer-VlgEWMq_\lib\site-packages\websockets\protocol.py", line 971, in read_data_frame
	frame = await self.read_frame(max_size)
  File "C:\Users\Philipp\.virtualenvs\DartScoreBoardServer-VlgEWMq_\lib\site-packages\websockets\protocol.py", line 1047, in read_frame
	frame = await Frame.read(
  File "C:\Users\Philipp\.virtualenvs\DartScoreBoardServer-VlgEWMq_\lib\site-packages\websockets\framing.py", line 105, in read
	data = await reader(2)
  File "c:\python38\lib\asyncio\streams.py", line 723, in readexactly
	await self._wait_for_data('readexactly')
  File "c:\python38\lib\asyncio\streams.py", line 517, in _wait_for_data
	await self._waiter
  File "c:\python38\lib\asyncio\proactor_events.py", line 280, in _loop_reading
	data = fut.result()
  File "c:\python38\lib\asyncio\windows_events.py", line 808, in _poll
	value = callback(transferred, key, ov)
  File "c:\python38\lib\asyncio\windows_events.py", line 453, in finish_recv
	return ov.getresult()
OSError: [WinError 121] The semaphore timeout period has expired
```

Does anyone have any idea what could be causing this?

Thank you!

**Comment by aaugustin** [comment]
This seems to be a network connection timeout. Probably we should catch it together with `ConnectionError` and `EOFError`  in the `transfer_data` method. It's a bit annoying that `asyncio` doesn't give a better error in this case.

I'm hesitating to catch `OSError` here: that seems too wide for "connection timed out".

Could you file a ticket on bugs.python.org to ask if it's possible for asyncio to raise a better exception in this case? Perhaps there's a technical reason that makes that difficult. However, it seems best to fix it in asyncio than in every program or library built on top of asyncio.

**Comment by Arun4rangan** [comment]
I am also running into a similar error, but in my case I am getting `TimeoutError`:
```
Error in data transfer
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 1051, in read_frame
    extensions=self.extensions,
  File "/usr/local/lib/python3.6/dist-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.6/asyncio/streams.py", line 674, in readexactly
    yield from self._wait_for_data('readexactly')
  File "/usr/lib/python3.6/asyncio/streams.py", line 464, in _wait_for_data
    yield from self._waiter
TimeoutError: [Errno 110] Connection timed out
```
Would you mind adding TimeoutError to https://github.com/aaugustin/websockets/blob/2b0f8cf0bc2c74ee9e39a1ff379543420d83b25e/src/websockets/protocol.py#L880?

**Comment by aaugustin** [comment]
Based on PEP 3151 it seems all right to catch `TimeoutError` (not to be confused with `asyncio.TimeoutError`, which happens to be `concurrent.futures.TimeoutError`...) I did that.

I don't want to add `OSError` wholesale or to start making my own list of Windows error codes. So I'll stick with my previous recommendation to escalate this as a Python bug.
