### ISSUE TITLE
Fatal Error on SSL Transport - sslv3 alert bad record mac

### ISSUE THREAD

**Issue by m-emori** [aaugustin/websockets#818]
When using SSL with websocket, I get an SSLError.

```
[2020-08-17 15:02:51,078] websockets.protocol : Error in data transfer [MainProcess - MainThread]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/usr/local/lib/python3.7/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/usr/local/lib/python3.7/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/usr/local/lib/python3.7/site-packages/websockets/protocol.py", line 1051, in read_frame
    extensions=self.extensions,
  File "/usr/local/lib/python3.7/site-packages/websockets/framing.py", line 106, in read
    data = await reader(2)
  File "/usr/local/lib/python3.7/asyncio/streams.py", line 679, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/local/lib/python3.7/asyncio/streams.py", line 473, in _wait_for_data
    await self._waiter
  File "guac_ws_client.py", line 166, in read
    await websocket.send(instruction)
  File "/usr/local/lib/python3.7/site-packages/websockets/protocol.py", line 567, in send
    await self.write_frame(True, opcode, data)
  File "/usr/local/lib/python3.7/site-packages/websockets/protocol.py", line 1077, in write_frame
    await self._drain()
  File "/usr/local/lib/python3.7/site-packages/websockets/protocol.py", line 306, in _drain
    raise exc
  File "/usr/local/lib/python3.7/asyncio/sslproto.py", line 530, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/local/lib/python3.7/asyncio/sslproto.py", line 202, in feed_ssldata
    chunk = self._sslobj.read(self.max_size)
  File "/usr/local/lib/python3.7/ssl.py", line 707, in read
    v = self._sslobj.read(len)
ssl.SSLError: [SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2488)
```

When data reception (SSL_read) and data transmission (SSL_write) occur at the same time, the error seems to occur.
It can be solved by exclusive read and write.

When I asked a question on the python bug tracker, it was an issue in the websocket package.
Can it be dealt with?

https://bugs.python.org/issue41597

## Environments:
  * debian 4.19.46
  * Python 3.7.3
  * OpenSSL 1.1.0l  10 Sep 2019

**Comment by aaugustin** [comment]
`websockets` doesn't use threads. Does you code use threads? Are you interacting with the websocket connection from multiple threads? If so, it's up to you to isolate reads and writes with locks. We could document that.

I don't think websockets should do it, exactly for the same reason asyncio doesn't do it.

**Comment by m-emori** [comment]
Thank you for your reply.
I understand that websocket cannot be used in multiple threads.
I close the issue.

**Comment by aaugustin** [comment]
If you have to, you may be able to use websockets in multiple threads with careful locking and usage of call_soon_threadsafe where needed. I wouldn't recommend it, though ;-) Especially if you don't have a clear vision of how to interact from a thread with an event loop running in another thread.

**Comment by m-emori** [comment]
Two threads are used to relay the communications as shown below.
I will try other websocket libraries, such as tornado
Thank you.

|Server|-----(Thread1: websocket.recv)---->|Client|-----(Thread1: otherstream.send)---->|Other|
|Server|<----(Thread2: websocket.send)-----|Client|<----(Thread2: otherstream.recv)-----|Other|
