### ISSUE TITLE
Error keepalive_ping which leads to error in data transfer

### ISSUE THREAD

**Issue by Arun4rangan** [aaugustin/websockets#823]
Hey I am running into this issue running SocketIO running under uvicorn.

I am running many websocket clients and forcefully shutting them down randomly, this is leading to the error bellow on the server side:

```
{"identifier": "emitter", "ctx": {"message": "Fatal write error on socket transport", "exception": "TimeoutError(110, 'Connection timed out')", "transport": "<_SelectorSocketTransport closing fd=22 read=idle write=<idle, bufsize=0>>", "protocol": "<uvicorn.protocols.websockets.websockets_impl.WebSocketProtocol object at 0x7fae15245208>"}, "event": "Loop error occured", "level": "error", "timestamp": "2020-08-29T14:26:02.058183Z"}
Unexpected exception in keepalive ping task
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 1130, in keepalive_ping
    ping_waiter = await self.ping()
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 749, in ping
    await self.write_frame(True, OP_PING, data)
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 1077, in write_frame
    await self._drain()
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 306, in _drain
    raise exc
  File "/usr/local/lib/python3.6/dist-packages/engineio/asyncio_socket.py", line 193, in writer
    await ws.send(pkt.encode(always_bytes=False))
  File "/usr/local/lib/python3.6/dist-packages/engineio/async_drivers/asgi.py", line 233, in send
    'text': msg_text})
  File "/usr/local/lib/python3.6/dist-packages/uvicorn/protocols/websockets/websockets_impl.py", line 212, in asgi_send
    await self.send(data)
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 567, in send
    await self.write_frame(True, opcode, data)
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 1077, in write_frame
    await self._drain()
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 318, in _drain
    await self._drain_helper()
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 299, in _drain_helper
    await waiter
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 775, in _write_ready
    n = self._sock.send(self._buffer)
TimeoutError: [Errno 110] Connection timed out
Error in data transfer
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 995, in read_data_frame
    await self.pong(frame.data)
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 770, in pong
    await self.write_frame(True, OP_PONG, data)
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 1077, in write_frame
    await self._drain()
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 306, in _drain
    raise exc
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 1130, in keepalive_ping
    ping_waiter = await self.ping()
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 749, in ping
    await self.write_frame(True, OP_PING, data)
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 1077, in write_frame
    await self._drain()
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 306, in _drain
    raise exc
  File "/usr/local/lib/python3.6/dist-packages/engineio/asyncio_socket.py", line 193, in writer
    await ws.send(pkt.encode(always_bytes=False))
  File "/usr/local/lib/python3.6/dist-packages/engineio/async_drivers/asgi.py", line 233, in send
    'text': msg_text})
  File "/usr/local/lib/python3.6/dist-packages/uvicorn/protocols/websockets/websockets_impl.py", line 212, in asgi_send
    await self.send(data)
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 567, in send
    await self.write_frame(True, opcode, data)
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 1077, in write_frame
    await self._drain()
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 318, in _drain
    await self._drain_helper()
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 299, in _drain_helper
    await waiter
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 775, in _write_ready
    n = self._sock.send(self._buffer)
TimeoutError: [Errno 110] Connection timed out
```
To log this error :
```
def handle_async_exception(loop, ctx):
    logger.error("Loop error occured", ctx=ctx)
loop = asyncio.get_event_loop()
loop.set_exception_handler(handle_async_exception)
```

If its ran on asyncio default loop (linux), it throws this error. However if I ran this on uvloop, I am getting:

```
Process Process-9:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/streaming/app/emitter_app/emitter.py", line 60, in start_emitter
    loop.run_until_complete(asyncio.gather(server.serve(), push_payload(queue)))
  File "uvloop/loop.pyx", line 1454, in uvloop.loop.Loop.run_until_complete
RuntimeError: Event loop stopped before Future completed.
```

Is this a bug on how websocket handles timeout or this a something wrong with how I am handling websocket disconnects?

Thanks!

**Comment by aaugustin** [comment]
I'm not seeing the problem here. If you forcefully kill the client, then the server gets a timeout. Specifically, the "keepalive ping task", which is responsible for detecting if the client dies, does its job.

Regarding the situation with uvloop, you should keep the event loop running until `close()` and `wait_closed()` have completed. The error message suggests that you don't.

**Comment by Arun4rangan** [comment]
Hey @aaugustin thanks for the reply. Shouldn't web-sockets server manage the clients regardless of what state they are in? In a production server, there might be users who forcefully shutdown their client, which in this case will lead to exception. We wouldn't want the sever to go down based on what the user does to their client.

Regarding `uvloop`, I don't actually call `close` or `wait_closed`, the websockets are running in `run_until_complete`. I will check with the uvloop community to why this happens. I would at least expect the same error, not the stoppage of the event loop.

**Comment by aaugustin** [comment]
The server doesn't go down — at least it doesn't with asyncio; I have no idea what you're doing with uvloop or how I could reproduce your results.

You get a log explaining that the client timed out. This can happen for a bunch of reasons. It's quite annoying to debug without logs. You can configure your logging to hide these messages if you don't want them.

**Comment by Arun4rangan** [comment]
That makes sense, I will try to get some answers as to why uvloop is closing its loop on this exception on their community.

Thanks for your help.
