### ISSUE TITLE
How to make a long running websocket client?

### ISSUE THREAD

**Issue by rmit-s3686930-keyu** [aaugustin/websockets#824]
i want to make a programme that:

1. send message to the server once (subscribe)
2. receive message from the server non stop

i have tried this 
```
async def subscribe():
    async with websockets.connect(URL) as websocket:
        await websocket.send(json.dumps(DATA))

        while True:
            greeting = await websocket.recv()
            print(f"< {greeting}")

asyncio.get_event_loop().run_until_complete(subscribe())
```

it will work for a while, but after couple minutes it gives
```
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\websockets\protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "C:\Python38\lib\site-packages\websockets\protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "C:\Python38\lib\site-packages\websockets\protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "C:\Python38\lib\site-packages\websockets\protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "C:\Python38\lib\site-packages\websockets\framing.py", line 105, in read
    data = await reader(2)
  File "C:\Python38\lib\asyncio\streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "C:\Python38\lib\asyncio\streams.py", line 517, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:/Users/tyran/OneDrive/Desktop/py/remote.py", line 43, in <module>
    asyncio.get_event_loop().run_until_complete(subscribe())
  File "C:\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:/Users/tyran/OneDrive/Desktop/py/remote.py", line 40, in subscribe
    greeting = await websocket.recv()
  File "C:\Python38\lib\site-packages\websockets\protocol.py", line 509, in recv
    await self.ensure_open()
  File "C:\Python38\lib\site-packages\websockets\protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

**Comment by rmit-s3686930-keyu** [comment]
I was suspecting i had something to do with the `asyncio` library, and i basically know nothing about it. As i was about to give up, i tried the `aiohttp` library:
```
async def subscribe():
    async with aiohttp.ClientSession() as session:
        async with session.ws_connect(URL) as ws:
            await ws.send_json(DATA)

            while True:
                j = json.dumps(await ws.receive_json())
                print(j)

asyncio.get_event_loop().run_until_complete(subscribe())
```
it worked fine for me.
Can somebody explain what caused this issue and how to solve it? It would be a great lesson for me.
Thanks!

**Comment by VacantHusky** [comment]
add ping_timeout=None
```python
async with websockets.connect("ws://127.0.0.1:53392/", ping_timeout=None, loop=self.loop) as websocket:
    # do something
```
Hope it helps you.

**Comment by aaugustin** [comment]
If `ping_timeout=None` solves that kind of problem, then it means that the server doesn't respond to pings properly, which may happen but isn't compliant.

**Comment by aaugustin** [comment]
If you still need help with this, please run your program with debugging turned on and provide logs:
https://websockets.readthedocs.io/en/stable/cheatsheet.html#debugging
