### ISSUE TITLE
ssl.SSLError: [SSL] PEM lib (_ssl.c:4012)

### ISSUE THREAD

**Issue by Directory** [aaugustin/websockets#826]
Im trying to reuse my letsencrypt files that cerbot generated for nginx. my code is as follows.
```py
cert_dir = '/etc/letsencrypt/live/site.com'
ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
fullchain = f'{cert_dir}/fullchain.pem'
ssl_context.load_cert_chain(fullchain)
```
and the traceback is
```py
Traceback (most recent call last):
  File "main.py", line 306, in <module>
    loop.run_until_complete(init())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "main.py", line 103, in init
    ssl_context.load_cert_chain(fullchain)
ssl.SSLError: [SSL] PEM lib (_ssl.c:4012)
```
i can confirm that the file is in place. idk why this exception happens. additionaly i would like to know if im doing anything wrong or unsecure here. letsencryt generates 4 pem files. the files are cert.pem, chain.pem, fullchain.pem, and privkey.pem. i believe fullchain.pem is the one i need to use.

Ill say right now that i checked the contents of fullchain.pem and its just a copy of cert.pem and chain.pem in one, so i assume `load_cert_chain()` should know what do to with that. Im on ubuntu server with the most recent version of openssl installed

**Comment by Directory** [comment]
solved. read up on load_cert_chain() from ssl docs. just `fullchain.pem` is not enough. this is what i did.
```py
cert_dir = '/etc/letsencrypt/live/site.com'
ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
cert = f'{cert_dir}/fullchain.pem'
privkey = f'{cert_dir}/privkey.pem'
ssl_context.load_cert_chain(certfile=cert, keyfile=privkey)
```
now the privkey is passed too. just make sure you `chmod 755` the symlinks that python is using AND the destination file that those symlinks point too. You may need to also open permissions for the parent directorys. Im not sure if this will work on certificate renewal since cerbot will just make new files and point the symlinks to it. maybe cerbot retains the perms, maybe not, take that as you will.

**Comment by Directory** [comment]
renewing the certificates does not modify previously set permmissions
