### ISSUE TITLE
raise on non-ascii values passed to parse_uri

### ISSUE THREAD

**Issue by graingert** [aaugustin/websockets#832]
when connecting to a service using a ws URI with punycoded/idna or non-ascii path segments, I get a connection error:

## actual behaviour:

```python
>>> await websockets.connect("ws://domain.example.com:5080/ws/user/albanø@hotmail.no")
Traceback (most recent call last):
  File "/home/graingert/.virtualenvs/websockets/lib/python3.8/site-packages/websockets/http.py", line 139, in read_response
    status_line = await read_line(stream)
  File "/home/graingert/.virtualenvs/websockets/lib/python3.8/site-packages/websockets/http.py", line 219, in read_line
    raise EOFError("line without CRLF")
EOFError: line without CRLF

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/graingert/.virtualenvs/websockets/lib/python3.8/site-packages/websockets/client.py", line 101, in read_http_response
    status_code, reason, headers = await read_response(self.reader)
  File "/home/graingert/.virtualenvs/websockets/lib/python3.8/site-packages/websockets/http.py", line 141, in read_response
    raise EOFError("connection closed while reading HTTP status line") from exc
EOFError: connection closed while reading HTTP status line

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "<console>", line 1, in <module>
  File "/home/graingert/.virtualenvs/websockets/lib/python3.8/site-packages/websockets/client.py", line 542, in __await_impl__
    await protocol.handshake(
  File "/home/graingert/.virtualenvs/websockets/lib/python3.8/site-packages/websockets/client.py", line 290, in handshake
    status_code, response_headers = await self.read_http_response()
  File "/home/graingert/.virtualenvs/websockets/lib/python3.8/site-packages/websockets/client.py", line 103, in read_http_response
    raise InvalidMessage("did not receive a valid HTTP response") from exc
websockets.exceptions.InvalidMessage: did not receive a valid HTTP response
```
### with hyperlink
```python
>>> await websockets.connect(hyperlink.parse("ws://domain.example.com:5080/ws/user/albanø@hotmail.no").to_uri().to_text())
<websockets.client.WebSocketClientProtocol object at 0x7fefc3571a00>
```

## expected:

```python
>>> await websockets.connect("ws://domain.example.com:5080/ws/user/albanø@hotmail.no")
<websockets.client.WebSocketClientProtocol object at 0x7fefc3571a00>
```

should be a simple change to websockets.uri.parse_uri, to use hyperlink.parse instead of urllib.parse.urlparse. I can prepare a PR if you're interested in this change

**Comment by graingert** [comment]
An alternative would be to default to only allowing ascii URIs:

```
def parse_uri(uri: str, ascii_only: bool=True) -> WebSocketURI:
    """
    Parse and validate a WebSocket URI.
    :raises ValueError: if ``uri`` isn't a valid WebSocket URI.
    """
    if ascii_only:
        try:
            uri.encode("ascii")
        except AttributeError:
            raise TypeError(f"a string-like object is required not {type(uri)}") from None
        except UnicodeEncodeError:
            raise Exception(f"Invalid url, use parse_uri({uri!r}, ascii_only=False) or parse_uri(hyperlink.parse({uri!r}).to_uri().to_text()")
    parsed = urllib.parse.urlparse(uri)
```

**Comment by aaugustin** [comment]
For now websockets has no dependencies. This is a state of things I'm reasonably happy with.

What you have is an IRI, not a URI, and websockets only supports URI — this is why the parameter is called URI.

I understand that most developers aren't clear on URI vs. IRI so it's probably worth treating IRI like they expect.

There's no need to pull a third-party dependency for this.

```python
from urllib.parse import quote
resource_name = quote(resource_name)
```

around https://github.com/aaugustin/websockets/blob/master/src/websockets/uri.py#L68-L73 should do the job. We could specify additional safe characters. We must also handle the query string similarly.

Also `host = host.encode("idna").decode()` while we're there.

**Comment by graingert** [comment]
> I understand that most developers aren't clear on URI vs. IRI so it's probably worth treating IRI like they expect.

@aaugustin thanks for the explanation of IRI vs URI. Reading further on the difference I now think it's correct for websocket to only allow URIs - and should therefore throw with a ValueError when called with a non-ascii value
