### ISSUE TITLE
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

### ISSUE THREAD

**Issue by zhbzhbzhbz** [aaugustin/websockets#838]
This error occurs irregularly, without any operation.
And if I use other websocket library to connect to the same server, I never meet the same error.
```
Traceback (most recent call last):
  File "D:\Program Files\Python38\lib\site-packages\websockets\protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "D:\Program Files\Python38\lib\site-packages\websockets\protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "D:\Program Files\Python38\lib\site-packages\websockets\protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "D:\Program Files\Python38\lib\site-packages\websockets\protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "D:\Program Files\Python38\lib\site-packages\websockets\framing.py", line 105, in read
    data = await reader(2)
  File "D:\Program Files\Python38\lib\asyncio\streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "D:\Program Files\Python38\lib\asyncio\streams.py", line 517, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "qq.py", line 52, in <module>
    QQSpider.start_monitor(a)
  File "qq.py", line 25, in start_monitor
threading.Thread(target=asyncio.get_event_loop().run_until_complete(QQSpider().websocket_receive(on_receive_message))).start()
  File "D:\Program Files\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "qq - 副本.py", line 31, in websocket_receive
    msg = await websocket.recv()
  File "D:\Program Files\Python38\lib\site-packages\websockets\protocol.py", line 509, in recv
    await self.ensure_open()
  File "D:\Program Files\Python38\lib\site-packages\websockets\protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

**Comment by aaugustin** [comment]
I believe the FAQ explains what happens here:
https://websockets.readthedocs.io/en/stable/faq.html#what-does-connectionclosederror-code-1006-mean
