### ISSUE TITLE
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

### ISSUE THREAD

**Issue by Corezcy** [aaugustin/websockets#839]
I use `websockets` to make a proxy between client and server.
After the server transmit the result , I get this error!
Here is the log:
![image](https://user-images.githubusercontent.com/33271784/94536076-e8323b00-0274-11eb-8389-da54544bf15e.png)
here is the error:

```
Error in connection handler
Traceback (most recent call last):
  File "/Users/core/.local/lib/python3.7/site-packages/websockets/protocol.py", line 674, in transfer_data
    message = yield from self.read_message()
  File "/Users/core/.local/lib/python3.7/site-packages/websockets/protocol.py", line 742, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "/Users/core/.local/lib/python3.7/site-packages/websockets/protocol.py", line 815, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "/Users/core/.local/lib/python3.7/site-packages/websockets/protocol.py", line 884, in read_frame
    extensions=self.extensions,
  File "/Users/core/.local/lib/python3.7/site-packages/websockets/framing.py", line 99, in read
    data = yield from reader(2)
  File "/Users/core/Documents/anaconda3/envs/DL/lib/python3.7/asyncio/streams.py", line 677, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/core/.local/lib/python3.7/site-packages/websockets/server.py", line 169, in handler
    yield from self.ws_handler(self, path)
  File "/Users/core/Desktop/websocket_proxpy/websocket_proxpy/proxy.py", line 145, in proxy_dispatcher
    yield from self.process_arbitrary_requests(proxy_web_socket, proxied_web_socket, connection)
  File "/Users/core/Desktop/websocket_proxpy/websocket_proxpy/proxy.py", line 171, in process_arbitrary_requests
    request_for_proxy = yield from proxy_web_socket.recv()
  File "/Users/core/.local/lib/python3.7/site-packages/websockets/protocol.py", line 434, in recv
    yield from self.ensure_open()
  File "/Users/core/.local/lib/python3.7/site-packages/websockets/protocol.py", line 646, in ensure_open
    ) from self.transfer_data_exc
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
``` 
I dont know where is wrong  and see the same problem has been asked. But still no mind  !

**Comment by lgrahl** [comment]
Please, see https://websockets.readthedocs.io/en/stable/faq.html#what-does-connectionclosederror-code-1006-mean

**Comment by Corezcy** [comment]
> Please, see https://websockets.readthedocs.io/en/stable/faq.html#what-does-connectionclosederror-code-1006-mean
I have seen the doc , the `asyncio.IncompleteReadError` cause the  `websocket ConnectionClosedError`.But the TCP connection is still connected,  so it's wrong to reconnect (this time is wrong code 1005)

**Comment by lgrahl** [comment]
`asyncio.IncompleteReadError` is only fired when EOF has been received, so I doubt that TCP isn't closed (at least the receiving half) at that point.

**Comment by Corezcy** [comment]
> `asyncio.IncompleteReadError` is only fired when EOF has been received, so I doubt that TCP isn't closed (at least the receiving half) at that point.

I 've solve this question ! Thanks very much !
First of all , for avoid `asyncio.IncompleteReadError`, I make the `client` to send JSON of close the connection.
and I use `yield from xxx . wait_closed( )` to solve this problem！ 
Thanks !!!
