### ISSUE TITLE
time.py example should have a different filename

### ISSUE THREAD

**Issue by SzieberthAdam** [aaugustin/websockets#87]
Example files are unable to run when the current directory is `example` (which would be the most straigtforward place to start them). This is because `time.py` interferes with the standard library module.

```
>>> import asyncio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/asyncio/__init__.py", line 21, in <module>
    from .base_events import *
  File "/usr/lib/python3.4/asyncio/base_events.py", line 18, in <module>
    import concurrent.futures
  File "/usr/lib/python3.4/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 7, in <module>
    import logging
  File "/usr/lib/python3.4/logging/__init__.py", line 26, in <module>
    import sys, os, time, io, traceback, warnings, weakref, collections
  File "/home/adam/github/ws34/websockets/example/time.py", line 6, in <module>
    import websockets
  File "/home/adam/github/ws34/lib/python3.4/site-packages/websockets/__init__.py", line 3, in <module>
    from .client import *
  File "/home/adam/github/ws34/lib/python3.4/site-packages/websockets/client.py", line 14, in <module>
    from .http import USER_AGENT, read_response
  File "/home/adam/github/ws34/lib/python3.4/site-packages/websockets/http.py", line 29, in <module>
    @asyncio.coroutine
AttributeError: 'module' object has no attribute 'coroutine'
```
Not that logging module tries and fails to import `time` from the standard library.

I suggest naming the examples as `sendtime.py` and `recvtime.html`.

**Comment by aaugustin** [comment]
Good idea.

What about `showtime.html`? `recvtime.html` makes me think of `man 2 recv` which feels weird for a web page.

Would you like to submit a pull request?

**Comment by SzieberthAdam** [comment]
Sure.

**Comment by SzieberthAdam** [comment]
Done. I hope I am doing things right. If not, please tell. I used to only manage my own repos. :)
