### ISSUE TITLE
Unittest failures in version 3.5.1 and with latest asyncio code.

### ISSUE THREAD

**Issue by SzieberthAdam** [aaugustin/websockets#92]
Currently at abec6594f master. 

Operating system: Linux szamsi 4.2.3-1-ARCH #1 SMP PREEMPT Sat Oct 3 18:52:50 CEST 2015 x86_64 GNU/Linux
Python version: Python 3.5.1 (default, Dec  7 2015, 12:58:09) [GCC 5.2.0] on linux
Asyncio: python/asyncio@74f2d8c87 master
Test result:
```
[adam@szamsi websockets]$ make test
python -m unittest
.......................................................................................................E..EE.E..............EE..........................F.......E......E.....E......................................................
======================================================================
ERROR: test_close_connection_lost (websockets.test_protocol.ClientTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adam/github/ws34/websockets/websockets/protocol.py", line 548, in write_frame
    yield from self.writer.drain()
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/usr/lib/python3.5/asyncio/streams.py", line 313, in drain
    yield from self._protocol._drain_helper()
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/usr/lib/python3.5/asyncio/streams.py", line 194, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/adam/github/ws34/websockets/websockets/test_protocol.py", line 699, in test_close_connection_lost
    self.loop.run_until_complete(self.protocol.close(reason='close'))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 337, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 121, in send
    return self.gen.send(value)
  File "/home/adam/github/ws34/websockets/websockets/protocol.py", line 217, in close
    yield from self.write_frame(OP_CLOSE, frame_data)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/home/adam/github/ws34/websockets/websockets/protocol.py", line 553, in write_frame
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006, no reason.

======================================================================
ERROR: test_close_preserves_incoming_frames (websockets.test_protocol.ClientTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adam/github/ws34/websockets/websockets/protocol.py", line 548, in write_frame
    yield from self.writer.drain()
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/usr/lib/python3.5/asyncio/streams.py", line 313, in drain
    yield from self._protocol._drain_helper()
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/usr/lib/python3.5/asyncio/streams.py", line 194, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/adam/github/ws34/websockets/websockets/test_protocol.py", line 681, in test_close_preserves_incoming_frames
    self.loop.run_until_complete(self.protocol.close(reason='close'))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 337, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 121, in send
    return self.gen.send(value)
  File "/home/adam/github/ws34/websockets/websockets/protocol.py", line 217, in close
    yield from self.write_frame(OP_CLOSE, frame_data)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/home/adam/github/ws34/websockets/websockets/protocol.py", line 553, in write_frame
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, reason = close.

======================================================================
ERROR: test_close_protocol_error (websockets.test_protocol.ClientTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adam/github/ws34/websockets/websockets/protocol.py", line 548, in write_frame
    yield from self.writer.drain()
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/usr/lib/python3.5/asyncio/streams.py", line 313, in drain
    yield from self._protocol._drain_helper()
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/usr/lib/python3.5/asyncio/streams.py", line 194, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/adam/github/ws34/websockets/websockets/test_protocol.py", line 693, in test_close_protocol_error
    self.loop.run_until_complete(self.protocol.close(reason='close'))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 337, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 121, in send
    return self.gen.send(value)
  File "/home/adam/github/ws34/websockets/websockets/protocol.py", line 217, in close
    yield from self.write_frame(OP_CLOSE, frame_data)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/home/adam/github/ws34/websockets/websockets/protocol.py", line 553, in write_frame
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1002, no reason.

======================================================================
ERROR: test_connection_closed_attributes (websockets.test_protocol.ClientTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adam/github/ws34/websockets/websockets/protocol.py", line 548, in write_frame
    yield from self.writer.drain()
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/usr/lib/python3.5/asyncio/streams.py", line 313, in drain
    yield from self._protocol._drain_helper()
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/usr/lib/python3.5/asyncio/streams.py", line 194, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/adam/github/ws34/websockets/websockets/test_protocol.py", line 620, in test_connection_closed_attributes
    self.loop.run_until_complete(self.protocol.close(reason='close'))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 337, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 121, in send
    return self.gen.send(value)
  File "/home/adam/github/ws34/websockets/websockets/protocol.py", line 217, in close
    yield from self.write_frame(OP_CLOSE, frame_data)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/home/adam/github/ws34/websockets/websockets/protocol.py", line 553, in write_frame
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, reason = close.

======================================================================
ERROR: test_local_close (websockets.test_protocol.ClientTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adam/github/ws34/websockets/websockets/protocol.py", line 548, in write_frame
    yield from self.writer.drain()
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/usr/lib/python3.5/asyncio/streams.py", line 313, in drain
    yield from self._protocol._drain_helper()
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/usr/lib/python3.5/asyncio/streams.py", line 194, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/adam/github/ws34/websockets/websockets/test_protocol.py", line 637, in test_local_close
    self.loop.run_until_complete(self.protocol.close(reason='close'))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 337, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 121, in send
    return self.gen.send(value)
  File "/home/adam/github/ws34/websockets/websockets/protocol.py", line 217, in close
    yield from self.write_frame(OP_CLOSE, frame_data)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/home/adam/github/ws34/websockets/websockets/protocol.py", line 553, in write_frame
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, reason = close.

======================================================================
ERROR: test_local_close_during_recv (websockets.test_protocol.ClientTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adam/github/ws34/websockets/websockets/protocol.py", line 548, in write_frame
    yield from self.writer.drain()
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/usr/lib/python3.5/asyncio/streams.py", line 313, in drain
    yield from self._protocol._drain_helper()
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/usr/lib/python3.5/asyncio/streams.py", line 194, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/adam/github/ws34/websockets/websockets/test_protocol.py", line 726, in test_local_close_during_recv
    self.loop.run_until_complete(self.protocol.close(reason='close'))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 337, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 121, in send
    return self.gen.send(value)
  File "/home/adam/github/ws34/websockets/websockets/protocol.py", line 217, in close
    yield from self.write_frame(OP_CLOSE, frame_data)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/home/adam/github/ws34/websockets/websockets/protocol.py", line 553, in write_frame
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, reason = close.

======================================================================
ERROR: test_simultaneous_close (websockets.test_protocol.ClientTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adam/github/ws34/websockets/websockets/protocol.py", line 548, in write_frame
    yield from self.writer.drain()
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/usr/lib/python3.5/asyncio/streams.py", line 313, in drain
    yield from self._protocol._drain_helper()
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/usr/lib/python3.5/asyncio/streams.py", line 194, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/adam/github/ws34/websockets/websockets/test_protocol.py", line 670, in test_simultaneous_close
    self.loop.run_until_complete(self.protocol.close(reason='local'))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 337, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 121, in send
    return self.gen.send(value)
  File "/home/adam/github/ws34/websockets/websockets/protocol.py", line 217, in close
    yield from self.write_frame(OP_CLOSE, frame_data)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/home/adam/github/ws34/websockets/websockets/protocol.py", line 553, in write_frame
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, reason = remote.

======================================================================
ERROR: test_close_connection_lost (websockets.test_protocol.ServerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adam/github/ws34/websockets/websockets/protocol.py", line 548, in write_frame
    yield from self.writer.drain()
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/usr/lib/python3.5/asyncio/streams.py", line 313, in drain
    yield from self._protocol._drain_helper()
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/usr/lib/python3.5/asyncio/streams.py", line 194, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/adam/github/ws34/websockets/websockets/test_protocol.py", line 699, in test_close_connection_lost
    self.loop.run_until_complete(self.protocol.close(reason='close'))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 337, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 121, in send
    return self.gen.send(value)
  File "/home/adam/github/ws34/websockets/websockets/protocol.py", line 217, in close
    yield from self.write_frame(OP_CLOSE, frame_data)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/home/adam/github/ws34/websockets/websockets/protocol.py", line 553, in write_frame
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006, no reason.

======================================================================
ERROR: test_connection_closed_attributes (websockets.test_protocol.ServerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adam/github/ws34/websockets/websockets/protocol.py", line 548, in write_frame
    yield from self.writer.drain()
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/usr/lib/python3.5/asyncio/streams.py", line 313, in drain
    yield from self._protocol._drain_helper()
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/usr/lib/python3.5/asyncio/streams.py", line 194, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/adam/github/ws34/websockets/websockets/test_protocol.py", line 620, in test_connection_closed_attributes
    self.loop.run_until_complete(self.protocol.close(reason='close'))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 337, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 121, in send
    return self.gen.send(value)
  File "/home/adam/github/ws34/websockets/websockets/protocol.py", line 217, in close
    yield from self.write_frame(OP_CLOSE, frame_data)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/home/adam/github/ws34/websockets/websockets/protocol.py", line 553, in write_frame
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, reason = close.

======================================================================
FAIL: test_remote_close (websockets.test_protocol.ClientTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adam/github/ws34/websockets/websockets/test_protocol.py", line 658, in test_remote_close
    self.assertConnectionClosed(1000, 'close')
  File "/home/adam/github/ws34/websockets/websockets/test_protocol.py", line 203, in assertConnectionClosed
    self.assertEqual(self.protocol.close_code, code)
AssertionError: 1006 != 1000

----------------------------------------------------------------------
Ran 228 tests in 14.177s

FAILED (failures=1, errors=9)
Exception ignored in: <generator object get at 0x7f9dedeef150>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/queues.py", line 170, in get
    getter.cancel()  # Just in case getter is not done yet.
  File "/usr/lib/python3.5/asyncio/futures.py", line 227, in cancel
    self._schedule_callbacks()
  File "/usr/lib/python3.5/asyncio/futures.py", line 242, in _schedule_callbacks
    self._loop.call_soon(callback, self)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 447, in call_soon
    handle = self._call_soon(callback, args)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 456, in _call_soon
    self._check_closed()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 284, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Makefile:5: recipe for target 'test' failed
make: *** [test] Error 1
```

**Comment by SzieberthAdam** [comment]
Well, I had the repo code in my `lib` since testing #84. That produced the failures. Today I went back to the original 3.5.0 asyncio which make all unittest to success. After that I force reinstalled 3.5.1 to check it with the release code. Then I pulled the lates asyncio code and tested with that again. It turned out that both 3.5.1 and latest repo code produces the failures above.

**Comment by aaugustin** [comment]
Aaaaw. I'll take a look.

The tests for connection closure are extremely precise. They break easily, but usually for a good reason.

**Comment by SzieberthAdam** [comment]
It seems that the asyncio fix which caused the weird behavior in #84 was released in 3.5.1. So only 3.5.0 was affected. So the fixes of 46741370aeaa may not be necessary. The asyncio fix was mainly causing `drain()` to raise exceptions instead of hiding them. All failures except the last one were caused by this behavior.

**Comment by aaugustin** [comment]
Unless I missed something, #84 also affected Python 3.4.

The fix I committed performs a feature-check for the asyncio fix that made it into Python 3.5.1, and if it isn't there, emulates it.

(I hope (1) there's only one change in asyncio involved and (2) we're talking about the same change. If not, this discussion is going to be very confusing!)

**Comment by SzieberthAdam** [comment]
My bad, for some reason I believed #84 was only affecting 3.5.0 which is not true. Now I am back on track and believe we are talking about the same change.

**Comment by SzieberthAdam** [comment]
Let me rephase the two confusing sentences in middle of https://github.com/aaugustin/websockets/issues/92#issuecomment-165035367: So versions 3.5.0 and below were affected by the asyncio bug. This implies that "Remove when dropping support for Python < 3.6" comments of 46741370aeaa could be modified to apply 3.5.1.

The rest of the previous comment stands.

**Comment by aaugustin** [comment]
Yes, that's correct.

As much as possible, I would like to support any bugfix release (3.5.x) within a given Python version (3.5). That's why the comment suggests to keep this code until we drop everything < 3.6.

**Comment by aaugustin** [comment]
It turns out that the fix is concise and also a clear improvement to the correctness of the test harness.
