### ISSUE TITLE
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

### ISSUE THREAD

**Issue by dima-dmytruk23** [aaugustin/websockets#920]
I am implementing a `websocket` connection between a client and a server with a webrtс connection established.

The server receives the data, processes it and sends the result to the client.

The server processes files using `aiofiles`. Also requests for `google api` go away.

But when posting a response - I get an error - _websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason_

When I work with files, the error flies out immediately. When I work with google api - after a while.
So I understand, is it related with a timeout of some kind?

```
await websocket.send_text("some text")
```
**Traceback**
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/m0nte-cr1st0/.virtualenvs/hypercube/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/m0nte-cr1st0/.virtualenvs/hypercube/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/m0nte-cr1st0/.virtualenvs/hypercube/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/m0nte-cr1st0/.virtualenvs/hypercube/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/home/m0nte-cr1st0/.virtualenvs/hypercube/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/m0nte-cr1st0/.virtualenvs/hypercube/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 157, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/home/m0nte-cr1st0/.virtualenvs/hypercube/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/m0nte-cr1st0/.virtualenvs/hypercube/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/m0nte-cr1st0/.virtualenvs/hypercube/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/m0nte-cr1st0/.virtualenvs/hypercube/lib/python3.8/site-packages/starlette/middleware/errors.py", line 146, in __call__
    await self.app(scope, receive, send)
  File "/home/m0nte-cr1st0/.virtualenvs/hypercube/lib/python3.8/site-packages/starlette/exceptions.py", line 58, in __call__
    await self.app(scope, receive, send)
  File "/home/m0nte-cr1st0/.virtualenvs/hypercube/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/m0nte-cr1st0/.virtualenvs/hypercube/lib/python3.8/site-packages/starlette/routing.py", line 283, in handle
    await self.app(scope, receive, send)
  File "/home/m0nte-cr1st0/.virtualenvs/hypercube/lib/python3.8/site-packages/starlette/routing.py", line 57, in app
    await func(session)
  File "/home/m0nte-cr1st0/.virtualenvs/hypercube/lib/python3.8/site-packages/fastapi/routing.py", line 247, in app
    await dependant.call(**values)
  File "./src/interfaces/websocket_consumer.py", line 15, in websocket_endpoint
    await manager.broadcast(data, websocket)
  File "./src/services/helpers/websocket_manager.py", line 47, in broadcast
    await websocket.send_text("some text")
  File "/home/m0nte-cr1st0/.virtualenvs/hypercube/lib/python3.8/site-packages/starlette/websockets.py", line 128, in send_text
    await self.send({"type": "websocket.send", "text": data})
  File "/home/m0nte-cr1st0/.virtualenvs/hypercube/lib/python3.8/site-packages/starlette/websockets.py", line 68, in send
    await self._send(message)
  File "/home/m0nte-cr1st0/.virtualenvs/hypercube/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 218, in asgi_send
    await self.send(data)
  File "/home/m0nte-cr1st0/.virtualenvs/hypercube/lib/python3.8/site-packages/websockets/protocol.py", line 555, in send
    await self.ensure_open()
  File "/home/m0nte-cr1st0/.virtualenvs/hypercube/lib/python3.8/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

**Comment by aaugustin** [comment]
This looks like a hard disconnect by the client. Do you have error logs on the client side? Perhaps the client receives something incorrect and closes summarily the connection?

**Comment by dima-dmytruk23** [comment]
@aaugustin thnx for the answer. I also think so.
On the client I see following logs
```
WebSocket is already in CLOSING or CLOSED state.
sendMessage @ Transcription.tsx:19
reader.onloadend @ Transcription.tsx:31
FileReader (async)
makeLink @ Transcription.tsx:28
recorder.current.ondataavailable @ Transcription.tsx:73
```
Also, I see that client receives first response from the server. In the next step - I get error..
![image](https://user-images.githubusercontent.com/76110682/111292845-47cca900-8651-11eb-810b-a9ca818c68ad.png)

**Comment by aaugustin** [comment]
I'm pretty sure you send something that the browser doesn't like and the browser closes the connection.

Then, when you try to send the next message, the connection is closed and you hit this error.

I don't think this is a problem in websockets, but rather in your payloads.
