### ISSUE TITLE
Error in opening handshake

### ISSUE THREAD

**Issue by AmirHmZz** [aaugustin/websockets#941]
When I call `serve()` function :
```python
await websockets.serve(
    self._test_handler, host="localhost", port=10234, ping_interval=20,
    ping_timeout=20, close_timeout=None, max_queue=4, compression=None,
    extensions=[
        permessage_deflate.ServerPerMessageDeflateFactory(
            server_no_context_takeover=False,
            client_no_context_takeover=False,
            server_max_window_bits=8,
            client_max_window_bits=8)])
```
Server runs without any error. but when I try to connect to my websocket server via a browser, I will get an error :
```python
Error in opening handshake
Traceback (most recent call last):
File "C:\Program Files\Python39\lib\site-packages\websockets\legacy\server.py", line 228, in handler
path = await self.handshake(
File "C:\Program Files\Python39\lib\site-packages\websockets\legacy\server.py", line 657, in handshake
extensions_header, self.extensions = self.process_extensions(
File "C:\Program Files\Python39\lib\site-packages\websockets\legacy\server.py", line 511, in process_extensions
response_params, extension = ext_factory.process_request_params(
File "C:\Program Files\Python39\lib\site-packages\websockets\extensions\permessage_deflate.py", line 608, in process_request_params
PerMessageDeflate(
File "C:\Program Files\Python39\lib\site-packages\websockets\extensions\permessage_deflate.py", line 74, in __init__
self.encoder = zlib.compressobj(
ValueError: Invalid initialization option
```

**Comment by aaugustin** [comment]
There's a can of worms around windows of 8 bits. Search for "zlib windowBits 8" to learn more. Could you try 9 instead of 8?

**Comment by AmirHmZz** [comment]
Yes error is because of zlib's bug. thanks
