### ISSUE TITLE
9.0.1 + python 3.9.4 :: module 'websockets' has no attribute 'client'

### ISSUE THREAD

**Issue by adriansev** [aaugustin/websockets#942]
@aaugustin  Hi! I just noticed on my dev machine (where the websockets was not upgraded before) that using `websockets.client.WebSocketClientProtocol` as the type returned by websockets.connect is no longer correct (or it never was but is was ignored..) as it throws things like:
```
File "/home.hdd/adrian/work-GRID/jalien_py/alienpy/alien.py", line 385, in <module>
async def IsWbConnected(wb: websockets.client.WebSocketClientProtocol) -> bool:
File "/home/adrian/.local/lib/python3.9/site-packages/websockets/imports.py", line 96, in __getattr__
raise AttributeError(f"module {package!r} has no attribute {name!r}")
AttributeError: module 'websockets' has no attribute 'client'
```
so, what is the correct type returned by connect?
also, do you have any idea why on python 3.6.8 this (websockets 9.0.1) still works but on 3.9 it does not?
Thank you!!

**Comment by adriansev** [comment]
oh, and also i get e message `module 'websockets.extensions' has no attribute 'permessage_deflate'`
my usage being:
```
deflateFact = websockets.extensions.permessage_deflate.ClientPerMessageDeflateFactory(compress_settings={'memLevel': 6},)
wb = await websockets.connect(fHostWSUrl, sock = socket_endpoint, server_hostname = host, ssl = ctx, extensions=[deflateFact, ],
max_queue=QUEUE_SIZE, max_size=MSG_SIZE, ping_interval=PING_INTERVAL, ping_timeout=PING_TIMEOUT, close_timeout=CLOSE_TIMEOUT)
```

i really do not understand what was changed ...

**Comment by adriansev** [comment]
actually this last one was solved by:
```
-import websockets.extensions
+from websockets.extensions import permessage_deflate
```
and
```
- deflateFact = websockets.extensions.permessage_deflate.ClientPerMessageDeflateFactory(compress_settings={'memLevel': 6},)
+ deflateFact = permessage_deflate.ClientPerMessageDeflateFactory(compress_settings={'memLevel': 6},)
```

**Comment by aaugustin** [comment]
In Python, you cannot rely on the fact that `import a` makes `a.b` or `a.b.c` available, even if you can `import a.b` or `import a.b.c`. If you're going to use an object from `a.b.c`, then you need to `import a.b.c`.

Here's an example of this in the standard library:

```
>>> import logging
>>> logging.handlers
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'logging' has no attribute 'handlers'
>>> import logging.handlers
>>> logging.handlers
<module 'logging.handlers' from '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/handlers.py'>
```

`import websockets` used to import all modules the library even if you used just the client or just the server — few projects need both. It's a bad choice I made super early in the project, and it's getting worse as I'm adding more modules.

This is why it was possible to use e.g. `websockets.client` after `import websockets`. However, you were relying on an implementation detail here.

It's considered OK in Python to move things around as long as imports continue working. Import compatibility is the baseline for backwards compatibility.

**Comment by adriansev** [comment]
@aaugustin ok, i see .. so, could please advise me what is the proper usage? should i also do `from websockets import connect as ws_connect` ?
also, if i do the exception treatment and i have `except websockets.exceptions.ConnectionClosed as e:` what should i do instead?  `import websockets.exceptions as ws_exceptions` and then do `except ws_exception.ConnectionClosed` ?
as for return type i do not thing that i really need to specify so this i will just skip...
Thanks a lot for info and pointers!! :)

**Comment by aaugustin** [comment]
Most public APIs of `websockets` are exposed directly in the root `websockets` module.

Intended usage is either:

```python
import websockets
websockets.connect
websockets.ConnectionClosed
```

or:
```python
from websockets import connect, ConnectionClosed
connect
ConnectionClosed
```

You don't need aliases unless you have name conflicts.
