### ISSUE TITLE
Unable to connect: code = 1006 (connection closed abnormally [internal]), no reason

### ISSUE THREAD

**Issue by WoLpH** [aaugustin/websockets#964]
For some reason I keep getting connection closed when connecting to this url. I can't figure out what's wrong with it honestly...

The code to reproduce:

```
import asyncio
import logging

import websockets


logger = logging.getLogger('websockets')
logger.setLevel(logging.DEBUG)
logger.addHandler(logging.StreamHandler())


async def main():
    async with websockets.connect(ping_interval=None, uri='wss://account.bit'
                                  'vavo.com/socket/') as ws:
        async for message in ws:
            print('msg', message)


if __name__ == '__main__':
    asyncio.run(main())
```

Debug output:
```
client - state = CONNECTING
client - event = connection_made(<asyncio.sslproto._SSLProtocolTransport object at 0x7fa4211af7c0>)
client > GET /socket/ HTTP/1.1
client > Headers([('Host', '...'), ('Upgrade', 'websocket'), ('Connection', 'Upgrade'), ('Sec-WebSocket-Key', 'agQGINo1LhASpkQRKQDYQA=='), ('Sec-WebSocket-Version', '13'), ('Sec-WebSocket-Extensions', 'permessage-deflate; client_max_window_bits'), ('User-Agent', 'Python/3.8 websockets/9.0.2')])
client - event = data_received(<362 bytes>)
client < HTTP/1.1 101 Switching Protocols
client < Headers([('Connection', 'upgrade'), ('Date', 'Mon, 17 May 2021 08:03:02 GMT'), ('Upgrade', 'websocket'), ('Sec-WebSocket-Accept', 'HGvUngvuyb7mu51KB40E+QnntEE='), ('X-Cache', 'Miss from cloudfront'), ('Via', '1.1 15bc83e8d3f23435c54d691169313d02.cloudfront.net (CloudFront)'), ('X-Amz-Cf-Pop', 'LHR3-C2'), ('X-Amz-Cf-Id', 'Mo9Jd_nj48Fd2bW5dM0mhLXlJTvLEIV3pH01uvgl0sMRM2uwTWY9mQ==')])
client - state = OPEN
client - event = connection_lost(None)
client - state = CLOSED
client x code = 1006, reason = [no reason]
client ! failing CLOSED WebSocket connection with code 1006
client x closing TCP connection
Traceback (most recent call last):
  File "websockets/legacy/protocol.py", line 750, in transfer_data
    message = await self.read_message()
  File "websockets/legacy/protocol.py", line 819, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "websockets/legacy/protocol.py", line 895, in read_data_frame
    frame = await self.read_frame(max_size)
  File "websockets/legacy/protocol.py", line 971, in read_frame
    frame = await Frame.read(
  File "websockets/legacy/framing.py", line 55, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 20, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "test.py", line 15, in main
    async for message in ws:
  File "websockets/legacy/protocol.py", line 356, in __aiter__
    yield await self.recv()
  File "websockets/legacy/protocol.py", line 421, in recv
    await self.ensure_open()
  File "websockets/legacy/protocol.py", line 726, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

**Comment by aaugustin** [comment]
FYI https://websockets.readthedocs.io/en/stable/contributing.html#bitcoin-users

**Comment by euri10** [comment]
> FYI https://websockets.readthedocs.io/en/stable/contributing.html#bitcoin-users

this made my day, bravo !

**Comment by lgrahl** [comment]
I think @aaugustin forgot to close. Although this might sound rude, we're not free debugging support for remote live servers. :slightly_smiling_face:

**Comment by WoLpH** [comment]
Ok, fair enough :)
