### ISSUE TITLE
Force server using self-signed cert to require valid client certificate

### ISSUE THREAD

**Issue by marksaenger** [aaugustin/websockets#982]
Hoping someone can help here!

Is it possible to enforce valid certificates between a server and client?  I want to configure a server such that a client MUST provide a valid certificate before establishing a connection.  I don't want a random client to be able to just disable cert verification and then be able to connect to the server.

I've been following the `secure_client.py` and `secure_server.py` self-signed cert examples in https://github.com/aaugustin/websockets/blob/main/example and that works just fine.  Removing the cert on the client side fails as expected, but I'm able to get around that by using `ssl.PROTOCOL_TLSv1_2` in place of `ssl.PROTOCOL_TLS_CLIENT` and then removing the call to `ssl_context.load_verify_locations()`.  Then I'm able to connect to the same server without having a valid cert.

I went back to the standard client example without the changes above and tried adding `ssl_context.verify_mode = ssl.CERT_REQUIRED` on the server.  I got the following exceptions on the client side with no output from the server.

```
Traceback (most recent call last):
  File "/home/msaenger/.local/lib/python3.7/site-packages/websockets/legacy/client.py", line 192, in read_http_response
    status_code, reason, headers = await read_response(self.reader)
  File "/home/me/.local/lib/python3.7/site-packages/websockets/legacy/http.py", line 112, in read_response
    status_line = await read_line(stream)
  File "/home/me/.local/lib/python3.7/site-packages/websockets/legacy/http.py", line 186, in read_line
    line = await stream.readline()
  File "/usr/lib/python3.7/asyncio/streams.py", line 496, in readline
    line = await self.readuntil(sep)
  File "/usr/lib/python3.7/asyncio/streams.py", line 588, in readuntil
    await self._wait_for_data('readuntil')
  File "/usr/lib/python3.7/asyncio/streams.py", line 473, in _wait_for_data
    await self._waiter
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 804, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test_client_ssl.py", line 40, in <module>
    asyncio.get_event_loop().run_until_complete(hello())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "test_client_ssl.py", line 23, in hello
    uri, ssl=ssl_context
  File "/home/me/.local/lib/python3.7/site-packages/websockets/legacy/client.py", line 604, in __aenter__
    return await self
  File "/home/me/.local/lib/python3.7/site-packages/websockets/legacy/client.py", line 634, in __await_impl__
    extra_headers=protocol.extra_headers,
  File "/home/me/.local/lib/python3.7/site-packages/websockets/legacy/client.py", line 382, in handshake
    status_code, response_headers = await self.read_http_response()
  File "/home/me/.local/lib/python3.7/site-packages/websockets/legacy/client.py", line 198, in read_http_response
    raise InvalidMessage("did not receive a valid HTTP response") from exc
websockets.exceptions.InvalidMessage: did not receive a valid HTTP response
```

It seems as though the server is just closing the connection but I can't figure out why.  Enabling DEBUG logs outputs the following:  (this doesn't seem to help much)

```
client - state = CONNECTING
client - event = connection_made(<asyncio.sslproto._SSLProtocolTransport object at 0x7f6e355ad490>)
client > GET / HTTP/1.1
client > Headers([('Host', 'localhost:8765'), ('Upgrade', 'websocket'), ('Connection', 'Upgrade'), ('Sec-WebSocket-Key', 'qsup1mPeLDusQvtlcScCnQ=='), ('Sec-WebSocket-Version', '13'), ('Sec-WebSocket-Extensions', 'permessage-deflate; client_max_window_bits'), ('User-Agent', 'Python/3.7 websockets/9.1')])
client - event = connection_lost([Errno 104] Connection reset by peer)
client - state = CLOSED
client x code = 1006, reason = [no reason]
client ! failing CLOSED WebSocket connection with code 1006
client x closing TCP connection
```

**Comment by aaugustin** [comment]
I suspect your question is more about asyncio than websockets.

If you find the correct `ssl` parameters forl [start_server](https://docs.python.org/3/library/asyncio-stream.html#asyncio.start_server) and [open_connection](https://docs.python.org/3/library/asyncio-stream.html#asyncio.open_connection), giving the same to websockets should work.

**Comment by aaugustin** [comment]
Please reopen if you can make it work with asyncio and it doesn't work with websockets. Else, this is an asyncio question :-)

**Comment by marksaenger** [comment]
Turns out I didn't quite understand the auth process between server and client.  I was able to do what I wanted and as you suspected it had nothing to do with websockets.  Thanks for the hint!
