### ISSUE TITLE
cyclic import causing failure in uvicorn test suite

### ISSUE THREAD

**Issue by graingert** [aaugustin/websockets#989]
```
>>> from websockets.extensions.permessage_deflate import ServerPerMessageDeflateFactory
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/graingert/projects/uvicorn/venv/lib/python3.10/site-packages/websockets/extensions/__init__.py", line 1, in <module>
    from .base import *
  File "/home/graingert/projects/uvicorn/venv/lib/python3.10/site-packages/websockets/extensions/base.py", line 13, in <module>
    from ..frames import Frame
  File "/home/graingert/projects/uvicorn/venv/lib/python3.10/site-packages/websockets/frames.py", line 13, in <module>
    from .exceptions import PayloadTooBig, ProtocolError
  File "/home/graingert/projects/uvicorn/venv/lib/python3.10/site-packages/websockets/exceptions.py", line 351, in <module>
    from .frames import format_close  # noqa
ImportError: cannot import name 'format_close' from partially initialized module 'websockets.frames' (most likely due to a circular import) (/home/graingert/projects/uvicorn/venv/lib/python3.10/site-packages/websockets/frames.py)
>>>
```

**Comment by aaugustin** [comment]
Yes, I saw it a few days ago, it's on my radar. Type annotations take the "avoid import cycles" game to the next level!
