### ISSUE TITLE
Python prompt as code = 1001 (going away), no reason

### ISSUE THREAD

**Issue by lolisound** [aaugustin/websockets#990]
My code is like this,
``` python
connected = set()
async def live_server(websocket, path):
    connected.add(websocket)
    try:
        while True:
            if not q.empty():
                message = q.get()
                await asyncio.wait([asyncio.ensure_future(ws.send(message)) for ws in connected])
            await asyncio.sleep(1)
    finally:
        connected.remove(websocket)

async def main():
    start_server = websockets.serve(live_server, 'localhost', 5678)
    await start_server
    await room.connect() # Keep connected to another service

if __name__ == "__main__":
    asyncio.run(main())
```

When I connect from a browser, and refresh page, python will prompt as follows

```
Task exception was never retrieved
future: <Task finished name='Task-26' coro=<WebSocketCommonProtocol.send() done, defined at C:\Users\Misaka\AppData\Local\Programs\Python\Python39\lib\site-packages\websockets\legacy\protocol.py:433> exception=ConnectionClosedOK('code = 1001 (going away), no reason')>
Traceback (most recent call last):
  File "C:\Users\Misaka\AppData\Local\Programs\Python\Python39\lib\site-packages\websockets\legacy\protocol.py", line 471, in send
    await self.ensure_open()
  File "C:\Users\Misaka\AppData\Local\Programs\Python\Python39\lib\site-packages\websockets\legacy\protocol.py", line 726, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: code = 1001 (going away), no reason
```

I saw #397, That is to say don't treat close code 1001 as an error.
In addition, the program is currently running normally, I am not sure if this issue has an impact.

**Comment by aaugustin** [comment]
This exception is the expected behavior when the browser closes a connection.

Maybe it's logged because you never recover the result of `asyncio.ensure_future(ws.send(message))`. I'm not completely sure how to deal properly with tasks raising exceptions in `asyncio.wait([...])`. You'd have the same logging behavior with any other task that could raise an exception inside `asyncio.wait([...])`, so that part is really a question about asyncio.
