### ISSUE TITLE
legacy tests fail with timeout

### ISSUE THREAD

**Issue by DerDakon** [aaugustin/websockets#997]
The machine is a Sun T5120, which is not exactly slow with 1.4 GHz, but not the fastest machine either. And when something runs in parallel on one of the many threads things easily jitter for a few ms.

```
======================================================================
FAIL: test_local_close_connection_lost_timeout_after_close (tests.legacy.test_protocol.ClientTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/websockets-9.1/work/websockets-9.1/tests/legacy/test_protocol.py", line 1458, in test_local_close_connection_lost_timeout_after_close
    self.loop.run_until_complete(self.protocol.close(reason="close"))
  File "/usr/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/var/tmp/portage/dev-python/websockets-9.1/work/websockets-9.1/tests/legacy/test_protocol.py", line 309, in assertCompletesWithin
    self.assertLess(dt, max_time, f"Too slow: {dt} >= {max_time}")
AssertionError: 0.04470174902235158 not less than 0.039 : Too slow: 0.04470174902235158 >= 0.039

======================================================================
FAIL: test_local_close_connection_lost_timeout_after_write_eof (tests.legacy.test_protocol.ClientTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/websockets-9.1/work/websockets-9.1/tests/legacy/test_protocol.py", line 1440, in test_local_close_connection_lost_timeout_after_write_eof
    self.loop.run_until_complete(self.protocol.close(reason="close"))
  File "/usr/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/var/tmp/portage/dev-python/websockets-9.1/work/websockets-9.1/tests/legacy/test_protocol.py", line 309, in assertCompletesWithin
    self.assertLess(dt, max_time, f"Too slow: {dt} >= {max_time}")
AssertionError: 0.033755247975932434 not less than 0.029 : Too slow: 0.033755247975932434 >= 0.029

======================================================================
FAIL: test_local_close_receive_close_frame_timeout (tests.legacy.test_protocol.ClientTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/websockets-9.1/work/websockets-9.1/tests/legacy/test_protocol.py", line 1426, in test_local_close_receive_close_frame_timeout
    self.loop.run_until_complete(self.protocol.close(reason="close"))
  File "/usr/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/var/tmp/portage/dev-python/websockets-9.1/work/websockets-9.1/tests/legacy/test_protocol.py", line 309, in assertCompletesWithin
    self.assertLess(dt, max_time, f"Too slow: {dt} >= {max_time}")
AssertionError: 0.03307468199636787 not less than 0.029 : Too slow: 0.03307468199636787 >= 0.029

======================================================================
FAIL: test_local_close_send_close_frame_timeout (tests.legacy.test_protocol.ClientTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/websockets-9.1/work/websockets-9.1/tests/legacy/test_protocol.py", line 1416, in test_local_close_send_close_frame_timeout
    self.loop.run_until_complete(self.protocol.close(reason="close"))
  File "/usr/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/var/tmp/portage/dev-python/websockets-9.1/work/websockets-9.1/tests/legacy/test_protocol.py", line 309, in assertCompletesWithin
    self.assertLess(dt, max_time, f"Too slow: {dt} >= {max_time}")
AssertionError: 0.02918602799763903 not less than 0.029 : Too slow: 0.02918602799763903 >= 0.029

======================================================================
FAIL: test_local_close_connection_lost_timeout_after_close (tests.legacy.test_protocol.ServerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/websockets-9.1/work/websockets-9.1/tests/legacy/test_protocol.py", line 1398, in test_local_close_connection_lost_timeout_after_close
    self.loop.run_until_complete(self.protocol.close(reason="close"))
  File "/usr/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/var/tmp/portage/dev-python/websockets-9.1/work/websockets-9.1/tests/legacy/test_protocol.py", line 309, in assertCompletesWithin
    self.assertLess(dt, max_time, f"Too slow: {dt} >= {max_time}")
AssertionError: 0.03377306702896021 not less than 0.029 : Too slow: 0.03377306702896021 >= 0.029

======================================================================
FAIL: test_local_close_connection_lost_timeout_after_write_eof (tests.legacy.test_protocol.ServerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/websockets-9.1/work/websockets-9.1/tests/legacy/test_protocol.py", line 1383, in test_local_close_connection_lost_timeout_after_write_eof
    self.loop.run_until_complete(self.protocol.close(reason="close"))
  File "/usr/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/var/tmp/portage/dev-python/websockets-9.1/work/websockets-9.1/tests/legacy/test_protocol.py", line 309, in assertCompletesWithin
    self.assertLess(dt, max_time, f"Too slow: {dt} >= {max_time}")
AssertionError: 0.024274351977510378 not less than 0.019 : Too slow: 0.024274351977510378 >= 0.019

======================================================================
FAIL: test_local_close_receive_close_frame_timeout (tests.legacy.test_protocol.ServerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/websockets-9.1/work/websockets-9.1/tests/legacy/test_protocol.py", line 1371, in test_local_close_receive_close_frame_timeout
    self.loop.run_until_complete(self.protocol.close(reason="close"))
  File "/usr/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/var/tmp/portage/dev-python/websockets-9.1/work/websockets-9.1/tests/legacy/test_protocol.py", line 309, in assertCompletesWithin
    self.assertLess(dt, max_time, f"Too slow: {dt} >= {max_time}")
AssertionError: 0.022360372997354716 not less than 0.019 : Too slow: 0.022360372997354716 >= 0.019

----------------------------------------------------------------------
Ran 888 tests in 29.628s
```

**Comment by lgrahl** [comment]
Tests like these are prone to fail for a wide range of machines. The results all look like they're in an acceptable range considering your machine. If having those tests fail on your machine, I'd suggest making a PR to apply a global modifier on all test time windows.

**Comment by aaugustin** [comment]
Use this:

https://github.com/aaugustin/websockets/blob/897d1b27f362c4113308e76b989321ece3bfd4af/tests/legacy/utils.py#L85-L87

**Comment by lgrahl** [comment]
Oh it already existed. :woman_facepalming: :sweat_smile:
